// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/analyzer.dart';
import 'api/model.dart';
import 'core/spend_path.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiAnalyzerInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1693999108;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_deadbolt',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<APIAnalysisResult> crateApiAnalyzerAnalyzeDescriptor({
    required String descriptor,
  });

  Future<APIAbsoluteTimelock> crateApiModelApiAbsoluteTimelockFromConsensus({
    required int consensus,
  });

  Future<int> crateApiModelApiAbsoluteTimelockToConsensus({
    required APIAbsoluteTimelock that,
  });

  Future<APIPolicyPath> crateApiModelApiPolicyPathDefault();

  Future<List<APIPolicyPath>> crateApiModelApiPolicyPathFromSpendpath({
    required SpendPath spendPath,
  });

  Future<APIRelativeTimelock> crateApiModelApiRelativeTimelockFromConsensus({
    required int consensus,
  });

  Future<int> crateApiModelApiRelativeTimelockToConsensus({
    required APIRelativeTimelock that,
  });

  Future<List<APISpendPath>> crateApiModelApiSpendPathFromSorted({
    required List<SpendPath> coreSpendPaths,
  });

  Future<String> crateApiAnalyzerBuildDescriptor({
    required APIWalletType walletType,
    required List<APIPubKey> keys,
    required List<APISpendPathDef> spendPaths,
  });

  Future<int> crateApiAnalyzerCalculateRustidFromTimelocks({
    required int threshold,
    required List<String> mfps,
    required APIRelativeTimelock relTimelock,
    required APIAbsoluteTimelock absTimelock,
  });

  Future<int> crateApiAnalyzerCalculateSpendPathId({
    required int threshold,
    required List<String> mfps,
    required int relTimelock,
    required int absTimelock,
  });

  Future<APIAbsoluteTimelock> crateApiAnalyzerDecodeLegacyAbsTimelock({
    required int consensus,
  });

  Future<APIRelativeTimelock> crateApiAnalyzerDecodeLegacyRelTimelock({
    required int consensus,
  });

  Future<void> crateApiAnalyzerInitApp();

  Future<void> crateApiAnalyzerValidateKey({
    required String mfp,
    required String derivationPath,
    required String xpub,
    required APINetwork network,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SpendPath;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SpendPath;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_SpendPathPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<APIAnalysisResult> crateApiAnalyzerAnalyzeDescriptor({
    required String descriptor,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(descriptor, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_analysis_result,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAnalyzerAnalyzeDescriptorConstMeta,
        argValues: [descriptor],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAnalyzerAnalyzeDescriptorConstMeta =>
      const TaskConstMeta(
        debugName: "analyze_descriptor",
        argNames: ["descriptor"],
      );

  @override
  Future<APIAbsoluteTimelock> crateApiModelApiAbsoluteTimelockFromConsensus({
    required int consensus,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(consensus, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_absolute_timelock,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiModelApiAbsoluteTimelockFromConsensusConstMeta,
        argValues: [consensus],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModelApiAbsoluteTimelockFromConsensusConstMeta =>
      const TaskConstMeta(
        debugName: "api_absolute_timelock_from_consensus",
        argNames: ["consensus"],
      );

  @override
  Future<int> crateApiModelApiAbsoluteTimelockToConsensus({
    required APIAbsoluteTimelock that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_api_absolute_timelock(that, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiModelApiAbsoluteTimelockToConsensusConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModelApiAbsoluteTimelockToConsensusConstMeta =>
      const TaskConstMeta(
        debugName: "api_absolute_timelock_to_consensus",
        argNames: ["that"],
      );

  @override
  Future<APIPolicyPath> crateApiModelApiPolicyPathDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_policy_path,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiModelApiPolicyPathDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModelApiPolicyPathDefaultConstMeta =>
      const TaskConstMeta(debugName: "api_policy_path_default", argNames: []);

  @override
  Future<List<APIPolicyPath>> crateApiModelApiPolicyPathFromSpendpath({
    required SpendPath spendPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpendPath(
            spendPath,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_api_policy_path,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiModelApiPolicyPathFromSpendpathConstMeta,
        argValues: [spendPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModelApiPolicyPathFromSpendpathConstMeta =>
      const TaskConstMeta(
        debugName: "api_policy_path_from_spendpath",
        argNames: ["spendPath"],
      );

  @override
  Future<APIRelativeTimelock> crateApiModelApiRelativeTimelockFromConsensus({
    required int consensus,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(consensus, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_relative_timelock,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiModelApiRelativeTimelockFromConsensusConstMeta,
        argValues: [consensus],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModelApiRelativeTimelockFromConsensusConstMeta =>
      const TaskConstMeta(
        debugName: "api_relative_timelock_from_consensus",
        argNames: ["consensus"],
      );

  @override
  Future<int> crateApiModelApiRelativeTimelockToConsensus({
    required APIRelativeTimelock that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_api_relative_timelock(that, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiModelApiRelativeTimelockToConsensusConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModelApiRelativeTimelockToConsensusConstMeta =>
      const TaskConstMeta(
        debugName: "api_relative_timelock_to_consensus",
        argNames: ["that"],
      );

  @override
  Future<List<APISpendPath>> crateApiModelApiSpendPathFromSorted({
    required List<SpendPath> coreSpendPaths,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpendPath(
            coreSpendPaths,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_api_spend_path,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiModelApiSpendPathFromSortedConstMeta,
        argValues: [coreSpendPaths],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiModelApiSpendPathFromSortedConstMeta =>
      const TaskConstMeta(
        debugName: "api_spend_path_from_sorted",
        argNames: ["coreSpendPaths"],
      );

  @override
  Future<String> crateApiAnalyzerBuildDescriptor({
    required APIWalletType walletType,
    required List<APIPubKey> keys,
    required List<APISpendPathDef> spendPaths,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_api_wallet_type(walletType, serializer);
          sse_encode_list_api_pub_key(keys, serializer);
          sse_encode_list_api_spend_path_def(spendPaths, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAnalyzerBuildDescriptorConstMeta,
        argValues: [walletType, keys, spendPaths],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAnalyzerBuildDescriptorConstMeta =>
      const TaskConstMeta(
        debugName: "build_descriptor",
        argNames: ["walletType", "keys", "spendPaths"],
      );

  @override
  Future<int> crateApiAnalyzerCalculateRustidFromTimelocks({
    required int threshold,
    required List<String> mfps,
    required APIRelativeTimelock relTimelock,
    required APIAbsoluteTimelock absTimelock,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(threshold, serializer);
          sse_encode_list_String(mfps, serializer);
          sse_encode_box_autoadd_api_relative_timelock(relTimelock, serializer);
          sse_encode_box_autoadd_api_absolute_timelock(absTimelock, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAnalyzerCalculateRustidFromTimelocksConstMeta,
        argValues: [threshold, mfps, relTimelock, absTimelock],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAnalyzerCalculateRustidFromTimelocksConstMeta =>
      const TaskConstMeta(
        debugName: "calculate_rustid_from_timelocks",
        argNames: ["threshold", "mfps", "relTimelock", "absTimelock"],
      );

  @override
  Future<int> crateApiAnalyzerCalculateSpendPathId({
    required int threshold,
    required List<String> mfps,
    required int relTimelock,
    required int absTimelock,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_32(threshold, serializer);
          sse_encode_list_String(mfps, serializer);
          sse_encode_u_32(relTimelock, serializer);
          sse_encode_u_32(absTimelock, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAnalyzerCalculateSpendPathIdConstMeta,
        argValues: [threshold, mfps, relTimelock, absTimelock],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAnalyzerCalculateSpendPathIdConstMeta =>
      const TaskConstMeta(
        debugName: "calculate_spend_path_id",
        argNames: ["threshold", "mfps", "relTimelock", "absTimelock"],
      );

  @override
  Future<APIAbsoluteTimelock> crateApiAnalyzerDecodeLegacyAbsTimelock({
    required int consensus,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(consensus, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_absolute_timelock,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAnalyzerDecodeLegacyAbsTimelockConstMeta,
        argValues: [consensus],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAnalyzerDecodeLegacyAbsTimelockConstMeta =>
      const TaskConstMeta(
        debugName: "decode_legacy_abs_timelock",
        argNames: ["consensus"],
      );

  @override
  Future<APIRelativeTimelock> crateApiAnalyzerDecodeLegacyRelTimelock({
    required int consensus,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(consensus, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_relative_timelock,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAnalyzerDecodeLegacyRelTimelockConstMeta,
        argValues: [consensus],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAnalyzerDecodeLegacyRelTimelockConstMeta =>
      const TaskConstMeta(
        debugName: "decode_legacy_rel_timelock",
        argNames: ["consensus"],
      );

  @override
  Future<void> crateApiAnalyzerInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAnalyzerInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAnalyzerInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiAnalyzerValidateKey({
    required String mfp,
    required String derivationPath,
    required String xpub,
    required APINetwork network,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mfp, serializer);
          sse_encode_String(derivationPath, serializer);
          sse_encode_String(xpub, serializer);
          sse_encode_api_network(network, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAnalyzerValidateKeyConstMeta,
        argValues: [mfp, derivationPath, xpub, network],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAnalyzerValidateKeyConstMeta =>
      const TaskConstMeta(
        debugName: "validate_key",
        argNames: ["mfp", "derivationPath", "xpub", "network"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SpendPath => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpendPath;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SpendPath => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpendPath;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  SpendPath
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpendPath(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SpendPathImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SpendPath
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpendPath(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SpendPathImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  SpendPath
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpendPath(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SpendPathImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  APIAbsoluteTimelock dco_decode_api_absolute_timelock(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return APIAbsoluteTimelock(
      timelockType: dco_decode_api_absolute_timelock_type(arr[0]),
      value: dco_decode_u_32(arr[1]),
    );
  }

  @protected
  APIAbsoluteTimelockType dco_decode_api_absolute_timelock_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return APIAbsoluteTimelockType.values[raw as int];
  }

  @protected
  APIAnalysisResult dco_decode_api_analysis_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return APIAnalysisResult(
      descriptor: dco_decode_String(arr[0]),
      network: dco_decode_api_network(arr[1]),
      walletType: dco_decode_api_wallet_type(arr[2]),
      keys: dco_decode_list_api_pub_key(arr[3]),
      spendPaths: dco_decode_list_api_spend_path(arr[4]),
    );
  }

  @protected
  APINetwork dco_decode_api_network(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return APINetwork.values[raw as int];
  }

  @protected
  APIPolicyPath dco_decode_api_policy_path(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return APIPolicyPath(
      policyId: dco_decode_String(arr[0]),
      path: dco_decode_list_prim_u_32_strict(arr[1]),
    );
  }

  @protected
  APIPubKey dco_decode_api_pub_key(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return APIPubKey(
      mfp: dco_decode_String(arr[0]),
      derivationPath: dco_decode_String(arr[1]),
      xpub: dco_decode_String(arr[2]),
    );
  }

  @protected
  APIRelativeTimelock dco_decode_api_relative_timelock(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return APIRelativeTimelock(
      timelockType: dco_decode_api_relative_timelock_type(arr[0]),
      value: dco_decode_u_32(arr[1]),
    );
  }

  @protected
  APIRelativeTimelockType dco_decode_api_relative_timelock_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return APIRelativeTimelockType.values[raw as int];
  }

  @protected
  APISpendPath dco_decode_api_spend_path(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return APISpendPath(
      id: dco_decode_u_32(arr[0]),
      policyPath: dco_decode_list_api_policy_path(arr[1]),
      threshold: dco_decode_u_32(arr[2]),
      mfps: dco_decode_list_String(arr[3]),
      relTimelock: dco_decode_api_relative_timelock(arr[4]),
      absTimelock: dco_decode_api_absolute_timelock(arr[5]),
      wuBase: dco_decode_u_32(arr[6]),
      wuIn: dco_decode_u_32(arr[7]),
      wuOut: dco_decode_u_32(arr[8]),
      trDepth: dco_decode_i_32(arr[9]),
      vbSweep: dco_decode_f_32(arr[10]),
    );
  }

  @protected
  APISpendPathDef dco_decode_api_spend_path_def(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return APISpendPathDef(
      threshold: dco_decode_u_32(arr[0]),
      mfps: dco_decode_list_String(arr[1]),
      relTimelock: dco_decode_api_relative_timelock(arr[2]),
      absTimelock: dco_decode_api_absolute_timelock(arr[3]),
      isKeyPath: dco_decode_bool(arr[4]),
      priority: dco_decode_u_32(arr[5]),
    );
  }

  @protected
  APIWalletType dco_decode_api_wallet_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return APIWalletType.values[raw as int];
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  APIAbsoluteTimelock dco_decode_box_autoadd_api_absolute_timelock(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_api_absolute_timelock(raw);
  }

  @protected
  APIRelativeTimelock dco_decode_box_autoadd_api_relative_timelock(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_api_relative_timelock(raw);
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<SpendPath>
  dco_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpendPath(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(
          dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpendPath,
        )
        .toList();
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<APIPolicyPath> dco_decode_list_api_policy_path(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_api_policy_path).toList();
  }

  @protected
  List<APIPubKey> dco_decode_list_api_pub_key(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_api_pub_key).toList();
  }

  @protected
  List<APISpendPath> dco_decode_list_api_spend_path(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_api_spend_path).toList();
  }

  @protected
  List<APISpendPathDef> dco_decode_list_api_spend_path_def(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_api_spend_path_def).toList();
  }

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint32List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  SpendPath
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpendPath(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SpendPathImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SpendPath
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpendPath(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SpendPathImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SpendPath
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpendPath(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SpendPathImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  APIAbsoluteTimelock sse_decode_api_absolute_timelock(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_timelockType = sse_decode_api_absolute_timelock_type(deserializer);
    var var_value = sse_decode_u_32(deserializer);
    return APIAbsoluteTimelock(
      timelockType: var_timelockType,
      value: var_value,
    );
  }

  @protected
  APIAbsoluteTimelockType sse_decode_api_absolute_timelock_type(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return APIAbsoluteTimelockType.values[inner];
  }

  @protected
  APIAnalysisResult sse_decode_api_analysis_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_descriptor = sse_decode_String(deserializer);
    var var_network = sse_decode_api_network(deserializer);
    var var_walletType = sse_decode_api_wallet_type(deserializer);
    var var_keys = sse_decode_list_api_pub_key(deserializer);
    var var_spendPaths = sse_decode_list_api_spend_path(deserializer);
    return APIAnalysisResult(
      descriptor: var_descriptor,
      network: var_network,
      walletType: var_walletType,
      keys: var_keys,
      spendPaths: var_spendPaths,
    );
  }

  @protected
  APINetwork sse_decode_api_network(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return APINetwork.values[inner];
  }

  @protected
  APIPolicyPath sse_decode_api_policy_path(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_policyId = sse_decode_String(deserializer);
    var var_path = sse_decode_list_prim_u_32_strict(deserializer);
    return APIPolicyPath(policyId: var_policyId, path: var_path);
  }

  @protected
  APIPubKey sse_decode_api_pub_key(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_mfp = sse_decode_String(deserializer);
    var var_derivationPath = sse_decode_String(deserializer);
    var var_xpub = sse_decode_String(deserializer);
    return APIPubKey(
      mfp: var_mfp,
      derivationPath: var_derivationPath,
      xpub: var_xpub,
    );
  }

  @protected
  APIRelativeTimelock sse_decode_api_relative_timelock(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_timelockType = sse_decode_api_relative_timelock_type(deserializer);
    var var_value = sse_decode_u_32(deserializer);
    return APIRelativeTimelock(
      timelockType: var_timelockType,
      value: var_value,
    );
  }

  @protected
  APIRelativeTimelockType sse_decode_api_relative_timelock_type(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return APIRelativeTimelockType.values[inner];
  }

  @protected
  APISpendPath sse_decode_api_spend_path(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_32(deserializer);
    var var_policyPath = sse_decode_list_api_policy_path(deserializer);
    var var_threshold = sse_decode_u_32(deserializer);
    var var_mfps = sse_decode_list_String(deserializer);
    var var_relTimelock = sse_decode_api_relative_timelock(deserializer);
    var var_absTimelock = sse_decode_api_absolute_timelock(deserializer);
    var var_wuBase = sse_decode_u_32(deserializer);
    var var_wuIn = sse_decode_u_32(deserializer);
    var var_wuOut = sse_decode_u_32(deserializer);
    var var_trDepth = sse_decode_i_32(deserializer);
    var var_vbSweep = sse_decode_f_32(deserializer);
    return APISpendPath(
      id: var_id,
      policyPath: var_policyPath,
      threshold: var_threshold,
      mfps: var_mfps,
      relTimelock: var_relTimelock,
      absTimelock: var_absTimelock,
      wuBase: var_wuBase,
      wuIn: var_wuIn,
      wuOut: var_wuOut,
      trDepth: var_trDepth,
      vbSweep: var_vbSweep,
    );
  }

  @protected
  APISpendPathDef sse_decode_api_spend_path_def(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_threshold = sse_decode_u_32(deserializer);
    var var_mfps = sse_decode_list_String(deserializer);
    var var_relTimelock = sse_decode_api_relative_timelock(deserializer);
    var var_absTimelock = sse_decode_api_absolute_timelock(deserializer);
    var var_isKeyPath = sse_decode_bool(deserializer);
    var var_priority = sse_decode_u_32(deserializer);
    return APISpendPathDef(
      threshold: var_threshold,
      mfps: var_mfps,
      relTimelock: var_relTimelock,
      absTimelock: var_absTimelock,
      isKeyPath: var_isKeyPath,
      priority: var_priority,
    );
  }

  @protected
  APIWalletType sse_decode_api_wallet_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return APIWalletType.values[inner];
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  APIAbsoluteTimelock sse_decode_box_autoadd_api_absolute_timelock(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_api_absolute_timelock(deserializer));
  }

  @protected
  APIRelativeTimelock sse_decode_box_autoadd_api_relative_timelock(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_api_relative_timelock(deserializer));
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<SpendPath>
  sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpendPath(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SpendPath>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(
        sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpendPath(
          deserializer,
        ),
      );
    }
    return ans_;
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<APIPolicyPath> sse_decode_list_api_policy_path(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <APIPolicyPath>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_api_policy_path(deserializer));
    }
    return ans_;
  }

  @protected
  List<APIPubKey> sse_decode_list_api_pub_key(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <APIPubKey>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_api_pub_key(deserializer));
    }
    return ans_;
  }

  @protected
  List<APISpendPath> sse_decode_list_api_spend_path(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <APISpendPath>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_api_spend_path(deserializer));
    }
    return ans_;
  }

  @protected
  List<APISpendPathDef> sse_decode_list_api_spend_path_def(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <APISpendPathDef>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_api_spend_path_def(deserializer));
    }
    return ans_;
  }

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint32List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpendPath(
    SpendPath self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SpendPathImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpendPath(
    SpendPath self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SpendPathImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpendPath(
    SpendPath self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SpendPathImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_api_absolute_timelock(
    APIAbsoluteTimelock self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_api_absolute_timelock_type(self.timelockType, serializer);
    sse_encode_u_32(self.value, serializer);
  }

  @protected
  void sse_encode_api_absolute_timelock_type(
    APIAbsoluteTimelockType self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_api_analysis_result(
    APIAnalysisResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.descriptor, serializer);
    sse_encode_api_network(self.network, serializer);
    sse_encode_api_wallet_type(self.walletType, serializer);
    sse_encode_list_api_pub_key(self.keys, serializer);
    sse_encode_list_api_spend_path(self.spendPaths, serializer);
  }

  @protected
  void sse_encode_api_network(APINetwork self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_api_policy_path(
    APIPolicyPath self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.policyId, serializer);
    sse_encode_list_prim_u_32_strict(self.path, serializer);
  }

  @protected
  void sse_encode_api_pub_key(APIPubKey self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.mfp, serializer);
    sse_encode_String(self.derivationPath, serializer);
    sse_encode_String(self.xpub, serializer);
  }

  @protected
  void sse_encode_api_relative_timelock(
    APIRelativeTimelock self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_api_relative_timelock_type(self.timelockType, serializer);
    sse_encode_u_32(self.value, serializer);
  }

  @protected
  void sse_encode_api_relative_timelock_type(
    APIRelativeTimelockType self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_api_spend_path(APISpendPath self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.id, serializer);
    sse_encode_list_api_policy_path(self.policyPath, serializer);
    sse_encode_u_32(self.threshold, serializer);
    sse_encode_list_String(self.mfps, serializer);
    sse_encode_api_relative_timelock(self.relTimelock, serializer);
    sse_encode_api_absolute_timelock(self.absTimelock, serializer);
    sse_encode_u_32(self.wuBase, serializer);
    sse_encode_u_32(self.wuIn, serializer);
    sse_encode_u_32(self.wuOut, serializer);
    sse_encode_i_32(self.trDepth, serializer);
    sse_encode_f_32(self.vbSweep, serializer);
  }

  @protected
  void sse_encode_api_spend_path_def(
    APISpendPathDef self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.threshold, serializer);
    sse_encode_list_String(self.mfps, serializer);
    sse_encode_api_relative_timelock(self.relTimelock, serializer);
    sse_encode_api_absolute_timelock(self.absTimelock, serializer);
    sse_encode_bool(self.isKeyPath, serializer);
    sse_encode_u_32(self.priority, serializer);
  }

  @protected
  void sse_encode_api_wallet_type(
    APIWalletType self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_api_absolute_timelock(
    APIAbsoluteTimelock self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_api_absolute_timelock(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_api_relative_timelock(
    APIRelativeTimelock self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_api_relative_timelock(self, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void
  sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpendPath(
    List<SpendPath> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpendPath(
        item,
        serializer,
      );
    }
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_api_policy_path(
    List<APIPolicyPath> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_api_policy_path(item, serializer);
    }
  }

  @protected
  void sse_encode_list_api_pub_key(
    List<APIPubKey> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_api_pub_key(item, serializer);
    }
  }

  @protected
  void sse_encode_list_api_spend_path(
    List<APISpendPath> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_api_spend_path(item, serializer);
    }
  }

  @protected
  void sse_encode_list_api_spend_path_def(
    List<APISpendPathDef> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_api_spend_path_def(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class SpendPathImpl extends RustOpaque implements SpendPath {
  // Not to be used by end users
  SpendPathImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  SpendPathImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_SpendPath,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_SpendPath,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_SpendPathPtr,
  );
}
