// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/analyzer.dart';
import 'api/hw_wallet.dart';
import 'api/model.dart';
import 'api/tor.dart';
import 'api/wallet.dart';
import 'api/wallet/backup.dart';
import 'api/wallet/descriptor_backup.dart';
import 'api/wallet/descriptor_recovery.dart';
import 'api/wallet/descriptor_sig.dart';
import 'api/wallet/discovery.dart';
import 'api/wallet/nostr_backup.dart';
import 'api/wif_sweep.dart';
import 'core/spend_path.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiWalletPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAPIWalletPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_AnchorKeyPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnchorKeyPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SecretKeyPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecretKeyPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SpendPathPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpendPathPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_XOnlyPublicKeyPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXOnlyPublicKeyPtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  ApiWallet
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAPIWallet(
    dynamic raw,
  );

  @protected
  AnchorKey
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnchorKey(
    dynamic raw,
  );

  @protected
  SecretKey
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecretKey(
    dynamic raw,
  );

  @protected
  SpendPath
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpendPath(
    dynamic raw,
  );

  @protected
  XOnlyPublicKey
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXOnlyPublicKey(
    dynamic raw,
  );

  @protected
  ApiWallet
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAPIWallet(
    dynamic raw,
  );

  @protected
  AnchorKey
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnchorKey(
    dynamic raw,
  );

  @protected
  ApiWallet
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAPIWallet(
    dynamic raw,
  );

  @protected
  AnchorKey
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnchorKey(
    dynamic raw,
  );

  @protected
  SpendPath
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpendPath(
    dynamic raw,
  );

  @protected
  ApiWallet
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAPIWallet(
    dynamic raw,
  );

  @protected
  AnchorKey
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnchorKey(
    dynamic raw,
  );

  @protected
  SecretKey
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecretKey(
    dynamic raw,
  );

  @protected
  SpendPath
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpendPath(
    dynamic raw,
  );

  @protected
  XOnlyPublicKey
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXOnlyPublicKey(
    dynamic raw,
  );

  @protected
  RustStreamSink<bool> dco_decode_StreamSink_bool_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  APIAbsoluteTimelock dco_decode_api_absolute_timelock(dynamic raw);

  @protected
  APIAbsoluteTimelockType dco_decode_api_absolute_timelock_type(dynamic raw);

  @protected
  APIAccountInfo dco_decode_api_account_info(dynamic raw);

  @protected
  APIAddress dco_decode_api_address(dynamic raw);

  @protected
  APIAddressDetails dco_decode_api_address_details(dynamic raw);

  @protected
  APIAnalysisResult dco_decode_api_analysis_result(dynamic raw);

  @protected
  APIBalance dco_decode_api_balance(dynamic raw);

  @protected
  APIBiometricSlot dco_decode_api_biometric_slot(dynamic raw);

  @protected
  APICoinControl dco_decode_api_coin_control(dynamic raw);

  @protected
  APICpfpInfo dco_decode_api_cpfp_info(dynamic raw);

  @protected
  APIDescriptorScanResult dco_decode_api_descriptor_scan_result(dynamic raw);

  @protected
  APIDescriptorSig dco_decode_api_descriptor_sig(dynamic raw);

  @protected
  APIDescriptorSigVerification dco_decode_api_descriptor_sig_verification(
    dynamic raw,
  );

  @protected
  APIDiscoveredAccounts dco_decode_api_discovered_accounts(dynamic raw);

  @protected
  APIFiatPrice dco_decode_api_fiat_price(dynamic raw);

  @protected
  APIHotKeyInfo dco_decode_api_hot_key_info(dynamic raw);

  @protected
  APIHotKeyList dco_decode_api_hot_key_list(dynamic raw);

  @protected
  APIHwConnectResult dco_decode_api_hw_connect_result(dynamic raw);

  @protected
  APIHwDevice dco_decode_api_hw_device(dynamic raw);

  @protected
  APIHwSessionInfo dco_decode_api_hw_session_info(dynamic raw);

  @protected
  APIImportPsbtResult dco_decode_api_import_psbt_result(dynamic raw);

  @protected
  APIKeyLabel dco_decode_api_key_label(dynamic raw);

  @protected
  APIKeychain dco_decode_api_keychain(dynamic raw);

  @protected
  APINetwork dco_decode_api_network(dynamic raw);

  @protected
  APIPathLabel dco_decode_api_path_label(dynamic raw);

  @protected
  APIPolicyPath dco_decode_api_policy_path(dynamic raw);

  @protected
  APIPrepareDescriptorSigPsbt dco_decode_api_prepare_descriptor_sig_psbt(
    dynamic raw,
  );

  @protected
  APIProtectionType dco_decode_api_protection_type(dynamic raw);

  @protected
  APIPsbtAnalysis dco_decode_api_psbt_analysis(dynamic raw);

  @protected
  APIPsbtInfo dco_decode_api_psbt_info(dynamic raw);

  @protected
  APIPsbtSignerStatus dco_decode_api_psbt_signer_status(dynamic raw);

  @protected
  APIPubKey dco_decode_api_pub_key(dynamic raw);

  @protected
  APIRbfInfo dco_decode_api_rbf_info(dynamic raw);

  @protected
  APIRecipient dco_decode_api_recipient(dynamic raw);

  @protected
  APIRelatedAddress dco_decode_api_related_address(dynamic raw);

  @protected
  APIRelatedTx dco_decode_api_related_tx(dynamic raw);

  @protected
  APIRelatedUtxo dco_decode_api_related_utxo(dynamic raw);

  @protected
  APIRelativeTimelock dco_decode_api_relative_timelock(dynamic raw);

  @protected
  APIRelativeTimelockType dco_decode_api_relative_timelock_type(dynamic raw);

  @protected
  APISecurityLevel dco_decode_api_security_level(dynamic raw);

  @protected
  APISpendPath dco_decode_api_spend_path(dynamic raw);

  @protected
  APISpendPathDef dco_decode_api_spend_path_def(dynamic raw);

  @protected
  APITransaction dco_decode_api_transaction(dynamic raw);

  @protected
  APITransactionPage dco_decode_api_transaction_page(dynamic raw);

  @protected
  APITxDetails dco_decode_api_tx_details(dynamic raw);

  @protected
  APITxMissingFiat dco_decode_api_tx_missing_fiat(dynamic raw);

  @protected
  APIUtxo dco_decode_api_utxo(dynamic raw);

  @protected
  APIUtxoDetails dco_decode_api_utxo_details(dynamic raw);

  @protected
  APIWalletInfo dco_decode_api_wallet_info(dynamic raw);

  @protected
  APIWalletProtection dco_decode_api_wallet_protection(dynamic raw);

  @protected
  APIWalletType dco_decode_api_wallet_type(dynamic raw);

  @protected
  APIWalletTypeKeyspecs dco_decode_api_wallet_type_keyspecs(dynamic raw);

  @protected
  APIWalletTypePaths dco_decode_api_wallet_type_paths(dynamic raw);

  @protected
  APIWifAddress dco_decode_api_wif_address(dynamic raw);

  @protected
  APIWifUtxo dco_decode_api_wif_utxo(dynamic raw);

  @protected
  APIXpubSlot dco_decode_api_xpub_slot(dynamic raw);

  @protected
  BackupParams dco_decode_backup_params(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  APIAbsoluteTimelock dco_decode_box_autoadd_api_absolute_timelock(dynamic raw);

  @protected
  APIDescriptorSigVerification
  dco_decode_box_autoadd_api_descriptor_sig_verification(dynamic raw);

  @protected
  APIHwSessionInfo dco_decode_box_autoadd_api_hw_session_info(dynamic raw);

  @protected
  APIRelativeTimelock dco_decode_box_autoadd_api_relative_timelock(dynamic raw);

  @protected
  APIWalletType dco_decode_box_autoadd_api_wallet_type(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  ExistingBackupInfo dco_decode_existing_backup_info(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<SpendPath>
  dco_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpendPath(
    dynamic raw,
  );

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<APIAccountInfo> dco_decode_list_api_account_info(dynamic raw);

  @protected
  List<APIAddress> dco_decode_list_api_address(dynamic raw);

  @protected
  List<APIBiometricSlot> dco_decode_list_api_biometric_slot(dynamic raw);

  @protected
  List<APICoinControl> dco_decode_list_api_coin_control(dynamic raw);

  @protected
  List<APIDescriptorSig> dco_decode_list_api_descriptor_sig(dynamic raw);

  @protected
  List<APIFiatPrice> dco_decode_list_api_fiat_price(dynamic raw);

  @protected
  List<APIHotKeyInfo> dco_decode_list_api_hot_key_info(dynamic raw);

  @protected
  List<APIHwDevice> dco_decode_list_api_hw_device(dynamic raw);

  @protected
  List<APIKeyLabel> dco_decode_list_api_key_label(dynamic raw);

  @protected
  List<APIPathLabel> dco_decode_list_api_path_label(dynamic raw);

  @protected
  List<APIPolicyPath> dco_decode_list_api_policy_path(dynamic raw);

  @protected
  List<APIPsbtInfo> dco_decode_list_api_psbt_info(dynamic raw);

  @protected
  List<APIPsbtSignerStatus> dco_decode_list_api_psbt_signer_status(dynamic raw);

  @protected
  List<APIPubKey> dco_decode_list_api_pub_key(dynamic raw);

  @protected
  List<APIRecipient> dco_decode_list_api_recipient(dynamic raw);

  @protected
  List<APIRelatedAddress> dco_decode_list_api_related_address(dynamic raw);

  @protected
  List<APIRelatedTx> dco_decode_list_api_related_tx(dynamic raw);

  @protected
  List<APIRelatedUtxo> dco_decode_list_api_related_utxo(dynamic raw);

  @protected
  List<APISpendPath> dco_decode_list_api_spend_path(dynamic raw);

  @protected
  List<APISpendPathDef> dco_decode_list_api_spend_path_def(dynamic raw);

  @protected
  List<APITransaction> dco_decode_list_api_transaction(dynamic raw);

  @protected
  List<APITxMissingFiat> dco_decode_list_api_tx_missing_fiat(dynamic raw);

  @protected
  List<APIUtxo> dco_decode_list_api_utxo(dynamic raw);

  @protected
  List<APIWalletInfo> dco_decode_list_api_wallet_info(dynamic raw);

  @protected
  List<APIWalletTypeKeyspecs> dco_decode_list_api_wallet_type_keyspecs(
    dynamic raw,
  );

  @protected
  List<APIWalletTypePaths> dco_decode_list_api_wallet_type_paths(dynamic raw);

  @protected
  List<APIWifAddress> dco_decode_list_api_wif_address(dynamic raw);

  @protected
  List<APIWifUtxo> dco_decode_list_api_wif_utxo(dynamic raw);

  @protected
  List<APIXpubSlot> dco_decode_list_api_xpub_slot(dynamic raw);

  @protected
  List<NostrBackupResponse> dco_decode_list_nostr_backup_response(dynamic raw);

  @protected
  List<NostrRelayStatus> dco_decode_list_nostr_relay_status(dynamic raw);

  @protected
  List<OnchainBackupResponse> dco_decode_list_onchain_backup_response(
    dynamic raw,
  );

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_32_loose(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  NostrBackupResponse dco_decode_nostr_backup_response(dynamic raw);

  @protected
  NostrImportResult dco_decode_nostr_import_result(dynamic raw);

  @protected
  NostrRelayStatus dco_decode_nostr_relay_status(dynamic raw);

  @protected
  OnchainBackupPsbt dco_decode_onchain_backup_psbt(dynamic raw);

  @protected
  OnchainBackupResponse dco_decode_onchain_backup_response(dynamic raw);

  @protected
  OnchainBackupResult dco_decode_onchain_backup_result(dynamic raw);

  @protected
  OnchainImportResult dco_decode_onchain_import_result(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  APIDescriptorSigVerification?
  dco_decode_opt_box_autoadd_api_descriptor_sig_verification(dynamic raw);

  @protected
  APIHwSessionInfo? dco_decode_opt_box_autoadd_api_hw_session_info(dynamic raw);

  @protected
  APIWalletType? dco_decode_opt_box_autoadd_api_wallet_type(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  (double, String) dco_decode_record_f_32_string(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WalletBackupStatus dco_decode_wallet_backup_status(dynamic raw);

  @protected
  WalletImportResult dco_decode_wallet_import_result(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  ApiWallet
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAPIWallet(
    SseDeserializer deserializer,
  );

  @protected
  AnchorKey
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnchorKey(
    SseDeserializer deserializer,
  );

  @protected
  SecretKey
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecretKey(
    SseDeserializer deserializer,
  );

  @protected
  SpendPath
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpendPath(
    SseDeserializer deserializer,
  );

  @protected
  XOnlyPublicKey
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXOnlyPublicKey(
    SseDeserializer deserializer,
  );

  @protected
  ApiWallet
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAPIWallet(
    SseDeserializer deserializer,
  );

  @protected
  AnchorKey
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnchorKey(
    SseDeserializer deserializer,
  );

  @protected
  ApiWallet
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAPIWallet(
    SseDeserializer deserializer,
  );

  @protected
  AnchorKey
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnchorKey(
    SseDeserializer deserializer,
  );

  @protected
  SpendPath
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpendPath(
    SseDeserializer deserializer,
  );

  @protected
  ApiWallet
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAPIWallet(
    SseDeserializer deserializer,
  );

  @protected
  AnchorKey
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnchorKey(
    SseDeserializer deserializer,
  );

  @protected
  SecretKey
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecretKey(
    SseDeserializer deserializer,
  );

  @protected
  SpendPath
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpendPath(
    SseDeserializer deserializer,
  );

  @protected
  XOnlyPublicKey
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXOnlyPublicKey(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<bool> sse_decode_StreamSink_bool_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  APIAbsoluteTimelock sse_decode_api_absolute_timelock(
    SseDeserializer deserializer,
  );

  @protected
  APIAbsoluteTimelockType sse_decode_api_absolute_timelock_type(
    SseDeserializer deserializer,
  );

  @protected
  APIAccountInfo sse_decode_api_account_info(SseDeserializer deserializer);

  @protected
  APIAddress sse_decode_api_address(SseDeserializer deserializer);

  @protected
  APIAddressDetails sse_decode_api_address_details(
    SseDeserializer deserializer,
  );

  @protected
  APIAnalysisResult sse_decode_api_analysis_result(
    SseDeserializer deserializer,
  );

  @protected
  APIBalance sse_decode_api_balance(SseDeserializer deserializer);

  @protected
  APIBiometricSlot sse_decode_api_biometric_slot(SseDeserializer deserializer);

  @protected
  APICoinControl sse_decode_api_coin_control(SseDeserializer deserializer);

  @protected
  APICpfpInfo sse_decode_api_cpfp_info(SseDeserializer deserializer);

  @protected
  APIDescriptorScanResult sse_decode_api_descriptor_scan_result(
    SseDeserializer deserializer,
  );

  @protected
  APIDescriptorSig sse_decode_api_descriptor_sig(SseDeserializer deserializer);

  @protected
  APIDescriptorSigVerification sse_decode_api_descriptor_sig_verification(
    SseDeserializer deserializer,
  );

  @protected
  APIDiscoveredAccounts sse_decode_api_discovered_accounts(
    SseDeserializer deserializer,
  );

  @protected
  APIFiatPrice sse_decode_api_fiat_price(SseDeserializer deserializer);

  @protected
  APIHotKeyInfo sse_decode_api_hot_key_info(SseDeserializer deserializer);

  @protected
  APIHotKeyList sse_decode_api_hot_key_list(SseDeserializer deserializer);

  @protected
  APIHwConnectResult sse_decode_api_hw_connect_result(
    SseDeserializer deserializer,
  );

  @protected
  APIHwDevice sse_decode_api_hw_device(SseDeserializer deserializer);

  @protected
  APIHwSessionInfo sse_decode_api_hw_session_info(SseDeserializer deserializer);

  @protected
  APIImportPsbtResult sse_decode_api_import_psbt_result(
    SseDeserializer deserializer,
  );

  @protected
  APIKeyLabel sse_decode_api_key_label(SseDeserializer deserializer);

  @protected
  APIKeychain sse_decode_api_keychain(SseDeserializer deserializer);

  @protected
  APINetwork sse_decode_api_network(SseDeserializer deserializer);

  @protected
  APIPathLabel sse_decode_api_path_label(SseDeserializer deserializer);

  @protected
  APIPolicyPath sse_decode_api_policy_path(SseDeserializer deserializer);

  @protected
  APIPrepareDescriptorSigPsbt sse_decode_api_prepare_descriptor_sig_psbt(
    SseDeserializer deserializer,
  );

  @protected
  APIProtectionType sse_decode_api_protection_type(
    SseDeserializer deserializer,
  );

  @protected
  APIPsbtAnalysis sse_decode_api_psbt_analysis(SseDeserializer deserializer);

  @protected
  APIPsbtInfo sse_decode_api_psbt_info(SseDeserializer deserializer);

  @protected
  APIPsbtSignerStatus sse_decode_api_psbt_signer_status(
    SseDeserializer deserializer,
  );

  @protected
  APIPubKey sse_decode_api_pub_key(SseDeserializer deserializer);

  @protected
  APIRbfInfo sse_decode_api_rbf_info(SseDeserializer deserializer);

  @protected
  APIRecipient sse_decode_api_recipient(SseDeserializer deserializer);

  @protected
  APIRelatedAddress sse_decode_api_related_address(
    SseDeserializer deserializer,
  );

  @protected
  APIRelatedTx sse_decode_api_related_tx(SseDeserializer deserializer);

  @protected
  APIRelatedUtxo sse_decode_api_related_utxo(SseDeserializer deserializer);

  @protected
  APIRelativeTimelock sse_decode_api_relative_timelock(
    SseDeserializer deserializer,
  );

  @protected
  APIRelativeTimelockType sse_decode_api_relative_timelock_type(
    SseDeserializer deserializer,
  );

  @protected
  APISecurityLevel sse_decode_api_security_level(SseDeserializer deserializer);

  @protected
  APISpendPath sse_decode_api_spend_path(SseDeserializer deserializer);

  @protected
  APISpendPathDef sse_decode_api_spend_path_def(SseDeserializer deserializer);

  @protected
  APITransaction sse_decode_api_transaction(SseDeserializer deserializer);

  @protected
  APITransactionPage sse_decode_api_transaction_page(
    SseDeserializer deserializer,
  );

  @protected
  APITxDetails sse_decode_api_tx_details(SseDeserializer deserializer);

  @protected
  APITxMissingFiat sse_decode_api_tx_missing_fiat(SseDeserializer deserializer);

  @protected
  APIUtxo sse_decode_api_utxo(SseDeserializer deserializer);

  @protected
  APIUtxoDetails sse_decode_api_utxo_details(SseDeserializer deserializer);

  @protected
  APIWalletInfo sse_decode_api_wallet_info(SseDeserializer deserializer);

  @protected
  APIWalletProtection sse_decode_api_wallet_protection(
    SseDeserializer deserializer,
  );

  @protected
  APIWalletType sse_decode_api_wallet_type(SseDeserializer deserializer);

  @protected
  APIWalletTypeKeyspecs sse_decode_api_wallet_type_keyspecs(
    SseDeserializer deserializer,
  );

  @protected
  APIWalletTypePaths sse_decode_api_wallet_type_paths(
    SseDeserializer deserializer,
  );

  @protected
  APIWifAddress sse_decode_api_wif_address(SseDeserializer deserializer);

  @protected
  APIWifUtxo sse_decode_api_wif_utxo(SseDeserializer deserializer);

  @protected
  APIXpubSlot sse_decode_api_xpub_slot(SseDeserializer deserializer);

  @protected
  BackupParams sse_decode_backup_params(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  APIAbsoluteTimelock sse_decode_box_autoadd_api_absolute_timelock(
    SseDeserializer deserializer,
  );

  @protected
  APIDescriptorSigVerification
  sse_decode_box_autoadd_api_descriptor_sig_verification(
    SseDeserializer deserializer,
  );

  @protected
  APIHwSessionInfo sse_decode_box_autoadd_api_hw_session_info(
    SseDeserializer deserializer,
  );

  @protected
  APIRelativeTimelock sse_decode_box_autoadd_api_relative_timelock(
    SseDeserializer deserializer,
  );

  @protected
  APIWalletType sse_decode_box_autoadd_api_wallet_type(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  ExistingBackupInfo sse_decode_existing_backup_info(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<SpendPath>
  sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpendPath(
    SseDeserializer deserializer,
  );

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<APIAccountInfo> sse_decode_list_api_account_info(
    SseDeserializer deserializer,
  );

  @protected
  List<APIAddress> sse_decode_list_api_address(SseDeserializer deserializer);

  @protected
  List<APIBiometricSlot> sse_decode_list_api_biometric_slot(
    SseDeserializer deserializer,
  );

  @protected
  List<APICoinControl> sse_decode_list_api_coin_control(
    SseDeserializer deserializer,
  );

  @protected
  List<APIDescriptorSig> sse_decode_list_api_descriptor_sig(
    SseDeserializer deserializer,
  );

  @protected
  List<APIFiatPrice> sse_decode_list_api_fiat_price(
    SseDeserializer deserializer,
  );

  @protected
  List<APIHotKeyInfo> sse_decode_list_api_hot_key_info(
    SseDeserializer deserializer,
  );

  @protected
  List<APIHwDevice> sse_decode_list_api_hw_device(SseDeserializer deserializer);

  @protected
  List<APIKeyLabel> sse_decode_list_api_key_label(SseDeserializer deserializer);

  @protected
  List<APIPathLabel> sse_decode_list_api_path_label(
    SseDeserializer deserializer,
  );

  @protected
  List<APIPolicyPath> sse_decode_list_api_policy_path(
    SseDeserializer deserializer,
  );

  @protected
  List<APIPsbtInfo> sse_decode_list_api_psbt_info(SseDeserializer deserializer);

  @protected
  List<APIPsbtSignerStatus> sse_decode_list_api_psbt_signer_status(
    SseDeserializer deserializer,
  );

  @protected
  List<APIPubKey> sse_decode_list_api_pub_key(SseDeserializer deserializer);

  @protected
  List<APIRecipient> sse_decode_list_api_recipient(
    SseDeserializer deserializer,
  );

  @protected
  List<APIRelatedAddress> sse_decode_list_api_related_address(
    SseDeserializer deserializer,
  );

  @protected
  List<APIRelatedTx> sse_decode_list_api_related_tx(
    SseDeserializer deserializer,
  );

  @protected
  List<APIRelatedUtxo> sse_decode_list_api_related_utxo(
    SseDeserializer deserializer,
  );

  @protected
  List<APISpendPath> sse_decode_list_api_spend_path(
    SseDeserializer deserializer,
  );

  @protected
  List<APISpendPathDef> sse_decode_list_api_spend_path_def(
    SseDeserializer deserializer,
  );

  @protected
  List<APITransaction> sse_decode_list_api_transaction(
    SseDeserializer deserializer,
  );

  @protected
  List<APITxMissingFiat> sse_decode_list_api_tx_missing_fiat(
    SseDeserializer deserializer,
  );

  @protected
  List<APIUtxo> sse_decode_list_api_utxo(SseDeserializer deserializer);

  @protected
  List<APIWalletInfo> sse_decode_list_api_wallet_info(
    SseDeserializer deserializer,
  );

  @protected
  List<APIWalletTypeKeyspecs> sse_decode_list_api_wallet_type_keyspecs(
    SseDeserializer deserializer,
  );

  @protected
  List<APIWalletTypePaths> sse_decode_list_api_wallet_type_paths(
    SseDeserializer deserializer,
  );

  @protected
  List<APIWifAddress> sse_decode_list_api_wif_address(
    SseDeserializer deserializer,
  );

  @protected
  List<APIWifUtxo> sse_decode_list_api_wif_utxo(SseDeserializer deserializer);

  @protected
  List<APIXpubSlot> sse_decode_list_api_xpub_slot(SseDeserializer deserializer);

  @protected
  List<NostrBackupResponse> sse_decode_list_nostr_backup_response(
    SseDeserializer deserializer,
  );

  @protected
  List<NostrRelayStatus> sse_decode_list_nostr_relay_status(
    SseDeserializer deserializer,
  );

  @protected
  List<OnchainBackupResponse> sse_decode_list_onchain_backup_response(
    SseDeserializer deserializer,
  );

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_32_loose(SseDeserializer deserializer);

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  NostrBackupResponse sse_decode_nostr_backup_response(
    SseDeserializer deserializer,
  );

  @protected
  NostrImportResult sse_decode_nostr_import_result(
    SseDeserializer deserializer,
  );

  @protected
  NostrRelayStatus sse_decode_nostr_relay_status(SseDeserializer deserializer);

  @protected
  OnchainBackupPsbt sse_decode_onchain_backup_psbt(
    SseDeserializer deserializer,
  );

  @protected
  OnchainBackupResponse sse_decode_onchain_backup_response(
    SseDeserializer deserializer,
  );

  @protected
  OnchainBackupResult sse_decode_onchain_backup_result(
    SseDeserializer deserializer,
  );

  @protected
  OnchainImportResult sse_decode_onchain_import_result(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  APIDescriptorSigVerification?
  sse_decode_opt_box_autoadd_api_descriptor_sig_verification(
    SseDeserializer deserializer,
  );

  @protected
  APIHwSessionInfo? sse_decode_opt_box_autoadd_api_hw_session_info(
    SseDeserializer deserializer,
  );

  @protected
  APIWalletType? sse_decode_opt_box_autoadd_api_wallet_type(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  (double, String) sse_decode_record_f_32_string(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WalletBackupStatus sse_decode_wallet_backup_status(
    SseDeserializer deserializer,
  );

  @protected
  WalletImportResult sse_decode_wallet_import_result(
    SseDeserializer deserializer,
  );

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAPIWallet(
    ApiWallet self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnchorKey(
    AnchorKey self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecretKey(
    SecretKey self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpendPath(
    SpendPath self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXOnlyPublicKey(
    XOnlyPublicKey self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAPIWallet(
    ApiWallet self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnchorKey(
    AnchorKey self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAPIWallet(
    ApiWallet self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnchorKey(
    AnchorKey self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpendPath(
    SpendPath self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAPIWallet(
    ApiWallet self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnchorKey(
    AnchorKey self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecretKey(
    SecretKey self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpendPath(
    SpendPath self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXOnlyPublicKey(
    XOnlyPublicKey self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_bool_Sse(
    RustStreamSink<bool> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_api_absolute_timelock(
    APIAbsoluteTimelock self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_absolute_timelock_type(
    APIAbsoluteTimelockType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_account_info(
    APIAccountInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_address(APIAddress self, SseSerializer serializer);

  @protected
  void sse_encode_api_address_details(
    APIAddressDetails self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_analysis_result(
    APIAnalysisResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_balance(APIBalance self, SseSerializer serializer);

  @protected
  void sse_encode_api_biometric_slot(
    APIBiometricSlot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_coin_control(
    APICoinControl self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_cpfp_info(APICpfpInfo self, SseSerializer serializer);

  @protected
  void sse_encode_api_descriptor_scan_result(
    APIDescriptorScanResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_descriptor_sig(
    APIDescriptorSig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_descriptor_sig_verification(
    APIDescriptorSigVerification self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_discovered_accounts(
    APIDiscoveredAccounts self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_fiat_price(APIFiatPrice self, SseSerializer serializer);

  @protected
  void sse_encode_api_hot_key_info(
    APIHotKeyInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_hot_key_list(
    APIHotKeyList self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_hw_connect_result(
    APIHwConnectResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_hw_device(APIHwDevice self, SseSerializer serializer);

  @protected
  void sse_encode_api_hw_session_info(
    APIHwSessionInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_import_psbt_result(
    APIImportPsbtResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_key_label(APIKeyLabel self, SseSerializer serializer);

  @protected
  void sse_encode_api_keychain(APIKeychain self, SseSerializer serializer);

  @protected
  void sse_encode_api_network(APINetwork self, SseSerializer serializer);

  @protected
  void sse_encode_api_path_label(APIPathLabel self, SseSerializer serializer);

  @protected
  void sse_encode_api_policy_path(APIPolicyPath self, SseSerializer serializer);

  @protected
  void sse_encode_api_prepare_descriptor_sig_psbt(
    APIPrepareDescriptorSigPsbt self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_protection_type(
    APIProtectionType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_psbt_analysis(
    APIPsbtAnalysis self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_psbt_info(APIPsbtInfo self, SseSerializer serializer);

  @protected
  void sse_encode_api_psbt_signer_status(
    APIPsbtSignerStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_pub_key(APIPubKey self, SseSerializer serializer);

  @protected
  void sse_encode_api_rbf_info(APIRbfInfo self, SseSerializer serializer);

  @protected
  void sse_encode_api_recipient(APIRecipient self, SseSerializer serializer);

  @protected
  void sse_encode_api_related_address(
    APIRelatedAddress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_related_tx(APIRelatedTx self, SseSerializer serializer);

  @protected
  void sse_encode_api_related_utxo(
    APIRelatedUtxo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_relative_timelock(
    APIRelativeTimelock self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_relative_timelock_type(
    APIRelativeTimelockType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_security_level(
    APISecurityLevel self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_spend_path(APISpendPath self, SseSerializer serializer);

  @protected
  void sse_encode_api_spend_path_def(
    APISpendPathDef self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_transaction(
    APITransaction self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_transaction_page(
    APITransactionPage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_tx_details(APITxDetails self, SseSerializer serializer);

  @protected
  void sse_encode_api_tx_missing_fiat(
    APITxMissingFiat self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_utxo(APIUtxo self, SseSerializer serializer);

  @protected
  void sse_encode_api_utxo_details(
    APIUtxoDetails self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_wallet_info(APIWalletInfo self, SseSerializer serializer);

  @protected
  void sse_encode_api_wallet_protection(
    APIWalletProtection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_wallet_type(APIWalletType self, SseSerializer serializer);

  @protected
  void sse_encode_api_wallet_type_keyspecs(
    APIWalletTypeKeyspecs self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_wallet_type_paths(
    APIWalletTypePaths self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_wif_address(APIWifAddress self, SseSerializer serializer);

  @protected
  void sse_encode_api_wif_utxo(APIWifUtxo self, SseSerializer serializer);

  @protected
  void sse_encode_api_xpub_slot(APIXpubSlot self, SseSerializer serializer);

  @protected
  void sse_encode_backup_params(BackupParams self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_api_absolute_timelock(
    APIAbsoluteTimelock self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_api_descriptor_sig_verification(
    APIDescriptorSigVerification self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_api_hw_session_info(
    APIHwSessionInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_api_relative_timelock(
    APIRelativeTimelock self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_api_wallet_type(
    APIWalletType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_existing_backup_info(
    ExistingBackupInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void
  sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpendPath(
    List<SpendPath> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_api_account_info(
    List<APIAccountInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_address(
    List<APIAddress> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_biometric_slot(
    List<APIBiometricSlot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_coin_control(
    List<APICoinControl> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_descriptor_sig(
    List<APIDescriptorSig> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_fiat_price(
    List<APIFiatPrice> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_hot_key_info(
    List<APIHotKeyInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_hw_device(
    List<APIHwDevice> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_key_label(
    List<APIKeyLabel> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_path_label(
    List<APIPathLabel> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_policy_path(
    List<APIPolicyPath> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_psbt_info(
    List<APIPsbtInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_psbt_signer_status(
    List<APIPsbtSignerStatus> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_pub_key(
    List<APIPubKey> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_recipient(
    List<APIRecipient> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_related_address(
    List<APIRelatedAddress> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_related_tx(
    List<APIRelatedTx> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_related_utxo(
    List<APIRelatedUtxo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_spend_path(
    List<APISpendPath> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_spend_path_def(
    List<APISpendPathDef> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_transaction(
    List<APITransaction> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_tx_missing_fiat(
    List<APITxMissingFiat> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_utxo(List<APIUtxo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_api_wallet_info(
    List<APIWalletInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_wallet_type_keyspecs(
    List<APIWalletTypeKeyspecs> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_wallet_type_paths(
    List<APIWalletTypePaths> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_wif_address(
    List<APIWifAddress> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_wif_utxo(
    List<APIWifUtxo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_xpub_slot(
    List<APIXpubSlot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_nostr_backup_response(
    List<NostrBackupResponse> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_nostr_relay_status(
    List<NostrRelayStatus> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_onchain_backup_response(
    List<OnchainBackupResponse> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_64_strict(
    Int64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_loose(
    List<int> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_nostr_backup_response(
    NostrBackupResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_nostr_import_result(
    NostrImportResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_nostr_relay_status(
    NostrRelayStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_onchain_backup_psbt(
    OnchainBackupPsbt self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_onchain_backup_response(
    OnchainBackupResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_onchain_backup_result(
    OnchainBackupResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_onchain_import_result(
    OnchainImportResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_api_descriptor_sig_verification(
    APIDescriptorSigVerification? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_api_hw_session_info(
    APIHwSessionInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_api_wallet_type(
    APIWalletType? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_f_32_string(
    (double, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_wallet_backup_status(
    WalletBackupStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_wallet_import_result(
    WalletImportResult self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAPIWallet(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAPIWallet(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAPIWalletPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_deadbolt_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAPIWallet',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAPIWallet =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAPIWalletPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAPIWallet(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAPIWallet(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAPIWalletPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_deadbolt_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAPIWallet',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAPIWallet =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAPIWalletPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnchorKey(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnchorKey(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnchorKeyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_deadbolt_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnchorKey',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnchorKey =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnchorKeyPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnchorKey(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnchorKey(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnchorKeyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_deadbolt_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnchorKey',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnchorKey =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerAnchorKeyPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecretKey(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecretKey(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecretKeyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_deadbolt_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecretKey',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecretKey =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecretKeyPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecretKey(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecretKey(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecretKeyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_deadbolt_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecretKey',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecretKey =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSecretKeyPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpendPath(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpendPath(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpendPathPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_deadbolt_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpendPath',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpendPath =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpendPathPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpendPath(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpendPath(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpendPathPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_deadbolt_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpendPath',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpendPath =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpendPathPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXOnlyPublicKey(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXOnlyPublicKey(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXOnlyPublicKeyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_deadbolt_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXOnlyPublicKey',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXOnlyPublicKey =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXOnlyPublicKeyPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXOnlyPublicKey(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXOnlyPublicKey(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXOnlyPublicKeyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_deadbolt_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXOnlyPublicKey',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXOnlyPublicKey =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerXOnlyPublicKeyPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
