// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../model.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Export a wallet to a self-contained encrypted `.deadbolt` backup (v2 format).
///
/// `export_protection` must be `UserPassword` or `XpubKey`.
/// - `UserPassword`: provide `export_password`; the credential is protected with Argon2id.
/// - `XpubKey`: xpubs are auto-extracted from the descriptor; each gets its own slot.
///
/// `security_level` controls the Argon2id parameters for the export credential slots.
/// The returned bytes should be saved as a `.deadbolt` file.
Future<Uint8List> exportWalletBackup({
  required String walletPath,
  required String deviceKeyHex,
  String? openPassword,
  required APIProtectionType exportProtection,
  String? exportPassword,
  required APISecurityLevel securityLevel,
}) => RustLib.instance.api.crateApiWalletBackupExportWalletBackup(
  walletPath: walletPath,
  deviceKeyHex: deviceKeyHex,
  openPassword: openPassword,
  exportProtection: exportProtection,
  exportPassword: exportPassword,
  securityLevel: securityLevel,
);

/// Import a `.deadbolt` backup (v1 or v2) and add it as a new wallet in `wallets_dir`.
///
/// `import_credential`: password for UserPassword backups, xpub or keyspec for XpubKey backups.
/// Returns the restored wallet info together with signature verification status.
Future<WalletImportResult> importWalletBackup({
  required List<int> backupBytes,
  required String importCredential,
  required String deviceKeyHex,
  required String walletsDir,
}) => RustLib.instance.api.crateApiWalletBackupImportWalletBackup(
  backupBytes: backupBytes,
  importCredential: importCredential,
  deviceKeyHex: deviceKeyHex,
  walletsDir: walletsDir,
);

/// Inspect a `.deadbolt` backup and return its protection type without decrypting it.
Future<APIProtectionType> inspectWalletBackup({
  required List<int> backupBytes,
}) => RustLib.instance.api.crateApiWalletBackupInspectWalletBackup(
  backupBytes: backupBytes,
);

/// Return type of `import_wallet_backup` — carries the restored wallet info.
class WalletImportResult {
  final APIWalletInfo wallet;

  const WalletImportResult({required this.wallet});

  @override
  int get hashCode => wallet.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletImportResult &&
          runtimeType == other.runtimeType &&
          wallet == other.wallet;
}
