// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../model.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Export the wallet's descriptor to a BED file.
///
/// Returns the raw binary payload. Use [`encode_bed_armor`] to obtain the
/// ASCII-armored text variant of the same bytes.
BEDExportResult exportBedBackup({
  required String walletPath,
  required String deviceKeyHex,
  String? password,
}) => RustLib.instance.api.crateApiWalletBedBackupExportBedBackup(
  walletPath: walletPath,
  deviceKeyHex: deviceKeyHex,
  password: password,
);

/// Encode raw BED bytes as PEM-style ASCII armor (pure post-processing, no
/// crypto). Mirrors [`decode_armored`] on the way back in.
String encodeBedArmor({required List<int> backupBytes}) => RustLib.instance.api
    .crateApiWalletBedBackupEncodeBedArmor(backupBytes: backupBytes);

/// Import a wallet from a BED file.
///
/// `backup_bytes` may be the raw binary payload or ASCII-armored text
/// (auto-detected). `xpub_credential` is any one of the descriptor's xpubs,
/// with or without the `[fingerprint/path]` origin prefix — only the xpub's
/// own public key is used, so no private key material is required.
///
/// Signature intentionally mirrors `import_onchain_backup` /
/// `import_nostr_backup` so it can be used as a drop-in `rustImport`
/// callback on the Dart side.
Future<BEDImportResult> importBedBackup({
  required List<int> backupBytes,
  required String xpubCredential,
  required String deviceKeyHex,
  required String walletsDir,
  required String networkHint,
}) => RustLib.instance.api.crateApiWalletBedBackupImportBedBackup(
  backupBytes: backupBytes,
  xpubCredential: xpubCredential,
  deviceKeyHex: deviceKeyHex,
  walletsDir: walletsDir,
  networkHint: networkHint,
);

/// Detect the format of raw bytes — `"binary"`, `"armored"`, or `"unknown"`.
String sniffBedFormat({required List<int> backupBytes}) => RustLib.instance.api
    .crateApiWalletBedBackupSniffBedFormat(backupBytes: backupBytes);
