// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../model.dart';
import 'nostr_backup.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `anchor_spk_for_xpub`, `collect_commits`, `compute_anchor_health`, `descriptor_meta`, `get_block_timestamp`, `parse_bare_xpub`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DescriptorMeta`

/// Scan on-chain for all descriptor backups published by the given xpub.
Future<List<OnchainBackupResponse>> fetchOnchainBackup({
  required String xpubCredential,
  required String electrumUrl,
  required String networkHint,
}) => RustLib.instance.api.crateApiWalletDescriptorRecoveryFetchOnchainBackup(
  xpubCredential: xpubCredential,
  electrumUrl: electrumUrl,
  networkHint: networkHint,
);

/// Import an on-chain backup payload (from `fetch_onchain_backup.bytes`) as a new wallet.
Future<OnchainImportResult> importOnchainBackup({
  required List<int> backupBytes,
  required String xpubCredential,
  required String deviceKeyHex,
  required String walletsDir,
  required String networkHint,
}) => RustLib.instance.api.crateApiWalletDescriptorRecoveryImportOnchainBackup(
  backupBytes: backupBytes,
  xpubCredential: xpubCredential,
  deviceKeyHex: deviceKeyHex,
  walletsDir: walletsDir,
  networkHint: networkHint,
);

/// A single on-chain descriptor backup found for a given xpub.
class OnchainBackupResponse {
  final String commitTxid;
  final String? revealTxid;

  /// Raw on-chain backup payload bytes (use with `import_onchain_backup`).
  final Uint8List bytes;
  final String? walletName;
  final String? network;
  final PlatformInt64? createdAt;
  final String? firstAddress;
  final APIWalletType? walletType;

  /// The decrypted descriptor string (present when decryption succeeded).
  final String? descriptor;
  final APIDescriptorSigVerification? descriptorSigVerification;

  /// How many anchor addresses derived from the descriptor have TX_COMMIT in their history.
  final int anchorsReachable;

  /// Total number of anchor addresses derived from the descriptor.
  final int anchorsTotal;

  const OnchainBackupResponse({
    required this.commitTxid,
    this.revealTxid,
    required this.bytes,
    this.walletName,
    this.network,
    this.createdAt,
    this.firstAddress,
    this.walletType,
    this.descriptor,
    this.descriptorSigVerification,
    required this.anchorsReachable,
    required this.anchorsTotal,
  });

  @override
  int get hashCode =>
      commitTxid.hashCode ^
      revealTxid.hashCode ^
      bytes.hashCode ^
      walletName.hashCode ^
      network.hashCode ^
      createdAt.hashCode ^
      firstAddress.hashCode ^
      walletType.hashCode ^
      descriptor.hashCode ^
      descriptorSigVerification.hashCode ^
      anchorsReachable.hashCode ^
      anchorsTotal.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OnchainBackupResponse &&
          runtimeType == other.runtimeType &&
          commitTxid == other.commitTxid &&
          revealTxid == other.revealTxid &&
          bytes == other.bytes &&
          walletName == other.walletName &&
          network == other.network &&
          createdAt == other.createdAt &&
          firstAddress == other.firstAddress &&
          walletType == other.walletType &&
          descriptor == other.descriptor &&
          descriptorSigVerification == other.descriptorSigVerification &&
          anchorsReachable == other.anchorsReachable &&
          anchorsTotal == other.anchorsTotal;
}

/// Return type of `import_onchain_backup`.
class OnchainImportResult {
  final APIWalletInfo wallet;

  const OnchainImportResult({required this.wallet});

  @override
  int get hashCode => wallet.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OnchainImportResult &&
          runtimeType == other.runtimeType &&
          wallet == other.wallet;
}
