// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `signing_message_for_wallet`, `verify_one_sig`, `xpub_entry_for_mfp`

/// Output of `prepare_descriptor_sig_psbt`.
class APIPrepareDescriptorSigPsbt {
  /// PSBT base64 to pass to `hw_sign_psbt`.
  final String psbtB64;

  /// Temporary descriptor (`wsh(pk(…/<0;1>/*))`) to register on the device.
  final String signDescriptor;

  /// The full xpub_entry for the MFP (needed for `complete_descriptor_sig_from_psbt`).
  final String xpubEntry;

  /// The message that was signed (for display / QR show).
  final String message;

  const APIPrepareDescriptorSigPsbt({
    required this.psbtB64,
    required this.signDescriptor,
    required this.xpubEntry,
    required this.message,
  });

  @override
  int get hashCode =>
      psbtB64.hashCode ^
      signDescriptor.hashCode ^
      xpubEntry.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIPrepareDescriptorSigPsbt &&
          runtimeType == other.runtimeType &&
          psbtB64 == other.psbtB64 &&
          signDescriptor == other.signDescriptor &&
          xpubEntry == other.xpubEntry &&
          message == other.message;
}
