// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `anchor_p2tr_address`, `build_encrypted_payload`, `build_reveal`, `commit_weight`, `decrypt_onchain_backup`, `derive_anchor_key`, `extract_descriptor_from_reveal`, `extract_raw_from_tapscript`, `find_reveal_tx_for_commit`, `find_reveal_tx`, `participant_triples`, `reveal_weight`, `sign_reveal`, `split_package_fees`, `vault_taproot`, `vault_tapscript`, `zstd_compress`

/// Minimum total UTXO sats required to perform the backup at the given fee rate.
///
/// Uses the same weight model as `prepare_backup_psbt` (keypath witness per input).
/// `commit_weight` already includes the change output in its size estimate, so the
/// fee covers that weight regardless of whether a change output is actually created.
/// Any surplus above this minimum goes to a change output when ≥ 330 sats (P2TR dust),
/// or is absorbed into the commit fee when below dust.
///
/// Flutter should call this instead of estimating weights locally.
BigInt computeMinUtxoSats({
  required BigInt commitVbytes,
  required BigInt revealVbytes,
  required int nAnchors,
  required double feeRateSatPerVb,
  required double minFeeRate,
}) => RustLib.instance.api.crateApiWalletDescriptorBackupComputeMinUtxoSats(
  commitVbytes: commitVbytes,
  revealVbytes: revealVbytes,
  nAnchors: nAnchors,
  feeRateSatPerVb: feeRateSatPerVb,
  minFeeRate: minFeeRate,
);

/// Check if an on-chain backup exists for the given xpub credential.
Future<ExistingBackupInfo> checkExistingBackup({
  required String xpubCredential,
  required String electrumUrl,
  required String networkHint,
}) => RustLib.instance.api.crateApiWalletDescriptorBackupCheckExistingBackup(
  xpubCredential: xpubCredential,
  electrumUrl: electrumUrl,
  networkHint: networkHint,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AnchorKey>>
abstract class AnchorKey implements RustOpaqueInterface {
  SecretKey get privkey;

  XOnlyPublicKey get xonly;

  set privkey(SecretKey privkey);

  set xonly(XOnlyPublicKey xonly);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SecretKey>>
abstract class SecretKey implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<XOnlyPublicKey>>
abstract class XOnlyPublicKey implements RustOpaqueInterface {}

/// Pre-computed backup parameters returned to Flutter immediately (no network).
///
/// Flutter uses `commit_vbytes` + `reveal_vbytes` to compute live fee breakdowns.
/// For N selected UTXOs: total_commit_vbytes = commit_vbytes + (N-1) * ceil(path.wuIn / 4).
class BackupParams {
  /// Commit TX weight in vbytes assuming one input (baseline).
  final BigInt commitVbytes;
  final BigInt revealVbytes;
  final int participantCount;
  final String vaultAddress;
  final String vaultTapscriptHex;
  final List<String> anchorAddresses;

  /// Minimum UTXO value in sats at the base fee rate (0.1 sat/vB).
  /// Flutter should scale this dynamically: min = base_min + commit_vbytes * (fee_rate - 0.1).
  final BigInt minUtxoSatsBase;

  const BackupParams({
    required this.commitVbytes,
    required this.revealVbytes,
    required this.participantCount,
    required this.vaultAddress,
    required this.vaultTapscriptHex,
    required this.anchorAddresses,
    required this.minUtxoSatsBase,
  });

  @override
  int get hashCode =>
      commitVbytes.hashCode ^
      revealVbytes.hashCode ^
      participantCount.hashCode ^
      vaultAddress.hashCode ^
      vaultTapscriptHex.hashCode ^
      anchorAddresses.hashCode ^
      minUtxoSatsBase.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackupParams &&
          runtimeType == other.runtimeType &&
          commitVbytes == other.commitVbytes &&
          revealVbytes == other.revealVbytes &&
          participantCount == other.participantCount &&
          vaultAddress == other.vaultAddress &&
          vaultTapscriptHex == other.vaultTapscriptHex &&
          anchorAddresses == other.anchorAddresses &&
          minUtxoSatsBase == other.minUtxoSatsBase;
}

/// Whether a previous on-chain backup exists for an xpub.
class ExistingBackupInfo {
  final bool found;
  final String? commitTxid;
  final String? revealTxid;

  const ExistingBackupInfo({
    required this.found,
    this.commitTxid,
    this.revealTxid,
  });

  @override
  int get hashCode =>
      found.hashCode ^ commitTxid.hashCode ^ revealTxid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExistingBackupInfo &&
          runtimeType == other.runtimeType &&
          found == other.found &&
          commitTxid == other.commitTxid &&
          revealTxid == other.revealTxid;
}

/// Unsigned TX_COMMIT PSBT with fee breakdown. Returned by `prepare_onchain_backup_psbt`.
///
/// Pass `commit_psbt_base64` to the signer and both fields verbatim to
/// `finalize_onchain_backup` once signing is complete.
class OnchainBackupPsbt {
  final String commitPsbtBase64;
  final String vaultTapscriptHex;
  final BigInt commitFeeSat;
  final BigInt revealFeeSat;
  final BigInt vaultSats;
  final BigInt anchorCostSat;
  final int anchorCount;
  final BigInt changeSat;
  final BigInt revealChangeSat;
  final BigInt packageVbytes;

  const OnchainBackupPsbt({
    required this.commitPsbtBase64,
    required this.vaultTapscriptHex,
    required this.commitFeeSat,
    required this.revealFeeSat,
    required this.vaultSats,
    required this.anchorCostSat,
    required this.anchorCount,
    required this.changeSat,
    required this.revealChangeSat,
    required this.packageVbytes,
  });

  @override
  int get hashCode =>
      commitPsbtBase64.hashCode ^
      vaultTapscriptHex.hashCode ^
      commitFeeSat.hashCode ^
      revealFeeSat.hashCode ^
      vaultSats.hashCode ^
      anchorCostSat.hashCode ^
      anchorCount.hashCode ^
      changeSat.hashCode ^
      revealChangeSat.hashCode ^
      packageVbytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OnchainBackupPsbt &&
          runtimeType == other.runtimeType &&
          commitPsbtBase64 == other.commitPsbtBase64 &&
          vaultTapscriptHex == other.vaultTapscriptHex &&
          commitFeeSat == other.commitFeeSat &&
          revealFeeSat == other.revealFeeSat &&
          vaultSats == other.vaultSats &&
          anchorCostSat == other.anchorCostSat &&
          anchorCount == other.anchorCount &&
          changeSat == other.changeSat &&
          revealChangeSat == other.revealChangeSat &&
          packageVbytes == other.packageVbytes;
}

/// Txids produced by a successful commit-reveal backup.
class OnchainBackupResult {
  final String commitTxid;
  final String revealTxid;

  const OnchainBackupResult({
    required this.commitTxid,
    required this.revealTxid,
  });

  @override
  int get hashCode => commitTxid.hashCode ^ revealTxid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OnchainBackupResult &&
          runtimeType == other.runtimeType &&
          commitTxid == other.commitTxid &&
          revealTxid == other.revealTxid;
}

/// Health status of an existing on-chain backup for this wallet.
class WalletBackupStatus {
  final bool found;
  final String? commitTxid;
  final String? revealTxid;

  /// How many anchor addresses have the commit TX in their Electrum history.
  final int anchorsReachable;
  final int anchorsTotal;

  /// True when TX_REVEAL was found and its decrypted descriptor matches this wallet.
  final bool descriptorVerified;

  const WalletBackupStatus({
    required this.found,
    this.commitTxid,
    this.revealTxid,
    required this.anchorsReachable,
    required this.anchorsTotal,
    required this.descriptorVerified,
  });

  @override
  int get hashCode =>
      found.hashCode ^
      commitTxid.hashCode ^
      revealTxid.hashCode ^
      anchorsReachable.hashCode ^
      anchorsTotal.hashCode ^
      descriptorVerified.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletBackupStatus &&
          runtimeType == other.runtimeType &&
          found == other.found &&
          commitTxid == other.commitTxid &&
          revealTxid == other.revealTxid &&
          anchorsReachable == other.anchorsReachable &&
          anchorsTotal == other.anchorsTotal &&
          descriptorVerified == other.descriptorVerified;
}
