// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../model.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Scan a mnemonic's BIP44-family accounts and return those with on-chain activity.
///
/// Iterates accounts starting at index 0. Stops after `account_gap_limit`
/// consecutive accounts with no transactions and no balance. For each
/// account it checks the first `address_gap_limit` receive addresses (chain 0)
/// using Electrum batch queries.
///
/// Only singlesig wallet types are supported. Passing `P2WSH` or `P2SH_WSH`
/// returns an error.
Future<APIDiscoveredAccounts> discoverAccounts({
  required String mnemonic,
  String? passphrase,
  required APIWalletType walletType,
  required APINetwork network,
  required String electrumUrl,
  required int accountGapLimit,
  required int addressGapLimit,
  required bool nonStandardPaths,
}) => RustLib.instance.api.crateApiWalletDiscoveryDiscoverAccounts(
  mnemonic: mnemonic,
  passphrase: passphrase,
  walletType: walletType,
  network: network,
  electrumUrl: electrumUrl,
  accountGapLimit: accountGapLimit,
  addressGapLimit: addressGapLimit,
  nonStandardPaths: nonStandardPaths,
);

/// Derives account-level xpubs for all standard derivation paths without any
/// on-chain queries.  Used to search Nostr for descriptor backups independently
/// of whether any funds are present.
///
/// Covers:
/// - BIP44-style single-sig (depth 3): purposes 44 / 49 / 84 / 86 × 0..account_count
/// - BIP48 multisig (depth 4): purpose 48 × 0..account_count × script_types 1 / 2 / 3 / 4 / 9
///   (script_type 1 = P2SH-P2WSH, 2 = P2WSH native, 3 = P2TR / Tapscript,
///   4 = P2WSH-P2SH nested, 9 = Miniscript / Liana)
Future<List<String>> deriveXpubsForNostr({
  required String mnemonic,
  String? passphrase,
  required APINetwork network,
  required int accountCount,
}) => RustLib.instance.api.crateApiWalletDiscoveryDeriveXpubsForNostr(
  mnemonic: mnemonic,
  passphrase: passphrase,
  network: network,
  accountCount: accountCount,
);

/// Returns the first external receive address (index 0) for a stored wallet
/// descriptor. Used to match discovered accounts against wallets already on
/// the device without relying on fragile descriptor string comparisons.
Future<String> firstAddressFromDescriptor({
  required String descriptor,
  required APINetwork network,
}) => RustLib.instance.api.crateApiWalletDiscoveryFirstAddressFromDescriptor(
  descriptor: descriptor,
  network: network,
);

/// Returns the wallet type derived from a descriptor.
/// This parses the descriptor to determine if it's P2PKH, P2WPKH, P2SH, P2WSH, or P2TR.
Future<APIWalletType> walletTypeFromDescriptor({required String descriptor}) =>
    RustLib.instance.api.crateApiWalletDiscoveryWalletTypeFromDescriptor(
      descriptor: descriptor,
    );
