// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../model.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_nostr_event`, `build_payload_for_xpub`, `derive_nostr_keypair`, `descriptor_d_tag`, `ws_check_descriptor_backup`, `ws_fetch_payloads_for_xpub`, `ws_open`, `ws_publish_event`

/// Publish an encrypted descriptor backup for every xpub in the wallet to all
/// configured Nostr relays. One event is published per xpub (each encrypted
/// for that xpub only), so any co-signer can independently locate and decrypt
/// their own backup using only their xpub.
///
/// Returns one `NostrRelayStatus` per relay URL. `has_backup = true` means
/// at least one xpub event was accepted by that relay.
Future<List<NostrRelayStatus>> publishNostrBackup({
  required String walletPath,
  required String deviceKeyHex,
  String? openPassword,
  required List<String> relayUrls,
}) => RustLib.instance.api.crateApiWalletNostrBackupPublishNostrBackup(
  walletPath: walletPath,
  deviceKeyHex: deviceKeyHex,
  openPassword: openPassword,
  relayUrls: relayUrls,
);

/// Check which relays have a complete backup for this wallet.
///
/// `has_backup = true` means **every** xpub in the descriptor has published a
/// non-empty backup event with the matching d-tag on that relay.
/// `backed_up_xpubs` / `total_xpubs` give the exact per-cosigner breakdown
/// so the UI can distinguish "all backed up", "some backed up", and "none".
Future<List<NostrRelayStatus>> checkNostrBackupStatus({
  required String descriptor,
  required List<String> relayUrls,
}) => RustLib.instance.api.crateApiWalletNostrBackupCheckNostrBackupStatus(
  descriptor: descriptor,
  relayUrls: relayUrls,
);

/// Overwrite this wallet's backup on each relay with an empty placeholder event.
///
/// Kind 30078 is an addressable (parameterized-replaceable) event: publishing a
/// new event with the same author pubkey and d-tag replaces the previous one.
/// This is more reliable than NIP-09 deletion requests, which many relays ignore.
///
/// For every xpub in the descriptor an empty kind-30078 event is signed with the
/// derived Nostr keypair and published to each relay URL.
/// Returns one `NostrRelayStatus` per relay — `has_backup` reflects
/// whether the replacement was accepted (relay returned `["OK", id, true]`).
Future<List<NostrRelayStatus>> deleteNostrBackup({
  required String descriptor,
  required List<String> relayUrls,
}) => RustLib.instance.api.crateApiWalletNostrBackupDeleteNostrBackup(
  descriptor: descriptor,
  relayUrls: relayUrls,
);

/// Fetch all Nostr backups for a given xpub and decrypt each one to extract
/// metadata and the first external address.
///
/// One xpub can back up multiple distinct wallet descriptors (e.g. the same
/// hardware wallet key participates in several multisigs). This function returns
/// one `NostrBackupResponse` per distinct descriptor found on the relays.
/// Discovery requires only the xpub — no prior knowledge of the d-tag.
Future<List<NostrBackupResponse>> fetchNostrBackup({
  required String xpub,
  required List<String> relayUrls,
}) => RustLib.instance.api.crateApiWalletNostrBackupFetchNostrBackup(
  xpub: xpub,
  relayUrls: relayUrls,
);

/// Decrypt a Nostr backup payload and create a new wallet from the recovered
/// descriptor. The wallet is created as DeviceKey-protected (watch-only until
/// the user reconnects their hardware wallet or re-enters their mnemonic).
///
/// `xpub_credential`: bare xpub or `[mfp/path]xpub` keyspec.
Future<NostrImportResult> importNostrBackup({
  required List<int> backupBytes,
  required String xpubCredential,
  required String deviceKeyHex,
  required String walletsDir,
  String? walletNameOverride,
}) => RustLib.instance.api.crateApiWalletNostrBackupImportNostrBackup(
  backupBytes: backupBytes,
  xpubCredential: xpubCredential,
  deviceKeyHex: deviceKeyHex,
  walletsDir: walletsDir,
  walletNameOverride: walletNameOverride,
);

/// Response from `fetch_nostr_backup` with full metadata including first address.
class NostrBackupResponse {
  final Uint8List bytes;
  final String? walletName;
  final String? network;
  final PlatformInt64? createdAt;
  final String? firstAddress;
  final APIWalletType? walletType;

  /// The decrypted descriptor string. Present when decryption succeeded.
  /// Can be passed to `scan_descriptor` to fetch on-chain balance/tx count.
  final String? descriptor;

  const NostrBackupResponse({
    required this.bytes,
    this.walletName,
    this.network,
    this.createdAt,
    this.firstAddress,
    this.walletType,
    this.descriptor,
  });

  @override
  int get hashCode =>
      bytes.hashCode ^
      walletName.hashCode ^
      network.hashCode ^
      createdAt.hashCode ^
      firstAddress.hashCode ^
      walletType.hashCode ^
      descriptor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NostrBackupResponse &&
          runtimeType == other.runtimeType &&
          bytes == other.bytes &&
          walletName == other.walletName &&
          network == other.network &&
          createdAt == other.createdAt &&
          firstAddress == other.firstAddress &&
          walletType == other.walletType &&
          descriptor == other.descriptor;
}

/// Return type of `import_nostr_backup`.
class NostrImportResult {
  final APIWalletInfo wallet;

  const NostrImportResult({required this.wallet});

  @override
  int get hashCode => wallet.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NostrImportResult &&
          runtimeType == other.runtimeType &&
          wallet == other.wallet;
}

/// Status of a Nostr relay for one wallet's backup.
class NostrRelayStatus {
  final String url;

  /// True when every xpub in the descriptor has a valid backup event on this
  /// relay. An empty-content "deleted" event counts as no backup.
  final bool hasBackup;

  /// Unix timestamp of the most recent event found (or published).
  final PlatformInt64? lastPublishedAt;

  /// Event ID of the most recent event found.
  final String? eventId;

  /// Non-null when the relay could not be reached or returned an error.
  final String? error;

  /// Number of xpubs that have a valid backup for this specific descriptor.
  /// For singlesig this is 0 or 1; for multisig it can be anywhere from 0
  /// to `total_xpubs`.
  final PlatformInt64 backedUpXpubs;

  /// Total number of xpubs in the wallet descriptor (1 for singlesig,
  /// N for N-of-M multisig).
  final PlatformInt64 totalXpubs;

  const NostrRelayStatus({
    required this.url,
    required this.hasBackup,
    this.lastPublishedAt,
    this.eventId,
    this.error,
    required this.backedUpXpubs,
    required this.totalXpubs,
  });

  @override
  int get hashCode =>
      url.hashCode ^
      hasBackup.hashCode ^
      lastPublishedAt.hashCode ^
      eventId.hashCode ^
      error.hashCode ^
      backedUpXpubs.hashCode ^
      totalXpubs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NostrRelayStatus &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          hasBackup == other.hasBackup &&
          lastPublishedAt == other.lastPublishedAt &&
          eventId == other.eventId &&
          error == other.error &&
          backedUpXpubs == other.backedUpXpubs &&
          totalXpubs == other.totalXpubs;
}
