[package]
name = "rust_lib_deadbolt"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
flutter_rust_bridge = "=2.11.1"
bdk_wallet = { version = "2.3.0", features = ["rusqlite", "keys-bip39", "compiler"] }
anyhow = {version = "1.0", features = ["backtrace"]}
rand = { version = "0.9", features = ["os_rng"] }
secp256k1 = "0.29"
thiserror = "2"
bdk_electrum = "0.23.2"
regex = "1"
hex = "0.4.3"
serde_json = "1"
base64 = "0.22"
rusqlite = { version = "0.31", features = ["bundled-sqlcipher-vendored-openssl"] }

[dev-dependencies]
tempfile = "3"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
