use anyhow::Result;
use bdk_wallet::bitcoin::Network;
use bdk_wallet::{PersistedWallet, Wallet};
use rusqlite::Connection;

mod fiat_storage;
mod labels;
mod psbt_storage;
mod seed_storage;

// Re-export everything so existing call sites continue to work unchanged.
pub use fiat_storage::*;
pub use labels::*;
pub use psbt_storage::*;
pub use seed_storage::*;

////////////////////
// WalletInfoRow  //
////////////////////

pub struct WalletInfoRow {
    pub name: String,
    pub descriptor: String,
    pub network: String,
    pub created_at: i64,
    pub last_synced_at: Option<i64>,
}

/// Create the wallet_info table if needed and upsert the single row.
pub fn upsert_wallet_info(
    conn: &Connection,
    name: &str,
    descriptor: &str,
    network: &str,
    created_at: i64,
) -> Result<()> {
    conn.execute_batch(
        "CREATE TABLE IF NOT EXISTS wallet_info (
            id             INTEGER PRIMARY KEY CHECK (id = 1),
            name           TEXT NOT NULL,
            descriptor     TEXT NOT NULL,
            network        TEXT NOT NULL,
            created_at     INTEGER NOT NULL,
            last_synced_at INTEGER
        );",
    )?;
    conn.execute(
        "INSERT OR REPLACE INTO wallet_info
         (id, name, descriptor, network, created_at)
         VALUES (1, ?1, ?2, ?3, ?4)",
        rusqlite::params![name, descriptor, network, created_at],
    )?;
    Ok(())
}

/// Read the single wallet_info row.
pub fn read_wallet_info(conn: &Connection) -> Result<WalletInfoRow> {
    conn.query_row(
        "SELECT name, descriptor, network, created_at, last_synced_at
         FROM wallet_info WHERE id = 1",
        [],
        |row| {
            Ok(WalletInfoRow {
                name: row.get(0)?,
                descriptor: row.get(1)?,
                network: row.get(2)?,
                created_at: row.get(3)?,
                last_synced_at: row.get(4)?,
            })
        },
    )
    .map_err(|e| anyhow::anyhow!("wallet_info not found: {}", e))
}

/// Update last_synced_at to the current Unix timestamp and return it.
pub fn touch_last_synced(conn: &Connection) -> Result<i64> {
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)?
        .as_secs() as i64;
    conn.execute(
        "UPDATE wallet_info SET last_synced_at = ?1 WHERE id = 1",
        rusqlite::params![now],
    )?;
    Ok(now)
}

/// Re-key an existing SQLCipher database from `old_key_hex` to `new_key_hex`.
pub fn rekey_database(path: &str, old_key_hex: &str, new_key_hex: &str) -> Result<()> {
    let conn = open_encrypted_connection(path, old_key_hex)?;
    conn.execute_batch(&format!("PRAGMA rekey = \"x'{}'\"", new_key_hex))?;
    Ok(())
}

/// Open an encrypted SQLite connection using SQLCipher.
pub fn open_encrypted_connection(path: &str, key_hex: &str) -> Result<Connection> {
    let conn = Connection::open(path)?;
    conn.execute_batch(&format!("PRAGMA key = \"x'{}'\"", key_hex))?;
    // Enable WAL mode for efficient concurrent reads
    conn.execute_batch("PRAGMA journal_mode = WAL;")?;
    Ok(conn)
}

/// Load an existing BDK wallet from the encrypted database, or create it if it doesn't exist.
pub fn load_or_create_wallet(
    path: &str,
    descriptor: &str,
    network: Network,
    key_hex: &str,
) -> Result<(PersistedWallet<Connection>, Connection)> {
    let mut conn = open_encrypted_connection(path, key_hex)?;

    // Do not pass the descriptor to load(): create_from_two_path_descriptor
    // splits the two-path descriptor into external (<0>/*) and internal (<1>/*)
    // before persisting. Passing the original two-path descriptor as the
    // external key would never match what BDK stored, so load_wallet() would
    // always return None and then create_wallet() would panic on existing tables.
    let wallet = match Wallet::load().load_wallet(&mut conn)? {
        Some(w) => w,
        None => Wallet::create_from_two_path_descriptor(descriptor.to_owned())
            .network(network)
            .create_wallet(&mut conn)?,
    };

    ensure_tx_labels_table(&conn)?;
    ensure_address_labels_table(&conn)?;
    ensure_key_labels_table(&conn)?;
    ensure_path_labels_table(&conn)?;
    ensure_coin_labels_table(&conn)?;
    ensure_seed_entries_table(&conn)?;
    ensure_fiat_prices_table(&conn)?;

    // Clean up orphaned auto-labels created before source_entity was tracked.
    // Auto-labels are derived data and will be regenerated by repropagate_all_labels.
    conn.execute(
        "DELETE FROM tx_labels WHERE is_auto = 1 AND source_entity IS NULL",
        [],
    )?;
    conn.execute(
        "DELETE FROM address_labels WHERE is_auto = 1 AND source_entity IS NULL",
        [],
    )?;
    conn.execute(
        "DELETE FROM coin_labels WHERE is_auto = 1 AND source_entity IS NULL",
        [],
    )?;

    Ok((wallet, conn))
}

#[cfg(test)]
mod tests {
    use super::*;
    use bdk_wallet::bitcoin::Network;
    use tempfile::tempdir;

    #[test]
    fn test_upsert_and_read_wallet_info() -> Result<()> {
        let dir = tempdir()?;
        let path = dir.path().join("test.db").to_string_lossy().to_string();
        let conn = open_encrypted_connection(&path, KEY_HEX)?;

        upsert_wallet_info(&conn, "My Wallet", "desc", "bitcoin", 1_700_000_000)?;
        let row = read_wallet_info(&conn)?;

        assert_eq!(row.name, "My Wallet");
        assert_eq!(row.descriptor, "desc");
        assert_eq!(row.network, "bitcoin");
        assert_eq!(row.created_at, 1_700_000_000);
        assert!(row.last_synced_at.is_none());
        Ok(())
    }

    #[test]
    fn test_upsert_overwrites_previous_row() -> Result<()> {
        let dir = tempdir()?;
        let path = dir.path().join("test.db").to_string_lossy().to_string();
        let conn = open_encrypted_connection(&path, KEY_HEX)?;

        upsert_wallet_info(&conn, "Old Name", "desc", "testnet", 1_000)?;
        upsert_wallet_info(&conn, "New Name", "desc", "testnet", 1_000)?;
        let row = read_wallet_info(&conn)?;

        assert_eq!(row.name, "New Name");
        Ok(())
    }

    #[test]
    fn test_touch_last_synced() -> Result<()> {
        let dir = tempdir()?;
        let path = dir.path().join("test.db").to_string_lossy().to_string();
        let conn = open_encrypted_connection(&path, KEY_HEX)?;

        upsert_wallet_info(&conn, "Wallet", "desc", "bitcoin", 1_000)?;
        assert!(read_wallet_info(&conn)?.last_synced_at.is_none());

        let now = touch_last_synced(&conn)?;
        assert!(now > 0);
        let ts = read_wallet_info(&conn)?.last_synced_at;
        assert_eq!(ts, Some(now));
        Ok(())
    }

    #[test]
    fn test_read_wallet_info_missing_table() -> Result<()> {
        let dir = tempdir()?;
        let path = dir.path().join("test.db").to_string_lossy().to_string();
        let conn = open_encrypted_connection(&path, KEY_HEX)?;

        let result = read_wallet_info(&conn);
        assert!(result.is_err());
        Ok(())
    }

    // 2-of-2 mainnet WSH descriptor with two-path notation (<0;1>/*)
    const MAINNET_DESC: &str = "wsh(sortedmulti(2,[c449c5c5/48h/0h/0h/2h]xpub6Dtni7dearhzvCuQ3aZYC5VkDEnpjJjoCSJRxs2m6D63r1KzvgvAvQKypzqFpSZ2uaYfNx8HSgi63jcK4ZFgFCTVph1MTMZxP55L1am1Csn/<0;1>/*,[c61af686/48h/0h/0h/2h]xpub6EDTxSWtzPTBiQtxScLWm1sJ6By9QPrG6J5RvA3ZuKYHP1mfvyeyTG2Gy3CgnQ2ps5p6cgGTvuULfxuqQtSAvkVp9VyASus6pMFoe8mztCj/<0;1>/*))#0wct5td0";
    // 32-byte test encryption key (not secret — test only)
    const KEY_HEX: &str = "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20";

    #[test]
    fn test_open_encrypted_connection_creates_db() -> Result<()> {
        let dir = tempdir()?;
        let path = dir.path().join("test.db").to_string_lossy().to_string();

        let conn = open_encrypted_connection(&path, KEY_HEX)?;
        // Verify the connection works with a simple query
        let result: i64 = conn.query_row("SELECT 1", [], |row| row.get(0))?;
        assert_eq!(result, 1);
        Ok(())
    }

    #[test]
    fn test_load_or_create_creates_fresh_wallet() -> Result<()> {
        let dir = tempdir()?;
        let path = dir.path().join("wallet.db").to_string_lossy().to_string();

        let (_wallet, _conn) =
            load_or_create_wallet(&path, MAINNET_DESC, Network::Bitcoin, KEY_HEX)?;
        // File should now exist
        assert!(std::path::Path::new(&path).exists());
        Ok(())
    }

    #[test]
    fn test_load_or_create_reloads_existing() -> Result<()> {
        let dir = tempdir()?;
        let path = dir.path().join("wallet.db").to_string_lossy().to_string();

        // First call: creates the wallet
        let _ = load_or_create_wallet(&path, MAINNET_DESC, Network::Bitcoin, KEY_HEX)?;
        // Second call: must reload without panic
        let (_wallet, _conn) =
            load_or_create_wallet(&path, MAINNET_DESC, Network::Bitcoin, KEY_HEX)?;
        Ok(())
    }

    #[test]
    fn test_ensure_coin_labels_table_idempotent() -> Result<()> {
        let dir = tempdir()?;
        let path = dir.path().join("labels.db").to_string_lossy().to_string();
        let conn = open_encrypted_connection(&path, KEY_HEX)?;

        // Calling twice must not fail (Bug 3)
        ensure_coin_labels_table(&conn)?;
        ensure_coin_labels_table(&conn)?;
        Ok(())
    }

    #[test]
    fn test_set_tx_label_stores_source_entity() -> Result<()> {
        let dir = tempdir()?;
        let path = dir.path().join("labels.db").to_string_lossy().to_string();
        let conn = open_encrypted_connection(&path, KEY_HEX)?;
        ensure_tx_labels_table(&conn)?;

        set_tx_label(&conn, "txid1", "Salary", true, Some("addr:bc1q…"))?;
        let (label, is_auto) = get_tx_label_with_flag(&conn, "txid1")?.unwrap();
        assert_eq!(label, "Salary");
        assert!(is_auto);

        // source_entity should be persisted
        let source: Option<String> = conn
            .query_row(
                "SELECT source_entity FROM tx_labels WHERE txid = 'txid1'",
                [],
                |row| row.get(0),
            )
            .ok()
            .flatten();
        assert_eq!(source.as_deref(), Some("addr:bc1q…"));
        Ok(())
    }

    #[test]
    fn test_explicit_label_has_null_source_entity() -> Result<()> {
        let dir = tempdir()?;
        let path = dir.path().join("labels.db").to_string_lossy().to_string();
        let conn = open_encrypted_connection(&path, KEY_HEX)?;
        ensure_tx_labels_table(&conn)?;

        set_tx_label(&conn, "txid1", "Exchange", false, None)?;
        let source: Option<String> = conn
            .query_row(
                "SELECT source_entity FROM tx_labels WHERE txid = 'txid1'",
                [],
                |row| row.get(0),
            )
            .ok()
            .flatten();
        assert!(source.is_none());
        Ok(())
    }

    /// Reproduce the backup-labels bug: write a label via conn_a (opened through
    /// load_or_create_wallet), then check whether a fresh conn_b can see it.
    /// If conn_a leaves an open transaction, conn_b will see an empty table.
    #[test]
    fn test_label_visible_from_second_connection() -> Result<()> {
        let dir = tempdir()?;
        let path = dir.path().join("wallet.db").to_string_lossy().to_string();

        // Simulate the app: open wallet through load_or_create_wallet (same as CoreWallet::open)
        let (_wallet, conn_a) =
            load_or_create_wallet(&path, MAINNET_DESC, Network::Bitcoin, KEY_HEX)?;

        // Write a label exactly as set_address_label does from the live wallet
        set_address_label(&conn_a, "bc1qtest", "my-label", false, None)?;

        // conn_a can read it back (within its own transaction if any)
        let labels_a = get_all_address_labels(&conn_a)?;
        assert!(
            labels_a.contains_key("bc1qtest"),
            "Label not visible from conn_a itself"
        );

        // Now open a completely fresh connection — same as export_wallet_backup does
        let conn_b = open_encrypted_connection(&path, KEY_HEX)?;
        let labels_b = get_all_address_labels(&conn_b)?;
        assert!(
            labels_b.contains_key("bc1qtest"),
            "Label NOT visible from conn_b — conn_a likely has an uncommitted transaction. \
             labels_b = {:?}",
            labels_b
        );
        Ok(())
    }

    #[test]
    fn test_wrong_key_cannot_open_existing_db() -> Result<()> {
        let dir = tempdir()?;
        let path = dir.path().join("wallet.db").to_string_lossy().to_string();

        // Create with KEY_HEX
        let _ = load_or_create_wallet(&path, MAINNET_DESC, Network::Bitcoin, KEY_HEX)?;

        // Open with a different key — SQLCipher should reject this
        let wrong_key = "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff";
        let result = load_or_create_wallet(&path, MAINNET_DESC, Network::Bitcoin, wrong_key);
        assert!(result.is_err(), "Opening with wrong key should fail");
        Ok(())
    }
}
