use anyhow::Result;
use bdk_wallet::bitcoin::Network;
use bdk_wallet::{PersistedWallet, Wallet};
use rusqlite::Connection;

mod descriptor_sig_storage;
mod fiat_storage;
mod labels;
mod migrations;
mod propagation;
mod psbt_storage;
mod seed_storage;

// Re-export everything so existing call sites continue to work unchanged.
pub use descriptor_sig_storage::*;
pub use fiat_storage::*;
pub use labels::*;
pub use migrations::run_wallet_migrations;
pub use propagation::*;
pub use psbt_storage::*;
pub use seed_storage::*;

////////////////////
// WalletInfoRow  //
////////////////////

pub struct WalletInfoRow {
    pub name: String,
    pub descriptor: String,
    pub network: String,
    pub created_at: i64,
    pub last_synced_at: Option<i64>,
    /// SHA-256 hex of the first external receive address. Only set for locked
    /// (UserPassword / XpubKey) wallets when read from the meta sidecar.
    pub first_address_hash: Option<String>,
}

/// Create the wallet_info table if needed and upsert the single row.
pub fn upsert_wallet_info(
    conn: &Connection,
    name: &str,
    descriptor: &str,
    network: &str,
    created_at: i64,
) -> Result<()> {
    conn.execute_batch(
        "CREATE TABLE IF NOT EXISTS wallet_info (
            id             INTEGER PRIMARY KEY CHECK (id = 1),
            name           TEXT NOT NULL,
            descriptor     TEXT NOT NULL,
            network        TEXT NOT NULL,
            created_at     INTEGER NOT NULL,
            last_synced_at INTEGER
        );",
    )?;
    conn.execute(
        "INSERT OR REPLACE INTO wallet_info
         (id, name, descriptor, network, created_at)
         VALUES (1, ?1, ?2, ?3, ?4)",
        rusqlite::params![name, descriptor, network, created_at],
    )?;
    Ok(())
}

/// Read the single wallet_info row.
pub fn read_wallet_info(conn: &Connection) -> Result<WalletInfoRow> {
    conn.query_row(
        "SELECT name, descriptor, network, created_at, last_synced_at
         FROM wallet_info WHERE id = 1",
        [],
        |row| {
            Ok(WalletInfoRow {
                name: row.get(0)?,
                descriptor: row.get(1)?,
                network: row.get(2)?,
                created_at: row.get(3)?,
                last_synced_at: row.get(4)?,
                first_address_hash: None,
            })
        },
    )
    .map_err(|e| anyhow::anyhow!("wallet_info not found: {}", e))
}

/// Update last_synced_at to the current Unix timestamp and return it.
pub fn touch_last_synced(conn: &Connection) -> Result<i64> {
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)?
        .as_secs() as i64;
    conn.execute(
        "UPDATE wallet_info SET last_synced_at = ?1 WHERE id = 1",
        rusqlite::params![now],
    )?;
    Ok(now)
}

/// Re-key an existing SQLCipher database from `old_key_hex` to `new_key_hex`.
pub fn rekey_database(path: &str, old_key_hex: &str, new_key_hex: &str) -> Result<()> {
    let conn = open_encrypted_connection(path, old_key_hex)?;
    conn.execute_batch(&format!("PRAGMA rekey = \"x'{}'\"", new_key_hex))?;
    Ok(())
}

/// Open an encrypted SQLite connection using SQLCipher.
pub fn open_encrypted_connection(path: &str, key_hex: &str) -> Result<Connection> {
    let conn = Connection::open(path)?;
    conn.execute_batch(&format!("PRAGMA key = \"x'{}'\"", key_hex))?;
    // Enable WAL mode for efficient concurrent reads
    conn.execute_batch("PRAGMA journal_mode = WAL;")?;
    Ok(conn)
}

/// Load an existing BDK wallet from the encrypted database, or create it if it doesn't exist.
pub fn load_or_create_wallet(
    path: &str,
    descriptor: &str,
    network: Network,
    key_hex: &str,
) -> Result<(PersistedWallet<Connection>, Connection)> {
    let mut conn = open_encrypted_connection(path, key_hex)?;

    // Do not pass the descriptor to load(): create_from_two_path_descriptor
    // splits the two-path descriptor into external (<0>/*) and internal (<1>/*)
    // before persisting. Passing the original two-path descriptor as the
    // external key would never match what BDK stored, so load_wallet() would
    // always return None and then create_wallet() would panic on existing tables.
    let wallet = match Wallet::load().load_wallet(&mut conn)? {
        Some(w) => w,
        None => Wallet::create_from_two_path_descriptor(descriptor.to_owned())
            .network(network)
            .create_wallet(&mut conn)?,
    };

    run_wallet_migrations(&conn)?;

    // Clean up orphaned auto-labels created before source_entity was tracked.
    // Auto-labels are derived data and will be regenerated by repropagate_all_labels.
    conn.execute(
        "DELETE FROM tx_labels WHERE is_auto = 1 AND source_entity IS NULL",
        [],
    )?;
    conn.execute(
        "DELETE FROM address_labels WHERE is_auto = 1 AND source_entity IS NULL",
        [],
    )?;
    conn.execute(
        "DELETE FROM coin_labels WHERE is_auto = 1 AND source_entity IS NULL",
        [],
    )?;

    Ok((wallet, conn))
}

#[cfg(test)]
mod tests;
