// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'model.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<APIAnalysisResult> analyzeDescriptor({required String descriptor}) =>
    RustLib.instance.api.crateApiAnalyzerAnalyzeDescriptor(
      descriptor: descriptor,
    );

Future<String> buildDescriptor({
  required APIWalletType walletType,
  required List<APIPubKey> keys,
  required List<APISpendPathDef> spendPaths,
}) => RustLib.instance.api.crateApiAnalyzerBuildDescriptor(
  walletType: walletType,
  keys: keys,
  spendPaths: spendPaths,
);

/// Validate that a descriptor's keys are compatible with the requested network.
///
/// A descriptor carrying mainnet keys (xpub/ypub/zpub) cannot be used on any
/// testnet variant, and vice versa. Returns Ok(()) when compatible, or an
/// error with a human-readable explanation.
Future<void> validateDescriptorNetwork({
  required String descriptor,
  required APINetwork network,
}) => RustLib.instance.api.crateApiAnalyzerValidateDescriptorNetwork(
  descriptor: descriptor,
  network: network,
);

/// Format a Taproot descriptor for Liana compatibility.
///
/// Liana requires the NUMS unspendable xpub (used as TR internal key when no
/// key-path spend exists) to carry an explicit [00000000] origin fingerprint.
/// The BIP380 standard omits this fingerprint, which is what Deadbolt generates
/// and what Nunchuk/most wallets expect.
///
/// Returns `Some(formatted_descriptor)` when the descriptor is TR with a NUMS
/// xpub internal key (no origin). Returns `None` when the format does not apply
/// (not TR, TR with a real key-path, or NUMS already has an origin).
Future<String?> formatDescriptorForLiana({required String descriptor}) =>
    RustLib.instance.api.crateApiAnalyzerFormatDescriptorForLiana(
      descriptor: descriptor,
    );

/// Calculate spend path rustId from semantic timelock values
/// Used when Flutter needs to compute rustId from type+value storage
Future<int> calculateRustidFromTimelocks({
  required int threshold,
  required List<String> mfps,
  required APIRelativeTimelock relTimelock,
  required APIAbsoluteTimelock absTimelock,
}) => RustLib.instance.api.crateApiAnalyzerCalculateRustidFromTimelocks(
  threshold: threshold,
  mfps: mfps,
  relTimelock: relTimelock,
  absTimelock: absTimelock,
);

/// Validate a key and check network compatibility
///
/// Returns Ok(()) if the key is valid and compatible with the network,
/// or Err with a descriptive message if validation fails.
Future<void> validateKey({
  required String mfp,
  required String derivationPath,
  required String xpub,
  required APINetwork network,
}) => RustLib.instance.api.crateApiAnalyzerValidateKey(
  mfp: mfp,
  derivationPath: derivationPath,
  xpub: xpub,
  network: network,
);

class APIAnalysisResult {
  final String descriptor;
  final APINetwork network;
  final APIWalletType walletType;
  final List<APIPubKey> keys;
  final List<APISpendPath> spendPaths;

  const APIAnalysisResult({
    required this.descriptor,
    required this.network,
    required this.walletType,
    required this.keys,
    required this.spendPaths,
  });

  @override
  int get hashCode =>
      descriptor.hashCode ^
      network.hashCode ^
      walletType.hashCode ^
      keys.hashCode ^
      spendPaths.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIAnalysisResult &&
          runtimeType == other.runtimeType &&
          descriptor == other.descriptor &&
          network == other.network &&
          walletType == other.walletType &&
          keys == other.keys &&
          spendPaths == other.spendPaths;
}
