// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../core/spend_path.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `try_from`, `try_from`

class APIAbsoluteTimelock {
  final APIAbsoluteTimelockType timelockType;
  final int value;

  const APIAbsoluteTimelock({required this.timelockType, required this.value});

  static Future<APIAbsoluteTimelock> fromConsensus({required int consensus}) =>
      RustLib.instance.api.crateApiModelApiAbsoluteTimelockFromConsensus(
        consensus: consensus,
      );

  Future<int> toConsensus() => RustLib.instance.api
      .crateApiModelApiAbsoluteTimelockToConsensus(that: this);

  @override
  int get hashCode => timelockType.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIAbsoluteTimelock &&
          runtimeType == other.runtimeType &&
          timelockType == other.timelockType &&
          value == other.value;
}

enum APIAbsoluteTimelockType { blocks, timestamp }

/// One BIP44-style account discovered during a seed scan.
class APIAccountInfo {
  final int accountIndex;

  /// e.g. "84'/0'/3'"
  final String derivationPath;

  /// "[mfp/84'/0'/3']xpub…"
  final String keyspec;
  final APIWalletType walletType;

  /// First external receive address (m/0/0). Used for wallet matching.
  final String firstAddress;
  final int txCount;
  final BigInt balanceSat;

  const APIAccountInfo({
    required this.accountIndex,
    required this.derivationPath,
    required this.keyspec,
    required this.walletType,
    required this.firstAddress,
    required this.txCount,
    required this.balanceSat,
  });

  @override
  int get hashCode =>
      accountIndex.hashCode ^
      derivationPath.hashCode ^
      keyspec.hashCode ^
      walletType.hashCode ^
      firstAddress.hashCode ^
      txCount.hashCode ^
      balanceSat.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIAccountInfo &&
          runtimeType == other.runtimeType &&
          accountIndex == other.accountIndex &&
          derivationPath == other.derivationPath &&
          keyspec == other.keyspec &&
          walletType == other.walletType &&
          firstAddress == other.firstAddress &&
          txCount == other.txCount &&
          balanceSat == other.balanceSat;
}

class APIAddress {
  final String address;
  final int index;
  final APIKeychain keychain;
  final BigInt balanceSat;

  /// True if this address has appeared in at least one transaction output.
  final bool isUsed;

  /// Number of transactions in which this address appears as an output.
  final int txCount;

  /// Explicit user-set label (use for editing).
  final String? label;

  /// Display label — own label if set, otherwise propagated from a related entity.
  final String? effectiveLabel;

  /// True when `effective_label` is auto-propagated from a related entity, not explicitly set.
  final bool isAuto;

  const APIAddress({
    required this.address,
    required this.index,
    required this.keychain,
    required this.balanceSat,
    required this.isUsed,
    required this.txCount,
    this.label,
    this.effectiveLabel,
    required this.isAuto,
  });

  @override
  int get hashCode =>
      address.hashCode ^
      index.hashCode ^
      keychain.hashCode ^
      balanceSat.hashCode ^
      isUsed.hashCode ^
      txCount.hashCode ^
      label.hashCode ^
      effectiveLabel.hashCode ^
      isAuto.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIAddress &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          index == other.index &&
          keychain == other.keychain &&
          balanceSat == other.balanceSat &&
          isUsed == other.isUsed &&
          txCount == other.txCount &&
          label == other.label &&
          effectiveLabel == other.effectiveLabel &&
          isAuto == other.isAuto;
}

/// Full detail for an address.
class APIAddressDetails {
  final APIAddress address;

  /// Unspent coins at this address.
  final List<APIRelatedUtxo> relatedUtxos;

  /// All transactions that sent to or spent from this address (unconfirmed first).
  final List<APIRelatedTx> relatedTxs;

  const APIAddressDetails({
    required this.address,
    required this.relatedUtxos,
    required this.relatedTxs,
  });

  @override
  int get hashCode =>
      address.hashCode ^ relatedUtxos.hashCode ^ relatedTxs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIAddressDetails &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          relatedUtxos == other.relatedUtxos &&
          relatedTxs == other.relatedTxs;
}

class APIBalance {
  final BigInt confirmed;
  final BigInt trustedPending;
  final BigInt untrustedPending;
  final BigInt immature;

  const APIBalance({
    required this.confirmed,
    required this.trustedPending,
    required this.untrustedPending,
    required this.immature,
  });

  @override
  int get hashCode =>
      confirmed.hashCode ^
      trustedPending.hashCode ^
      untrustedPending.hashCode ^
      immature.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIBalance &&
          runtimeType == other.runtimeType &&
          confirmed == other.confirmed &&
          trustedPending == other.trustedPending &&
          untrustedPending == other.untrustedPending &&
          immature == other.immature;
}

/// One registered biometric slot in a UserPassword or XpubKey wallet.
class APIBiometricSlot {
  /// UUID v4 — used as the key identifier in the platform keystore.
  final String id;

  const APIBiometricSlot({required this.id});

  @override
  int get hashCode => id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIBiometricSlot &&
          runtimeType == other.runtimeType &&
          id == other.id;
}

class APICoinControl {
  final String txid;
  final int vout;

  const APICoinControl({required this.txid, required this.vout});

  @override
  int get hashCode => txid.hashCode ^ vout.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APICoinControl &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          vout == other.vout;
}

class APICpfpInfo {
  /// Total fee of all unconfirmed ancestor txs (sats). None if any ancestor fee is unknown.
  final BigInt? ancestorFeeSat;

  /// Total virtual size of all unconfirmed ancestor txs (vbytes).
  final int ancestorVsize;

  /// Ancestor fee rate (sat/vB): ancestor_fee / ancestor_vsize. 0.0 if fee unknown.
  final double ancestorFeeRateSatPerVb;

  /// Number of unconfirmed ancestor txs in the package (including direct parents).
  final int ancestorCount;

  const APICpfpInfo({
    this.ancestorFeeSat,
    required this.ancestorVsize,
    required this.ancestorFeeRateSatPerVb,
    required this.ancestorCount,
  });

  @override
  int get hashCode =>
      ancestorFeeSat.hashCode ^
      ancestorVsize.hashCode ^
      ancestorFeeRateSatPerVb.hashCode ^
      ancestorCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APICpfpInfo &&
          runtimeType == other.runtimeType &&
          ancestorFeeSat == other.ancestorFeeSat &&
          ancestorVsize == other.ancestorVsize &&
          ancestorFeeRateSatPerVb == other.ancestorFeeRateSatPerVb &&
          ancestorCount == other.ancestorCount;
}

/// A stored descriptor ownership signature for one participating key.
class APIDescriptorSig {
  /// Master fingerprint (8 lowercase hex chars) of the signing key.
  final String mfp;

  /// Full descriptor key entry, e.g. `[aabbccdd/48'/0'/0'/2']xpub…`
  final String xpubEntry;

  /// Signature type, determines the verification algorithm: "bip322" | "message"
  final String sigMethod;

  /// Unix timestamp (seconds) when the signature was created.
  final PlatformInt64 signedAt;

  /// Whether the signature currently passes verification against the stored descriptor.
  final bool isValid;

  const APIDescriptorSig({
    required this.mfp,
    required this.xpubEntry,
    required this.sigMethod,
    required this.signedAt,
    required this.isValid,
  });

  @override
  int get hashCode =>
      mfp.hashCode ^
      xpubEntry.hashCode ^
      sigMethod.hashCode ^
      signedAt.hashCode ^
      isValid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIDescriptorSig &&
          runtimeType == other.runtimeType &&
          mfp == other.mfp &&
          xpubEntry == other.xpubEntry &&
          sigMethod == other.sigMethod &&
          signedAt == other.signedAt &&
          isValid == other.isValid;
}

/// Result of [discover_accounts].
class APIDiscoveredAccounts {
  final List<APIAccountInfo> accounts;

  /// Total number of accounts scanned (including empty ones).
  final int scannedCount;

  const APIDiscoveredAccounts({
    required this.accounts,
    required this.scannedCount,
  });

  @override
  int get hashCode => accounts.hashCode ^ scannedCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIDiscoveredAccounts &&
          runtimeType == other.runtimeType &&
          accounts == other.accounts &&
          scannedCount == other.scannedCount;
}

class APIFiatPrice {
  final String txid;

  /// BTC price in the requested fiat currency at the time of the transaction.
  final double btcPrice;

  const APIFiatPrice({required this.txid, required this.btcPrice});

  @override
  int get hashCode => txid.hashCode ^ btcPrice.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIFiatPrice &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          btcPrice == other.btcPrice;
}

/// Metadata about a hot signing key stored inside the wallet.
/// The seed itself is never exposed via FFI — only the MFP and type.
class APIHotKeyInfo {
  /// Master fingerprint (8 lowercase hex chars).
  final String mfp;

  /// "mnemonic" or "xprv".
  final String seedType;

  /// Unix timestamp (seconds) when this key was added.
  final PlatformInt64 createdAt;

  const APIHotKeyInfo({
    required this.mfp,
    required this.seedType,
    required this.createdAt,
  });

  @override
  int get hashCode => mfp.hashCode ^ seedType.hashCode ^ createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIHotKeyInfo &&
          runtimeType == other.runtimeType &&
          mfp == other.mfp &&
          seedType == other.seedType &&
          createdAt == other.createdAt;
}

class APIHotKeyList {
  /// Successfully loaded hot keys.
  final List<APIHotKeyInfo> keys;

  /// Error messages for seed entries that could not be loaded from the database.
  final List<String> corruptRows;

  const APIHotKeyList({required this.keys, required this.corruptRows});

  @override
  int get hashCode => keys.hashCode ^ corruptRows.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIHotKeyList &&
          runtimeType == other.runtimeType &&
          keys == other.keys &&
          corruptRows == other.corruptRows;
}

/// Result of [`connect_hw_device`] / [`connect_hw_device_android`].
class APIHwConnectResult {
  /// Opaque session identifier used in subsequent hw_* calls.
  final String sessionId;

  /// If `Some(code)`: show the code to the user and call `wait_hw_pairing`.
  /// If `None`: device was already paired; it is ready immediately.
  final String? pairingCode;

  const APIHwConnectResult({required this.sessionId, this.pairingCode});

  @override
  int get hashCode => sessionId.hashCode ^ pairingCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIHwConnectResult &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          pairingCode == other.pairingCode;
}

/// A detected hardware wallet device (BitBox02 or similar).
class APIHwDevice {
  /// Platform-specific device path used to open it (e.g. hidapi path on Linux).
  final String devicePath;

  /// Human-readable product name, e.g. "BitBox02".
  final String productString;

  /// USB serial number (may be empty).
  final String serialNumber;

  const APIHwDevice({
    required this.devicePath,
    required this.productString,
    required this.serialNumber,
  });

  @override
  int get hashCode =>
      devicePath.hashCode ^ productString.hashCode ^ serialNumber.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIHwDevice &&
          runtimeType == other.runtimeType &&
          devicePath == other.devicePath &&
          productString == other.productString &&
          serialNumber == other.serialNumber;
}

/// Device info readable from a connected session via [`get_hw_session_info`]
/// or [`hw_active_session`].
class APIHwSessionInfo {
  /// Opaque session identifier used for subsequent operations.
  final String sessionId;

  /// Human-readable product name, e.g. "BitBox02".
  final String productString;

  /// Root fingerprint (lowercase hex, 8 chars), e.g. "aabbccdd".
  /// Empty string if pairing has not been completed yet.
  final String rootFingerprint;

  const APIHwSessionInfo({
    required this.sessionId,
    required this.productString,
    required this.rootFingerprint,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^ productString.hashCode ^ rootFingerprint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIHwSessionInfo &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          productString == other.productString &&
          rootFingerprint == other.rootFingerprint;
}

/// Returned by [APIWallet::import_psbt].
/// `was_merged` is true when the imported PSBT was combined with an existing record;
/// false when a brand-new record was created.
class APIImportPsbtResult {
  final APIPsbtInfo psbt;
  final bool wasMerged;

  const APIImportPsbtResult({required this.psbt, required this.wasMerged});

  @override
  int get hashCode => psbt.hashCode ^ wasMerged.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIImportPsbtResult &&
          runtimeType == other.runtimeType &&
          psbt == other.psbt &&
          wasMerged == other.wasMerged;
}

enum APIKeychain {
  /// External keychain — receive addresses (<0>/*)
  external_,

  /// Internal keychain — change addresses (<1>/*)
  internal,
}

enum APINetwork {
  bitcoin,
  testnet,
  testnet4,
  signet,
  regtest;

  /// Canonical serialization string stored in wallet_info.network column.
  Future<void> asStr() =>
      RustLib.instance.api.crateApiModelApiNetworkAsStr(that: this);

  /// Human-readable lowercase name for error messages and display.
  Future<void> displayName() =>
      RustLib.instance.api.crateApiModelApiNetworkDisplayName(that: this);
}

class APIPolicyPath {
  final String policyId;
  final Uint32List path;

  const APIPolicyPath({required this.policyId, required this.path});

  static Future<APIPolicyPath> default_() =>
      RustLib.instance.api.crateApiModelApiPolicyPathDefault();

  static Future<List<APIPolicyPath>> fromSpendpath({
    required SpendPath spendPath,
  }) => RustLib.instance.api.crateApiModelApiPolicyPathFromSpendpath(
    spendPath: spendPath,
  );

  @override
  int get hashCode => policyId.hashCode ^ path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIPolicyPath &&
          runtimeType == other.runtimeType &&
          policyId == other.policyId &&
          path == other.path;
}

/// Which protection scheme wraps the per-wallet data key.
enum APIProtectionType {
  /// Wrapped with the device key (automatic, no password needed).
  deviceKey,

  /// Wrapped with a key derived from a user password (Argon2id).
  userPassword,

  /// Each xpub in the descriptor has its own slot; any one can unlock.
  xpubKey,
}

class APIPsbtAnalysis {
  final List<APIPsbtSignerStatus> signers;
  final bool isFinalized;

  const APIPsbtAnalysis({required this.signers, required this.isFinalized});

  @override
  int get hashCode => signers.hashCode ^ isFinalized.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIPsbtAnalysis &&
          runtimeType == other.runtimeType &&
          signers == other.signers &&
          isFinalized == other.isFinalized;
}

class APIPsbtInfo {
  final PlatformInt64 id;
  final String psbtBase64;

  /// Txid of the unsigned transaction (deterministic, independent of signatures).
  final String txid;

  /// Explicit user-set label (use for editing).
  final String? label;

  /// Display label — own label if set, otherwise inherited from the recipient address.
  final String? effectiveLabel;

  /// True when `effective_label` is auto-propagated from the recipient address label.
  final bool isAuto;

  /// True when the recipient is one of this wallet's own addresses.
  final bool isSelfTransfer;
  final PlatformInt64 createdAt;
  final String recipient;
  final BigInt amountSat;
  final List<APIRecipient> recipients;
  final BigInt feeSat;
  final int spendPathId;
  final int threshold;
  final List<String> mfps;

  /// Max confirmation height of the input UTXOs at PSBT creation time.
  /// Used to compute unlock block for relative timelocks:
  ///   unlock_block = utxo_max_conf_height + timelock_blocks
  final PlatformInt64? utxoMaxConfHeight;

  /// True when at least one input of this PSBT has been confirmed-spent by
  /// another transaction. The PSBT can no longer be broadcast.
  final bool hasSpentInputs;

  const APIPsbtInfo({
    required this.id,
    required this.psbtBase64,
    required this.txid,
    this.label,
    this.effectiveLabel,
    required this.isAuto,
    required this.isSelfTransfer,
    required this.createdAt,
    required this.recipient,
    required this.amountSat,
    required this.recipients,
    required this.feeSat,
    required this.spendPathId,
    required this.threshold,
    required this.mfps,
    this.utxoMaxConfHeight,
    required this.hasSpentInputs,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      psbtBase64.hashCode ^
      txid.hashCode ^
      label.hashCode ^
      effectiveLabel.hashCode ^
      isAuto.hashCode ^
      isSelfTransfer.hashCode ^
      createdAt.hashCode ^
      recipient.hashCode ^
      amountSat.hashCode ^
      recipients.hashCode ^
      feeSat.hashCode ^
      spendPathId.hashCode ^
      threshold.hashCode ^
      mfps.hashCode ^
      utxoMaxConfHeight.hashCode ^
      hasSpentInputs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIPsbtInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          psbtBase64 == other.psbtBase64 &&
          txid == other.txid &&
          label == other.label &&
          effectiveLabel == other.effectiveLabel &&
          isAuto == other.isAuto &&
          isSelfTransfer == other.isSelfTransfer &&
          createdAt == other.createdAt &&
          recipient == other.recipient &&
          amountSat == other.amountSat &&
          recipients == other.recipients &&
          feeSat == other.feeSat &&
          spendPathId == other.spendPathId &&
          threshold == other.threshold &&
          mfps == other.mfps &&
          utxoMaxConfHeight == other.utxoMaxConfHeight &&
          hasSpentInputs == other.hasSpentInputs;
}

class APIPsbtSignerStatus {
  final String mfp;
  final bool hasSigned;

  const APIPsbtSignerStatus({required this.mfp, required this.hasSigned});

  @override
  int get hashCode => mfp.hashCode ^ hasSigned.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIPsbtSignerStatus &&
          runtimeType == other.runtimeType &&
          mfp == other.mfp &&
          hasSigned == other.hasSigned;
}

class APIPubKey {
  final String mfp;
  final String derivationPath;
  final String xpub;

  const APIPubKey({
    required this.mfp,
    required this.derivationPath,
    required this.xpub,
  });

  @override
  int get hashCode => mfp.hashCode ^ derivationPath.hashCode ^ xpub.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIPubKey &&
          runtimeType == other.runtimeType &&
          mfp == other.mfp &&
          derivationPath == other.derivationPath &&
          xpub == other.xpub;
}

class APIRbfInfo {
  /// Fee paid by the original spending tx (sats).
  final BigInt origFeeSat;

  /// Virtual size of the original spending tx (vbytes).
  final int origVsize;

  /// Fee rate of the original spending tx (sat/vB).
  final double origFeeRateSatPerVb;

  /// Number of unconfirmed descendants that would also be evicted by the replacement.
  /// BIP-125 Rule 4 requires covering their fees too.
  final int descendantCount;

  /// Sum of fees of all unconfirmed descendants (sats).
  /// None if any descendant's input values are unknown (Electrum fetch was not attempted
  /// for descendants — the UI should treat the minimum as a lower bound in that case).
  final BigInt? descendantFeeSat;

  /// Total virtual size of all unconfirmed descendants (vbytes).
  final int descendantVsize;

  /// Minimum absolute fee for a replacement tx (BIP-125 Rule 4 / PaysForRBF).
  /// = sum(orig_fee + descendant_fees) + orig_vsize × 1 sat/vB
  /// orig_vsize is used as a proxy for new_vsize (unknown at query time).
  /// The Dart layer refines this with the actual new tx vsize.
  final BigInt minFeeSat;

  /// Minimum fee rate the replacement must strictly exceed (ImprovesFeerateDiagram).
  /// = package_rate(orig + descendants) when descendants are known; orig_rate otherwise.
  final double minFeeRateSatPerVb;

  const APIRbfInfo({
    required this.origFeeSat,
    required this.origVsize,
    required this.origFeeRateSatPerVb,
    required this.descendantCount,
    this.descendantFeeSat,
    required this.descendantVsize,
    required this.minFeeSat,
    required this.minFeeRateSatPerVb,
  });

  @override
  int get hashCode =>
      origFeeSat.hashCode ^
      origVsize.hashCode ^
      origFeeRateSatPerVb.hashCode ^
      descendantCount.hashCode ^
      descendantFeeSat.hashCode ^
      descendantVsize.hashCode ^
      minFeeSat.hashCode ^
      minFeeRateSatPerVb.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIRbfInfo &&
          runtimeType == other.runtimeType &&
          origFeeSat == other.origFeeSat &&
          origVsize == other.origVsize &&
          origFeeRateSatPerVb == other.origFeeRateSatPerVb &&
          descendantCount == other.descendantCount &&
          descendantFeeSat == other.descendantFeeSat &&
          descendantVsize == other.descendantVsize &&
          minFeeSat == other.minFeeSat &&
          minFeeRateSatPerVb == other.minFeeRateSatPerVb;
}

class APIRecipient {
  final String address;
  final BigInt amountSat;

  /// When `Some`, this recipient is an OP_RETURN data carrier instead of a
  /// payment output. `address` is empty and `amount_sat` is ignored (forced to 0).
  final Uint8List? opReturnData;

  const APIRecipient({
    required this.address,
    required this.amountSat,
    this.opReturnData,
  });

  @override
  int get hashCode =>
      address.hashCode ^ amountSat.hashCode ^ opReturnData.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIRecipient &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          amountSat == other.amountSat &&
          opReturnData == other.opReturnData;
}

/// Output address entry shown inside a transaction detail dialog.
class APIRelatedAddress {
  final String address;

  /// Amount at this address in this transaction. None when the previous
  /// output could not be resolved (e.g. external input tx not in graph).
  final BigInt? valueSat;

  /// Display label (own or propagated via the label inheritance system).
  final String? effectiveLabel;

  /// True when `effective_label` is auto-propagated, not explicitly set on this address.
  final bool isAuto;

  /// True if this address belongs to our wallet.
  final bool isMine;

  /// When `Some`, this output is an OP_RETURN data carrier; `address` is empty
  /// and `value_sat` is 0 (Bitcoin standardness).
  final Uint8List? opReturnData;

  const APIRelatedAddress({
    required this.address,
    this.valueSat,
    this.effectiveLabel,
    required this.isAuto,
    required this.isMine,
    this.opReturnData,
  });

  static Future<APIRelatedAddress> default_() =>
      RustLib.instance.api.crateApiModelApiRelatedAddressDefault();

  @override
  int get hashCode =>
      address.hashCode ^
      valueSat.hashCode ^
      effectiveLabel.hashCode ^
      isAuto.hashCode ^
      isMine.hashCode ^
      opReturnData.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIRelatedAddress &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          valueSat == other.valueSat &&
          effectiveLabel == other.effectiveLabel &&
          isAuto == other.isAuto &&
          isMine == other.isMine &&
          opReturnData == other.opReturnData;
}

/// Compact transaction summary shown inside coin/address detail dialogs.
class APIRelatedTx {
  final String txid;

  /// Display label (own or propagated via the label inheritance system).
  final String? effectiveLabel;

  /// True when `effective_label` is auto-propagated, not explicitly set on this tx.
  final bool isAuto;
  final int? confirmationHeight;

  /// Sats received by this specific address/coin in this tx.
  final BigInt addrReceived;

  /// Sats spent from this specific address/coin in this tx.
  final BigInt addrSpent;
  final BigInt? fee;

  const APIRelatedTx({
    required this.txid,
    this.effectiveLabel,
    required this.isAuto,
    this.confirmationHeight,
    required this.addrReceived,
    required this.addrSpent,
    this.fee,
  });

  @override
  int get hashCode =>
      txid.hashCode ^
      effectiveLabel.hashCode ^
      isAuto.hashCode ^
      confirmationHeight.hashCode ^
      addrReceived.hashCode ^
      addrSpent.hashCode ^
      fee.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIRelatedTx &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          effectiveLabel == other.effectiveLabel &&
          isAuto == other.isAuto &&
          confirmationHeight == other.confirmationHeight &&
          addrReceived == other.addrReceived &&
          addrSpent == other.addrSpent &&
          fee == other.fee;
}

/// Compact UTXO summary shown inside tx/address detail dialogs.
class APIRelatedUtxo {
  final String txid;
  final int vout;
  final String address;
  final BigInt valueSat;

  /// Display label (own or propagated via the label inheritance system).
  final String? effectiveLabel;

  /// True when `effective_label` is auto-propagated, not explicitly set on this coin.
  final bool isAuto;

  const APIRelatedUtxo({
    required this.txid,
    required this.vout,
    required this.address,
    required this.valueSat,
    this.effectiveLabel,
    required this.isAuto,
  });

  @override
  int get hashCode =>
      txid.hashCode ^
      vout.hashCode ^
      address.hashCode ^
      valueSat.hashCode ^
      effectiveLabel.hashCode ^
      isAuto.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIRelatedUtxo &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          vout == other.vout &&
          address == other.address &&
          valueSat == other.valueSat &&
          effectiveLabel == other.effectiveLabel &&
          isAuto == other.isAuto;
}

class APIRelativeTimelock {
  final APIRelativeTimelockType timelockType;
  final int value;

  const APIRelativeTimelock({required this.timelockType, required this.value});

  static Future<APIRelativeTimelock> fromConsensus({required int consensus}) =>
      RustLib.instance.api.crateApiModelApiRelativeTimelockFromConsensus(
        consensus: consensus,
      );

  Future<int> toConsensus() => RustLib.instance.api
      .crateApiModelApiRelativeTimelockToConsensus(that: this);

  @override
  int get hashCode => timelockType.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIRelativeTimelock &&
          runtimeType == other.runtimeType &&
          timelockType == other.timelockType &&
          value == other.value;
}

enum APIRelativeTimelockType { blocks, time }

/// Argon2id brute-force resistance level for backup export and change-protection.
enum APISecurityLevel {
  /// m=65536 (64 MB), t=5 — ~300 ms on mobile. Good for interactive unlocking.
  standard,

  /// m=262144 (256 MB), t=6 — ~1.6 s on mobile. Requires deliberate effort.
  high,

  /// m=524288 (512 MB), t=10 — ~5.5 s on mobile. For long-term key storage.
  extreme;

  /// Infer level from stored m_cost (best match; defaults to Standard).
  static Future<APISecurityLevel> fromMCost({required int mCost}) =>
      RustLib.instance.api.crateApiModelApiSecurityLevelFromMCost(mCost: mCost);

  Future<int> mCost() =>
      RustLib.instance.api.crateApiModelApiSecurityLevelMCost(that: this);

  Future<int> tCost() =>
      RustLib.instance.api.crateApiModelApiSecurityLevelTCost(that: this);
}

class APISpendPath {
  final int id;
  final List<APIPolicyPath> policyPath;
  final int threshold;
  final List<String> mfps;
  final APIRelativeTimelock relTimelock;
  final APIAbsoluteTimelock absTimelock;
  final int wuBase;
  final int wuIn;
  final int wuOut;
  final int trDepth;

  /// Per-MFP change index (0=external, 1=internal, taproot leaf chain index, …).
  /// Used by callers (e.g. HW signing) to disambiguate which leaf each cosigner
  /// belongs to in multi-leaf taproot descriptors.
  final Map<String, int> keyChanges;
  final double vbSweep;

  const APISpendPath({
    required this.id,
    required this.policyPath,
    required this.threshold,
    required this.mfps,
    required this.relTimelock,
    required this.absTimelock,
    required this.wuBase,
    required this.wuIn,
    required this.wuOut,
    required this.trDepth,
    required this.keyChanges,
    required this.vbSweep,
  });

  static Future<List<APISpendPath>> fromSorted({
    required List<SpendPath> coreSpendPaths,
  }) => RustLib.instance.api.crateApiModelApiSpendPathFromSorted(
    coreSpendPaths: coreSpendPaths,
  );

  @override
  int get hashCode =>
      id.hashCode ^
      policyPath.hashCode ^
      threshold.hashCode ^
      mfps.hashCode ^
      relTimelock.hashCode ^
      absTimelock.hashCode ^
      wuBase.hashCode ^
      wuIn.hashCode ^
      wuOut.hashCode ^
      trDepth.hashCode ^
      keyChanges.hashCode ^
      vbSweep.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APISpendPath &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          policyPath == other.policyPath &&
          threshold == other.threshold &&
          mfps == other.mfps &&
          relTimelock == other.relTimelock &&
          absTimelock == other.absTimelock &&
          wuBase == other.wuBase &&
          wuIn == other.wuIn &&
          wuOut == other.wuOut &&
          trDepth == other.trDepth &&
          keyChanges == other.keyChanges &&
          vbSweep == other.vbSweep;
}

class APISpendPathDef {
  final int threshold;
  final List<String> mfps;
  final APIRelativeTimelock relTimelock;
  final APIAbsoluteTimelock absTimelock;
  final bool isKeyPath;

  /// Taproot script tree priority (0 = deepest/least likely, higher = shallower/more likely).
  /// Ignored for non-Taproot descriptors.
  final int priority;

  const APISpendPathDef({
    required this.threshold,
    required this.mfps,
    required this.relTimelock,
    required this.absTimelock,
    required this.isKeyPath,
    required this.priority,
  });

  @override
  int get hashCode =>
      threshold.hashCode ^
      mfps.hashCode ^
      relTimelock.hashCode ^
      absTimelock.hashCode ^
      isKeyPath.hashCode ^
      priority.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APISpendPathDef &&
          runtimeType == other.runtimeType &&
          threshold == other.threshold &&
          mfps == other.mfps &&
          relTimelock == other.relTimelock &&
          absTimelock == other.absTimelock &&
          isKeyPath == other.isKeyPath &&
          priority == other.priority;
}

class APITransaction {
  final String txid;
  final BigInt received;
  final BigInt sent;
  final BigInt? fee;
  final int? confirmationHeight;
  final BigInt? confirmationTime;

  /// Explicit user-set label (use for editing).
  final String? label;

  /// Display label — own label if set, otherwise propagated from a related entity.
  final String? effectiveLabel;

  /// True when `effective_label` is auto-propagated from a related entity, not explicitly set.
  final bool isAuto;

  const APITransaction({
    required this.txid,
    required this.received,
    required this.sent,
    this.fee,
    this.confirmationHeight,
    this.confirmationTime,
    this.label,
    this.effectiveLabel,
    required this.isAuto,
  });

  @override
  int get hashCode =>
      txid.hashCode ^
      received.hashCode ^
      sent.hashCode ^
      fee.hashCode ^
      confirmationHeight.hashCode ^
      confirmationTime.hashCode ^
      label.hashCode ^
      effectiveLabel.hashCode ^
      isAuto.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APITransaction &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          received == other.received &&
          sent == other.sent &&
          fee == other.fee &&
          confirmationHeight == other.confirmationHeight &&
          confirmationTime == other.confirmationTime &&
          label == other.label &&
          effectiveLabel == other.effectiveLabel &&
          isAuto == other.isAuto;
}

class APITransactionPage {
  final List<APITransaction> transactions;
  final int totalCount;
  final bool hasMore;

  const APITransactionPage({
    required this.transactions,
    required this.totalCount,
    required this.hasMore,
  });

  @override
  int get hashCode =>
      transactions.hashCode ^ totalCount.hashCode ^ hasMore.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APITransactionPage &&
          runtimeType == other.runtimeType &&
          transactions == other.transactions &&
          totalCount == other.totalCount &&
          hasMore == other.hasMore;
}

/// Full detail for a transaction.
class APITxDetails {
  final APITransaction tx;

  /// Unspent output coins created by this transaction.
  final List<APIRelatedUtxo> relatedUtxos;

  /// Input addresses (previous outputs spent by this transaction).
  final List<APIRelatedAddress> inputAddresses;

  /// All output addresses of this transaction.
  final List<APIRelatedAddress> outputAddresses;

  const APITxDetails({
    required this.tx,
    required this.relatedUtxos,
    required this.inputAddresses,
    required this.outputAddresses,
  });

  @override
  int get hashCode =>
      tx.hashCode ^
      relatedUtxos.hashCode ^
      inputAddresses.hashCode ^
      outputAddresses.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APITxDetails &&
          runtimeType == other.runtimeType &&
          tx == other.tx &&
          relatedUtxos == other.relatedUtxos &&
          inputAddresses == other.inputAddresses &&
          outputAddresses == other.outputAddresses;
}

class APITxMissingFiat {
  final String txid;

  /// Unix timestamp of confirmation; None for unconfirmed transactions.
  final PlatformInt64? confirmationTime;

  const APITxMissingFiat({required this.txid, this.confirmationTime});

  @override
  int get hashCode => txid.hashCode ^ confirmationTime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APITxMissingFiat &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          confirmationTime == other.confirmationTime;
}

/// Preview of an unsigned transaction before persisting a PSBT.
///
/// All amounts are in sats. `fee_rate_sat_per_vb` is the back-computed effective rate
/// even when the caller passed an absolute fee. `total_wu` is BDK's actual weight for the
/// resulting tx (drain or change present). `has_change` is true when a change output was added.
///
/// `insufficient_funds` is set instead of returning an error so the UI can render
/// gracefully while the user is still typing. Other fields hold sentinel zeros in that case.
///
/// `recipients` contains the canonical-encoded recipient addresses (parsed by BDK) and the
/// final amounts — for the drain recipient the amount reflects what BDK actually assigned.
///
/// `rbf_min_fee_sats` is the minimum absolute fee (BIP-125 Rule 4 / PaysForRBF) that the
/// replacement tx must strictly exceed, computed from the conflict cluster and the actual
/// new tx vsize. None when no RBF conflicts were declared.
class APITxPreview {
  final BigInt feeSats;
  final double feeRateSatPerVb;
  final BigInt changeSats;
  final BigInt sendSats;
  final BigInt totalWu;
  final bool hasChange;
  final bool insufficientFunds;
  final List<APIRecipient> recipients;
  final BigInt? rbfMinFeeSats;

  const APITxPreview({
    required this.feeSats,
    required this.feeRateSatPerVb,
    required this.changeSats,
    required this.sendSats,
    required this.totalWu,
    required this.hasChange,
    required this.insufficientFunds,
    required this.recipients,
    this.rbfMinFeeSats,
  });

  @override
  int get hashCode =>
      feeSats.hashCode ^
      feeRateSatPerVb.hashCode ^
      changeSats.hashCode ^
      sendSats.hashCode ^
      totalWu.hashCode ^
      hasChange.hashCode ^
      insufficientFunds.hashCode ^
      recipients.hashCode ^
      rbfMinFeeSats.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APITxPreview &&
          runtimeType == other.runtimeType &&
          feeSats == other.feeSats &&
          feeRateSatPerVb == other.feeRateSatPerVb &&
          changeSats == other.changeSats &&
          sendSats == other.sendSats &&
          totalWu == other.totalWu &&
          hasChange == other.hasChange &&
          insufficientFunds == other.insufficientFunds &&
          recipients == other.recipients &&
          rbfMinFeeSats == other.rbfMinFeeSats;
}

class APIUtxo {
  final String txid;
  final int vout;
  final BigInt valueSat;
  final APIKeychain keychain;
  final int derivationIndex;
  final String address;
  final bool isConfirmed;
  final int? confirmationHeight;

  /// Unix timestamp of the block that confirmed this UTXO; None = unconfirmed.
  final BigInt? confirmationTime;

  /// Explicit user-set label (use for editing).
  final String? label;

  /// Display label — own label if set, otherwise inherited from a related entity.
  final String? effectiveLabel;

  /// True when `effective_label` is auto-propagated from a related entity, not explicitly set.
  final bool isAuto;

  /// IDs of pending PSBTs (unsigned_txs.id) that spend this UTXO.
  /// Empty for most coins; populated by get_utxos().
  final Int64List pendingPsbtIds;

  /// TXID of an unconfirmed (mempool) transaction that spends this UTXO, if any.
  /// Higher-priority indicator than pending_psbt_ids: the spend has already been broadcast.
  final String? mempoolSpendingTxid;

  const APIUtxo({
    required this.txid,
    required this.vout,
    required this.valueSat,
    required this.keychain,
    required this.derivationIndex,
    required this.address,
    required this.isConfirmed,
    this.confirmationHeight,
    this.confirmationTime,
    this.label,
    this.effectiveLabel,
    required this.isAuto,
    required this.pendingPsbtIds,
    this.mempoolSpendingTxid,
  });

  @override
  int get hashCode =>
      txid.hashCode ^
      vout.hashCode ^
      valueSat.hashCode ^
      keychain.hashCode ^
      derivationIndex.hashCode ^
      address.hashCode ^
      isConfirmed.hashCode ^
      confirmationHeight.hashCode ^
      confirmationTime.hashCode ^
      label.hashCode ^
      effectiveLabel.hashCode ^
      isAuto.hashCode ^
      pendingPsbtIds.hashCode ^
      mempoolSpendingTxid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIUtxo &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          vout == other.vout &&
          valueSat == other.valueSat &&
          keychain == other.keychain &&
          derivationIndex == other.derivationIndex &&
          address == other.address &&
          isConfirmed == other.isConfirmed &&
          confirmationHeight == other.confirmationHeight &&
          confirmationTime == other.confirmationTime &&
          label == other.label &&
          effectiveLabel == other.effectiveLabel &&
          isAuto == other.isAuto &&
          pendingPsbtIds == other.pendingPsbtIds &&
          mempoolSpendingTxid == other.mempoolSpendingTxid;
}

/// Full detail for a UTXO.
class APIUtxoDetails {
  final APIUtxo utxo;

  /// Display label for this UTXO's address — own label if set, otherwise propagated.
  final String? addressEffectiveLabel;

  /// True when `address_effective_label` is auto-propagated, not explicitly set on the address.
  final bool addressLabelIsAuto;

  /// The transaction that created this UTXO.
  final APIRelatedTx creatingTx;

  const APIUtxoDetails({
    required this.utxo,
    this.addressEffectiveLabel,
    required this.addressLabelIsAuto,
    required this.creatingTx,
  });

  @override
  int get hashCode =>
      utxo.hashCode ^
      addressEffectiveLabel.hashCode ^
      addressLabelIsAuto.hashCode ^
      creatingTx.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIUtxoDetails &&
          runtimeType == other.runtimeType &&
          utxo == other.utxo &&
          addressEffectiveLabel == other.addressEffectiveLabel &&
          addressLabelIsAuto == other.addressLabelIsAuto &&
          creatingTx == other.creatingTx;
}

class APIWalletInfo {
  final String walletPath;
  final String name;
  final String descriptor;
  final APINetwork network;
  final PlatformInt64 createdAt;
  final PlatformInt64? lastSyncedAt;
  final APIWalletProtection protection;

  /// SHA-256 hex of the first external receive address. Only present for locked
  /// (UserPassword / XpubKey) wallets; used to match against discovered accounts
  /// during seed recovery without revealing the descriptor or xpub.
  final String? firstAddressHash;

  const APIWalletInfo({
    required this.walletPath,
    required this.name,
    required this.descriptor,
    required this.network,
    required this.createdAt,
    this.lastSyncedAt,
    required this.protection,
    this.firstAddressHash,
  });

  @override
  int get hashCode =>
      walletPath.hashCode ^
      name.hashCode ^
      descriptor.hashCode ^
      network.hashCode ^
      createdAt.hashCode ^
      lastSyncedAt.hashCode ^
      protection.hashCode ^
      firstAddressHash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIWalletInfo &&
          runtimeType == other.runtimeType &&
          walletPath == other.walletPath &&
          name == other.name &&
          descriptor == other.descriptor &&
          network == other.network &&
          createdAt == other.createdAt &&
          lastSyncedAt == other.lastSyncedAt &&
          protection == other.protection &&
          firstAddressHash == other.firstAddressHash;
}

/// Protection information returned as part of `APIWalletInfo`.
class APIWalletProtection {
  final APIProtectionType protectionType;

  /// True when this wallet requires a credential (password or xpub) to open.
  final bool needsPassword;

  /// The Argon2id security level in use (DeviceKey wallets always report Standard).
  final APISecurityLevel securityLevel;

  const APIWalletProtection({
    required this.protectionType,
    required this.needsPassword,
    required this.securityLevel,
  });

  @override
  int get hashCode =>
      protectionType.hashCode ^ needsPassword.hashCode ^ securityLevel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIWalletProtection &&
          runtimeType == other.runtimeType &&
          protectionType == other.protectionType &&
          needsPassword == other.needsPassword &&
          securityLevel == other.securityLevel;
}

enum APIWalletType {
  p2Pkh,
  p2Wpkh,
  p2Sh,
  p2Wsh,
  p2Tr,
  p2ShWpkh,
  p2ShWsh,
  unknown,
}

/// One registered xpub slot in a XpubKey-protected wallet.
class APIXpubSlot {
  /// Master fingerprint (8-char lowercase hex).
  final String mfp;

  /// Derivation path suffix stored as a display hint (e.g. "48h/0h/0h/2h").
  /// Empty for legacy slots.
  final String derivationHint;

  const APIXpubSlot({required this.mfp, required this.derivationHint});

  @override
  int get hashCode => mfp.hashCode ^ derivationHint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIXpubSlot &&
          runtimeType == other.runtimeType &&
          mfp == other.mfp &&
          derivationHint == other.derivationHint;
}
