// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../core/spend_path.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `try_from`, `try_from`

class APIAbsoluteTimelock {
  final APIAbsoluteTimelockType timelockType;
  final int value;

  const APIAbsoluteTimelock({required this.timelockType, required this.value});

  static Future<APIAbsoluteTimelock> fromConsensus({required int consensus}) =>
      RustLib.instance.api.crateApiModelApiAbsoluteTimelockFromConsensus(
        consensus: consensus,
      );

  Future<int> toConsensus() => RustLib.instance.api
      .crateApiModelApiAbsoluteTimelockToConsensus(that: this);

  @override
  int get hashCode => timelockType.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIAbsoluteTimelock &&
          runtimeType == other.runtimeType &&
          timelockType == other.timelockType &&
          value == other.value;
}

enum APIAbsoluteTimelockType { blocks, timestamp }

class APIAddress {
  final String address;
  final int index;
  final APIKeychain keychain;
  final BigInt balanceSat;

  /// True if this address has appeared in at least one transaction output.
  final bool isUsed;

  /// Number of transactions in which this address appears as an output.
  final int txCount;

  /// Explicit user-set label (use for editing).
  final String? label;

  /// Display label — own label if set, otherwise inherited from a related entity.
  final String? effectiveLabel;

  /// True when `effective_label` comes from a related entity (tx or UTXO), not this address.
  final bool labelIsInherited;

  const APIAddress({
    required this.address,
    required this.index,
    required this.keychain,
    required this.balanceSat,
    required this.isUsed,
    required this.txCount,
    this.label,
    this.effectiveLabel,
    required this.labelIsInherited,
  });

  @override
  int get hashCode =>
      address.hashCode ^
      index.hashCode ^
      keychain.hashCode ^
      balanceSat.hashCode ^
      isUsed.hashCode ^
      txCount.hashCode ^
      label.hashCode ^
      effectiveLabel.hashCode ^
      labelIsInherited.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIAddress &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          index == other.index &&
          keychain == other.keychain &&
          balanceSat == other.balanceSat &&
          isUsed == other.isUsed &&
          txCount == other.txCount &&
          label == other.label &&
          effectiveLabel == other.effectiveLabel &&
          labelIsInherited == other.labelIsInherited;
}

/// Full detail for an address.
class APIAddressDetails {
  final APIAddress address;

  /// Unspent coins at this address.
  final List<APIRelatedUtxo> relatedUtxos;

  /// All transactions that sent to or spent from this address (unconfirmed first).
  final List<APIRelatedTx> relatedTxs;

  const APIAddressDetails({
    required this.address,
    required this.relatedUtxos,
    required this.relatedTxs,
  });

  @override
  int get hashCode =>
      address.hashCode ^ relatedUtxos.hashCode ^ relatedTxs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIAddressDetails &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          relatedUtxos == other.relatedUtxos &&
          relatedTxs == other.relatedTxs;
}

class APIBalance {
  final BigInt confirmed;
  final BigInt trustedPending;
  final BigInt untrustedPending;
  final BigInt immature;

  const APIBalance({
    required this.confirmed,
    required this.trustedPending,
    required this.untrustedPending,
    required this.immature,
  });

  @override
  int get hashCode =>
      confirmed.hashCode ^
      trustedPending.hashCode ^
      untrustedPending.hashCode ^
      immature.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIBalance &&
          runtimeType == other.runtimeType &&
          confirmed == other.confirmed &&
          trustedPending == other.trustedPending &&
          untrustedPending == other.untrustedPending &&
          immature == other.immature;
}

class APICoinControl {
  final String txid;
  final int vout;

  const APICoinControl({required this.txid, required this.vout});

  @override
  int get hashCode => txid.hashCode ^ vout.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APICoinControl &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          vout == other.vout;
}

enum APIKeychain {
  /// External keychain — receive addresses (<0>/*)
  external_,

  /// Internal keychain — change addresses (<1>/*)
  internal,
}

enum APINetwork {
  bitcoin,
  testnet,
  testnet4,
  signet,
  regtest;

  /// Canonical serialization string stored in wallet_info.network column.
  Future<void> asStr() =>
      RustLib.instance.api.crateApiModelApiNetworkAsStr(that: this);

  /// Human-readable lowercase name for error messages and display.
  Future<void> displayName() =>
      RustLib.instance.api.crateApiModelApiNetworkDisplayName(that: this);
}

class APIPolicyPath {
  final String policyId;
  final Uint32List path;

  const APIPolicyPath({required this.policyId, required this.path});

  static Future<APIPolicyPath> default_() =>
      RustLib.instance.api.crateApiModelApiPolicyPathDefault();

  static Future<List<APIPolicyPath>> fromSpendpath({
    required SpendPath spendPath,
  }) => RustLib.instance.api.crateApiModelApiPolicyPathFromSpendpath(
    spendPath: spendPath,
  );

  @override
  int get hashCode => policyId.hashCode ^ path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIPolicyPath &&
          runtimeType == other.runtimeType &&
          policyId == other.policyId &&
          path == other.path;
}

class APIPsbtAnalysis {
  final List<APIPsbtSignerStatus> signers;
  final bool isFinalized;

  const APIPsbtAnalysis({required this.signers, required this.isFinalized});

  @override
  int get hashCode => signers.hashCode ^ isFinalized.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIPsbtAnalysis &&
          runtimeType == other.runtimeType &&
          signers == other.signers &&
          isFinalized == other.isFinalized;
}

class APIPsbtInfo {
  final PlatformInt64 id;
  final String psbtBase64;
  final String? label;
  final PlatformInt64 createdAt;
  final String recipient;
  final BigInt amountSat;
  final BigInt feeSat;
  final int spendPathId;
  final int threshold;
  final List<String> mfps;

  /// Max confirmation height of the input UTXOs at PSBT creation time.
  /// Used to compute unlock block for relative timelocks:
  ///   unlock_block = utxo_max_conf_height + timelock_blocks
  final PlatformInt64? utxoMaxConfHeight;

  const APIPsbtInfo({
    required this.id,
    required this.psbtBase64,
    this.label,
    required this.createdAt,
    required this.recipient,
    required this.amountSat,
    required this.feeSat,
    required this.spendPathId,
    required this.threshold,
    required this.mfps,
    this.utxoMaxConfHeight,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      psbtBase64.hashCode ^
      label.hashCode ^
      createdAt.hashCode ^
      recipient.hashCode ^
      amountSat.hashCode ^
      feeSat.hashCode ^
      spendPathId.hashCode ^
      threshold.hashCode ^
      mfps.hashCode ^
      utxoMaxConfHeight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIPsbtInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          psbtBase64 == other.psbtBase64 &&
          label == other.label &&
          createdAt == other.createdAt &&
          recipient == other.recipient &&
          amountSat == other.amountSat &&
          feeSat == other.feeSat &&
          spendPathId == other.spendPathId &&
          threshold == other.threshold &&
          mfps == other.mfps &&
          utxoMaxConfHeight == other.utxoMaxConfHeight;
}

class APIPsbtSignerStatus {
  final String mfp;
  final bool hasSigned;

  const APIPsbtSignerStatus({required this.mfp, required this.hasSigned});

  @override
  int get hashCode => mfp.hashCode ^ hasSigned.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIPsbtSignerStatus &&
          runtimeType == other.runtimeType &&
          mfp == other.mfp &&
          hasSigned == other.hasSigned;
}

class APIPubKey {
  final String mfp;
  final String derivationPath;
  final String xpub;

  const APIPubKey({
    required this.mfp,
    required this.derivationPath,
    required this.xpub,
  });

  @override
  int get hashCode => mfp.hashCode ^ derivationPath.hashCode ^ xpub.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIPubKey &&
          runtimeType == other.runtimeType &&
          mfp == other.mfp &&
          derivationPath == other.derivationPath &&
          xpub == other.xpub;
}

/// Output address entry shown inside a transaction detail dialog.
class APIRelatedAddress {
  final String address;

  /// Amount at this address in this transaction. None when the previous
  /// output could not be resolved (e.g. external input tx not in graph).
  final BigInt? valueSat;

  /// Explicit label on this address (None if unlabelled or external).
  final String? label;

  /// True if this address belongs to our wallet.
  final bool isMine;

  const APIRelatedAddress({
    required this.address,
    this.valueSat,
    this.label,
    required this.isMine,
  });

  @override
  int get hashCode =>
      address.hashCode ^ valueSat.hashCode ^ label.hashCode ^ isMine.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIRelatedAddress &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          valueSat == other.valueSat &&
          label == other.label &&
          isMine == other.isMine;
}

/// Compact transaction summary shown inside coin/address detail dialogs.
class APIRelatedTx {
  final String txid;
  final String? label;
  final int? confirmationHeight;

  /// Sats received by this specific address/coin in this tx.
  final BigInt addrReceived;

  /// Sats spent from this specific address/coin in this tx.
  final BigInt addrSpent;
  final BigInt? fee;

  const APIRelatedTx({
    required this.txid,
    this.label,
    this.confirmationHeight,
    required this.addrReceived,
    required this.addrSpent,
    this.fee,
  });

  @override
  int get hashCode =>
      txid.hashCode ^
      label.hashCode ^
      confirmationHeight.hashCode ^
      addrReceived.hashCode ^
      addrSpent.hashCode ^
      fee.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIRelatedTx &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          label == other.label &&
          confirmationHeight == other.confirmationHeight &&
          addrReceived == other.addrReceived &&
          addrSpent == other.addrSpent &&
          fee == other.fee;
}

/// Compact UTXO summary shown inside tx/address detail dialogs.
class APIRelatedUtxo {
  final String txid;
  final int vout;
  final String address;
  final BigInt valueSat;

  /// Explicit label on this UTXO.
  final String? utxoLabel;

  /// Explicit label on this UTXO's address.
  final String? addressLabel;

  const APIRelatedUtxo({
    required this.txid,
    required this.vout,
    required this.address,
    required this.valueSat,
    this.utxoLabel,
    this.addressLabel,
  });

  @override
  int get hashCode =>
      txid.hashCode ^
      vout.hashCode ^
      address.hashCode ^
      valueSat.hashCode ^
      utxoLabel.hashCode ^
      addressLabel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIRelatedUtxo &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          vout == other.vout &&
          address == other.address &&
          valueSat == other.valueSat &&
          utxoLabel == other.utxoLabel &&
          addressLabel == other.addressLabel;
}

class APIRelativeTimelock {
  final APIRelativeTimelockType timelockType;
  final int value;

  const APIRelativeTimelock({required this.timelockType, required this.value});

  static Future<APIRelativeTimelock> fromConsensus({required int consensus}) =>
      RustLib.instance.api.crateApiModelApiRelativeTimelockFromConsensus(
        consensus: consensus,
      );

  Future<int> toConsensus() => RustLib.instance.api
      .crateApiModelApiRelativeTimelockToConsensus(that: this);

  @override
  int get hashCode => timelockType.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIRelativeTimelock &&
          runtimeType == other.runtimeType &&
          timelockType == other.timelockType &&
          value == other.value;
}

enum APIRelativeTimelockType { blocks, time }

class APISpendPath {
  final int id;
  final List<APIPolicyPath> policyPath;
  final int threshold;
  final List<String> mfps;
  final APIRelativeTimelock relTimelock;
  final APIAbsoluteTimelock absTimelock;
  final int wuBase;
  final int wuIn;
  final int wuOut;
  final int trDepth;
  final double vbSweep;

  const APISpendPath({
    required this.id,
    required this.policyPath,
    required this.threshold,
    required this.mfps,
    required this.relTimelock,
    required this.absTimelock,
    required this.wuBase,
    required this.wuIn,
    required this.wuOut,
    required this.trDepth,
    required this.vbSweep,
  });

  static Future<List<APISpendPath>> fromSorted({
    required List<SpendPath> coreSpendPaths,
  }) => RustLib.instance.api.crateApiModelApiSpendPathFromSorted(
    coreSpendPaths: coreSpendPaths,
  );

  @override
  int get hashCode =>
      id.hashCode ^
      policyPath.hashCode ^
      threshold.hashCode ^
      mfps.hashCode ^
      relTimelock.hashCode ^
      absTimelock.hashCode ^
      wuBase.hashCode ^
      wuIn.hashCode ^
      wuOut.hashCode ^
      trDepth.hashCode ^
      vbSweep.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APISpendPath &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          policyPath == other.policyPath &&
          threshold == other.threshold &&
          mfps == other.mfps &&
          relTimelock == other.relTimelock &&
          absTimelock == other.absTimelock &&
          wuBase == other.wuBase &&
          wuIn == other.wuIn &&
          wuOut == other.wuOut &&
          trDepth == other.trDepth &&
          vbSweep == other.vbSweep;
}

class APISpendPathDef {
  final int threshold;
  final List<String> mfps;
  final APIRelativeTimelock relTimelock;
  final APIAbsoluteTimelock absTimelock;
  final bool isKeyPath;

  /// Taproot script tree priority (0 = deepest/least likely, higher = shallower/more likely).
  /// Ignored for non-Taproot descriptors.
  final int priority;

  const APISpendPathDef({
    required this.threshold,
    required this.mfps,
    required this.relTimelock,
    required this.absTimelock,
    required this.isKeyPath,
    required this.priority,
  });

  @override
  int get hashCode =>
      threshold.hashCode ^
      mfps.hashCode ^
      relTimelock.hashCode ^
      absTimelock.hashCode ^
      isKeyPath.hashCode ^
      priority.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APISpendPathDef &&
          runtimeType == other.runtimeType &&
          threshold == other.threshold &&
          mfps == other.mfps &&
          relTimelock == other.relTimelock &&
          absTimelock == other.absTimelock &&
          isKeyPath == other.isKeyPath &&
          priority == other.priority;
}

class APITransaction {
  final String txid;
  final BigInt received;
  final BigInt sent;
  final BigInt? fee;
  final int? confirmationHeight;
  final BigInt? confirmationTime;

  /// Explicit user-set label (use for editing).
  final String? label;

  /// Display label — own label if set, otherwise inherited from a related entity.
  final String? effectiveLabel;

  /// True when `effective_label` comes from a related entity (address or UTXO), not this tx.
  final bool labelIsInherited;

  const APITransaction({
    required this.txid,
    required this.received,
    required this.sent,
    this.fee,
    this.confirmationHeight,
    this.confirmationTime,
    this.label,
    this.effectiveLabel,
    required this.labelIsInherited,
  });

  @override
  int get hashCode =>
      txid.hashCode ^
      received.hashCode ^
      sent.hashCode ^
      fee.hashCode ^
      confirmationHeight.hashCode ^
      confirmationTime.hashCode ^
      label.hashCode ^
      effectiveLabel.hashCode ^
      labelIsInherited.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APITransaction &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          received == other.received &&
          sent == other.sent &&
          fee == other.fee &&
          confirmationHeight == other.confirmationHeight &&
          confirmationTime == other.confirmationTime &&
          label == other.label &&
          effectiveLabel == other.effectiveLabel &&
          labelIsInherited == other.labelIsInherited;
}

class APITransactionPage {
  final List<APITransaction> transactions;
  final int totalCount;
  final bool hasMore;

  const APITransactionPage({
    required this.transactions,
    required this.totalCount,
    required this.hasMore,
  });

  @override
  int get hashCode =>
      transactions.hashCode ^ totalCount.hashCode ^ hasMore.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APITransactionPage &&
          runtimeType == other.runtimeType &&
          transactions == other.transactions &&
          totalCount == other.totalCount &&
          hasMore == other.hasMore;
}

/// Full detail for a transaction.
class APITxDetails {
  final APITransaction tx;

  /// Unspent output coins created by this transaction.
  final List<APIRelatedUtxo> relatedUtxos;

  /// Input addresses (previous outputs spent by this transaction).
  final List<APIRelatedAddress> inputAddresses;

  /// All output addresses of this transaction.
  final List<APIRelatedAddress> outputAddresses;

  const APITxDetails({
    required this.tx,
    required this.relatedUtxos,
    required this.inputAddresses,
    required this.outputAddresses,
  });

  @override
  int get hashCode =>
      tx.hashCode ^
      relatedUtxos.hashCode ^
      inputAddresses.hashCode ^
      outputAddresses.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APITxDetails &&
          runtimeType == other.runtimeType &&
          tx == other.tx &&
          relatedUtxos == other.relatedUtxos &&
          inputAddresses == other.inputAddresses &&
          outputAddresses == other.outputAddresses;
}

class APIUtxo {
  final String txid;
  final int vout;
  final BigInt valueSat;
  final APIKeychain keychain;
  final int derivationIndex;
  final String address;
  final bool isConfirmed;
  final int? confirmationHeight;

  /// Explicit user-set label (use for editing).
  final String? label;

  /// Display label — own label if set, otherwise inherited from a related entity.
  final String? effectiveLabel;

  /// True when `effective_label` comes from a related entity (address or tx), not this UTXO.
  final bool labelIsInherited;

  const APIUtxo({
    required this.txid,
    required this.vout,
    required this.valueSat,
    required this.keychain,
    required this.derivationIndex,
    required this.address,
    required this.isConfirmed,
    this.confirmationHeight,
    this.label,
    this.effectiveLabel,
    required this.labelIsInherited,
  });

  @override
  int get hashCode =>
      txid.hashCode ^
      vout.hashCode ^
      valueSat.hashCode ^
      keychain.hashCode ^
      derivationIndex.hashCode ^
      address.hashCode ^
      isConfirmed.hashCode ^
      confirmationHeight.hashCode ^
      label.hashCode ^
      effectiveLabel.hashCode ^
      labelIsInherited.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIUtxo &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          vout == other.vout &&
          valueSat == other.valueSat &&
          keychain == other.keychain &&
          derivationIndex == other.derivationIndex &&
          address == other.address &&
          isConfirmed == other.isConfirmed &&
          confirmationHeight == other.confirmationHeight &&
          label == other.label &&
          effectiveLabel == other.effectiveLabel &&
          labelIsInherited == other.labelIsInherited;
}

/// Full detail for a UTXO.
class APIUtxoDetails {
  final APIUtxo utxo;

  /// Explicit label on this UTXO's address.
  final String? addressLabel;

  /// The transaction that created this UTXO.
  final APIRelatedTx creatingTx;

  const APIUtxoDetails({
    required this.utxo,
    this.addressLabel,
    required this.creatingTx,
  });

  @override
  int get hashCode =>
      utxo.hashCode ^ addressLabel.hashCode ^ creatingTx.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIUtxoDetails &&
          runtimeType == other.runtimeType &&
          utxo == other.utxo &&
          addressLabel == other.addressLabel &&
          creatingTx == other.creatingTx;
}

class APIWalletInfo {
  final String walletPath;
  final String name;
  final String descriptor;
  final APINetwork network;
  final PlatformInt64? sourceProjectId;
  final PlatformInt64 createdAt;
  final PlatformInt64? lastSyncedAt;

  const APIWalletInfo({
    required this.walletPath,
    required this.name,
    required this.descriptor,
    required this.network,
    this.sourceProjectId,
    required this.createdAt,
    this.lastSyncedAt,
  });

  @override
  int get hashCode =>
      walletPath.hashCode ^
      name.hashCode ^
      descriptor.hashCode ^
      network.hashCode ^
      sourceProjectId.hashCode ^
      createdAt.hashCode ^
      lastSyncedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIWalletInfo &&
          runtimeType == other.runtimeType &&
          walletPath == other.walletPath &&
          name == other.name &&
          descriptor == other.descriptor &&
          network == other.network &&
          sourceProjectId == other.sourceProjectId &&
          createdAt == other.createdAt &&
          lastSyncedAt == other.lastSyncedAt;
}

enum APIWalletType {
  p2Pkh,
  p2Wpkh,
  p2Sh,
  p2Wsh,
  p2Tr,
  p2ShWpkh,
  p2ShWsh,
  unknown,
}
