// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Start Tor in the background. Returns immediately; use [isTorRunning] to
/// poll bootstrap completion.
void startTor() => RustLib.instance.api.crateApiTorStartTor();

/// Stop Tor and close all circuits.
void stopTor() => RustLib.instance.api.crateApiTorStopTor();

/// True once Tor has fully bootstrapped and the local SOCKS5 listener is ready.
bool isTorRunning() => RustLib.instance.api.crateApiTorIsTorRunning();

/// Persist the enabled flag in Rust so wallet operations can enforce it.
/// Call before [startTor] / [stopTor].
void setTorEnabled({required bool enabled}) =>
    RustLib.instance.api.crateApiTorSetTorEnabled(enabled: enabled);

/// True if the user has enabled Tor (may be true while still bootstrapping).
bool isTorEnabled() => RustLib.instance.api.crateApiTorIsTorEnabled();

/// Set the directory used for Tor state / cache (call before [startTor]).
/// Pass the app's persistent support directory so guard info survives restarts.
void setTorDataDir({required String path}) =>
    RustLib.instance.api.crateApiTorSetTorDataDir(path: path);

/// Bootstrap progress: fraction 0.0–1.0 and a human-readable status line.
/// Poll this while [isTorRunning] is false to show detailed progress to the user.
(double, String) torBootstrapProgress() =>
    RustLib.instance.api.crateApiTorTorBootstrapProgress();

/// Returns the local SOCKS5 address (e.g. "127.0.0.1:51234") when Tor is
/// running and the listener is ready, or None otherwise.
String? torSocksAddr() => RustLib.instance.api.crateApiTorTorSocksAddr();
