// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'model.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'wallet/descriptor_backup.dart';
import 'wallet/descriptor_sig.dart';

// These functions are ignored because they are not marked as `pub`: `apply_psbt_label_to_tx`, `chain_conf_info`, `create_electrum_client`, `create_raw_electrum_client`, `derive_and_format_keyspec`, `load_all_label_maps`, `lock_wallet`, `protection_for_path`, `psbt_effective_label`, `psbt_from_base64`, `psbt_to_base64`, `resolve_label`, `row_to_api_info`, `row_to_api_psbt_loaded`, `row_to_api_psbt`

/// Return all wallets found in wallets_dir, sorted newest-first.
Future<List<APIWalletInfo>> listWallets({
  required String walletsDir,
  required String encryptionKeyHex,
}) => RustLib.instance.api.crateApiWalletListWallets(
  walletsDir: walletsDir,
  encryptionKeyHex: encryptionKeyHex,
);

/// Create a new wallet .db file and return its info.
Future<APIWalletInfo> createWallet({
  required String walletsDir,
  required String name,
  required String descriptor,
  required APINetwork network,
  required String deviceKeyHex,
  required APIProtectionType protectionType,
  String? password,
  required APISecurityLevel securityLevel,
}) => RustLib.instance.api.crateApiWalletCreateWallet(
  walletsDir: walletsDir,
  name: name,
  descriptor: descriptor,
  network: network,
  deviceKeyHex: deviceKeyHex,
  protectionType: protectionType,
  password: password,
  securityLevel: securityLevel,
);

/// Read metadata from an existing wallet file.
/// Pass `password` for UserPassword wallets, `None` for DeviceKey wallets.
Future<APIWalletInfo> getWalletInfo({
  required String walletPath,
  required String deviceKeyHex,
  String? password,
}) => RustLib.instance.api.crateApiWalletGetWalletInfo(
  walletPath: walletPath,
  deviceKeyHex: deviceKeyHex,
  password: password,
);

/// Rename a wallet (updates wallet_info.name in the file).
/// Pass `password` for UserPassword wallets, `None` for DeviceKey wallets.
Future<void> renameWallet({
  required String walletPath,
  required String name,
  required String deviceKeyHex,
  String? password,
}) => RustLib.instance.api.crateApiWalletRenameWallet(
  walletPath: walletPath,
  name: name,
  deviceKeyHex: deviceKeyHex,
  password: password,
);

/// Delete a wallet's .db, .db-wal, .db-shm, and .db.meta files.
Future<void> deleteWallet({required String walletPath}) =>
    RustLib.instance.api.crateApiWalletDeleteWallet(walletPath: walletPath);

/// Open a wallet once and hold the live handle for repeated operations.
///
/// Reads descriptor and network from wallet_info inside the encrypted file,
/// then opens the BDK wallet in a single SQLite connection.
/// Pass `password` for UserPassword wallets, `None` for DeviceKey wallets.
/// Pass `biometric_key_hex` to unlock via a registered biometric slot instead of
/// the normal credential; biometric slots are tried first when this is `Some`.
Future<ApiWallet> openWallet({
  required String walletPath,
  required String deviceKeyHex,
  String? password,
  String? biometricKeyHex,
}) => RustLib.instance.api.crateApiWalletOpenWallet(
  walletPath: walletPath,
  deviceKeyHex: deviceKeyHex,
  password: password,
  biometricKeyHex: biometricKeyHex,
);

/// Check whether a wallet requires a credential (password or xpub) to open.
Future<bool> walletRequiresPassword({required String walletPath}) => RustLib
    .instance
    .api
    .crateApiWalletWalletRequiresPassword(walletPath: walletPath);

/// Check whether a wallet is XpubKey protected.
Future<bool> walletRequiresXpub({required String walletPath}) => RustLib
    .instance
    .api
    .crateApiWalletWalletRequiresXpub(walletPath: walletPath);

/// Return the network stored in the wallet meta sidecar without opening the DB.
/// Returns None for DeviceKey wallets or when the meta cannot be read.
Future<String?> getWalletNetworkHint({required String walletPath}) => RustLib
    .instance
    .api
    .crateApiWalletGetWalletNetworkHint(walletPath: walletPath);

/// Add a new xpub slot to a XpubKey-protected wallet.
/// `current_xpub` is any already-registered xpub (used to derive the data key).
/// `new_mfp` and `new_xpub` identify the slot to add.
/// Derivation is looked up from the wallet descriptor automatically.
Future<void> addXpubSlot({
  required String walletPath,
  required String newMfp,
  required String newXpub,
  required String deviceKeyHex,
  required String currentXpub,
}) => RustLib.instance.api.crateApiWalletAddXpubSlot(
  walletPath: walletPath,
  newMfp: newMfp,
  newXpub: newXpub,
  deviceKeyHex: deviceKeyHex,
  currentXpub: currentXpub,
);

/// Remove an xpub slot by MFP from a XpubKey-protected wallet.
/// Fails if it would leave the wallet with zero slots.
Future<void> removeXpubSlot({
  required String walletPath,
  required String mfp,
}) => RustLib.instance.api.crateApiWalletRemoveXpubSlot(
  walletPath: walletPath,
  mfp: mfp,
);

/// List all registered xpub slots for a XpubKey-protected wallet, including derivation hints.
Future<List<APIXpubSlot>> listXpubSlots({required String walletPath}) =>
    RustLib.instance.api.crateApiWalletListXpubSlots(walletPath: walletPath);

/// Add a biometric slot to a UserPassword or XpubKey wallet.
///
/// The Flutter layer generates a random 32-byte `biometric_key_hex` and stores it
/// in the platform's secure storage (gated behind `local_auth`). This function wraps
/// the wallet data key with that random key and records the slot in the `.meta` sidecar.
///
/// Returns the slot ID (UUID v4) that the Flutter layer must use as the keystore key name.
/// `current_credential` is the existing password/xpub needed to derive the data key.
Future<String> addBiometricSlot({
  required String walletPath,
  required String deviceKeyHex,
  String? currentCredential,
  required String biometricKeyHex,
}) => RustLib.instance.api.crateApiWalletAddBiometricSlot(
  walletPath: walletPath,
  deviceKeyHex: deviceKeyHex,
  currentCredential: currentCredential,
  biometricKeyHex: biometricKeyHex,
);

/// Remove a biometric slot by ID from a UserPassword or XpubKey wallet.
Future<void> removeBiometricSlot({
  required String walletPath,
  required String biometricId,
}) => RustLib.instance.api.crateApiWalletRemoveBiometricSlot(
  walletPath: walletPath,
  biometricId: biometricId,
);

/// List all registered biometric slot IDs for this wallet.
/// Returns an empty list for DeviceKey wallets.
Future<List<APIBiometricSlot>> listBiometricSlots({
  required String walletPath,
}) => RustLib.instance.api.crateApiWalletListBiometricSlots(
  walletPath: walletPath,
);

/// Returns true if the wallet has at least one registered biometric slot.
Future<bool> walletHasBiometricSlots({required String walletPath}) => RustLib
    .instance
    .api
    .crateApiWalletWalletHasBiometricSlots(walletPath: walletPath);

/// Validate a mnemonic phrase and return its MFP without storing anything.
Future<APIHotKeyInfo> validateMnemonic({
  required String mnemonic,
  String? passphrase,
  required APINetwork network,
}) => RustLib.instance.api.crateApiWalletValidateMnemonic(
  mnemonic: mnemonic,
  passphrase: passphrase,
  network: network,
);

/// Validate a master xprv (depth-0) and return its MFP without storing anything.
Future<APIHotKeyInfo> validateXprv({required String xprv}) =>
    RustLib.instance.api.crateApiWalletValidateXprv(xprv: xprv);

/// `derivation_path` may include or omit the leading `m/`.
/// Returns a string suitable for use in a Bitcoin descriptor.
Future<String> deriveKeyspec({
  required String mnemonic,
  String? passphrase,
  required String derivationPath,
  required APINetwork network,
}) => RustLib.instance.api.crateApiWalletDeriveKeyspec(
  mnemonic: mnemonic,
  passphrase: passphrase,
  derivationPath: derivationPath,
  network: network,
);

/// Derive a public keyspec `[mfp/path]xpub` from a master xprv and derivation path.
///
/// `xprv_str` must be a depth-0 master key.
/// `derivation_path` may include or omit the leading `m/`.
Future<String> deriveKeyspecFromXprv({
  required String xprvStr,
  required String derivationPath,
}) => RustLib.instance.api.crateApiWalletDeriveKeyspecFromXprv(
  xprvStr: xprvStr,
  derivationPath: derivationPath,
);

/// Store a mnemonic as a signing key for a project.
///
/// Validates the mnemonic, computes the MFP, and persists it in the
/// shared `project_seeds.db` (SQLCipher, device-key protected).
APIHotKeyInfo addProjectMnemonicKey({
  required String appSupportDir,
  required PlatformInt64 projectId,
  required String mnemonic,
  String? passphrase,
  required APINetwork network,
  required String deviceKeyHex,
}) => RustLib.instance.api.crateApiWalletAddProjectMnemonicKey(
  appSupportDir: appSupportDir,
  projectId: projectId,
  mnemonic: mnemonic,
  passphrase: passphrase,
  network: network,
  deviceKeyHex: deviceKeyHex,
);

/// Store a master xprv (depth-0 only) as a signing key for a project.
APIHotKeyInfo addProjectXprvKey({
  required String appSupportDir,
  required PlatformInt64 projectId,
  required String xprv,
  required String deviceKeyHex,
}) => RustLib.instance.api.crateApiWalletAddProjectXprvKey(
  appSupportDir: appSupportDir,
  projectId: projectId,
  xprv: xprv,
  deviceKeyHex: deviceKeyHex,
);

/// List all project signing keys (never exposes the seed itself).
List<APIHotKeyInfo> listProjectHotKeys({
  required String appSupportDir,
  required PlatformInt64 projectId,
  required String deviceKeyHex,
}) => RustLib.instance.api.crateApiWalletListProjectHotKeys(
  appSupportDir: appSupportDir,
  projectId: projectId,
  deviceKeyHex: deviceKeyHex,
);

/// Remove a project signing key by MFP.
void deleteProjectHotKey({
  required String appSupportDir,
  required PlatformInt64 projectId,
  required String mfp,
  required String deviceKeyHex,
}) => RustLib.instance.api.crateApiWalletDeleteProjectHotKey(
  appSupportDir: appSupportDir,
  projectId: projectId,
  mfp: mfp,
  deviceKeyHex: deviceKeyHex,
);

/// Reveal the stored seed phrase or xprv for a project signing key.
///
/// Call only after showing an appropriate warning to the user.
String revealProjectSeed({
  required String appSupportDir,
  required PlatformInt64 projectId,
  required String mfp,
  required String deviceKeyHex,
}) => RustLib.instance.api.crateApiWalletRevealProjectSeed(
  appSupportDir: appSupportDir,
  projectId: projectId,
  mfp: mfp,
  deviceKeyHex: deviceKeyHex,
);

/// Copy all signing keys from a project's encrypted seeds DB into a wallet.
///
/// Returns the number of keys copied.
int copyProjectKeysToWallet({
  required String appSupportDir,
  required PlatformInt64 projectId,
  required String walletPath,
  required String deviceKeyHex,
  String? walletPassword,
}) => RustLib.instance.api.crateApiWalletCopyProjectKeysToWallet(
  appSupportDir: appSupportDir,
  projectId: projectId,
  walletPath: walletPath,
  deviceKeyHex: deviceKeyHex,
  walletPassword: walletPassword,
);

/// Strip non-essential fields from a PSBT to reduce QR code size.
///
/// Returns the BIP39 English wordlist (2048 words, alphabetically sorted).
List<String> bip39Wordlist() =>
    RustLib.instance.api.crateApiWalletBip39Wordlist();

/// Returns all BIP39 words that, when appended to `partial_words`, produce a valid
/// mnemonic of a supported BIP39 length (12, 15, 18, 21, or 24 words) and start
/// with `prefix`.
///
/// `partial_words` must contain exactly (target_length - 1) words, e.g. 11 words
/// for a 12-word mnemonic. Returns an empty list if the count is wrong.
List<String> bip39ValidLastWords({
  required String partialWords,
  required String prefix,
}) => RustLib.instance.api.crateApiWalletBip39ValidLastWords(
  partialWords: partialWords,
  prefix: prefix,
);

/// Converts raw BIP39 entropy bytes to a mnemonic phrase.
///
/// Accepts entropy of 16, 20, 24, 28, or 32 bytes (for 12, 15, 18, 21, or
/// 24-word mnemonics respectively). Computes the checksum internally.
/// Used to decode Compact SeedQR payloads, which store only entropy bytes.
String bip39EntropyToMnemonic({required List<int> entropy}) =>
    RustLib.instance.api.crateApiWalletBip39EntropyToMnemonic(entropy: entropy);

/// Generates a fresh BIP39 mnemonic of `word_count` words (12 or 24).
///
/// Entropy pipeline (defense-in-depth, matching SeedSigner/Trezor practice
/// rather than feeding raw OS RNG into BIP39 directly):
/// 1. Sample 64 bytes from the OS CSPRNG (`OsRng`) — always 64, regardless of
///    final word count, so the RNG pool is consumed maximally.
/// 2. SHA-256 the 64-byte buffer → 32 bytes of normalized entropy.
/// 3. Truncate to 16 bytes for 12 words, or use all 32 bytes for 24 words.
/// 4. Hand the entropy to BIP39 (`Mnemonic::from_entropy`), which appends the
///    standard 4-bit / 8-bit checksum.
///
/// All intermediate buffers are zeroized before return.
String generateMnemonic({required int wordCount}) =>
    RustLib.instance.api.crateApiWalletGenerateMnemonic(wordCount: wordCount);

/// Removes `non_witness_utxo` (full previous transaction, ~200-500 B per input)
/// when `witness_utxo` is present (segwit/taproot inputs), plus all `proprietary`
/// and `unknown` fields from global, inputs, and outputs.
///
/// The stored PSBT is never modified — this is only used for QR export.
Future<String> stripPsbtForHw({required String psbtBase64}) =>
    RustLib.instance.api.crateApiWalletStripPsbtForHw(psbtBase64: psbtBase64);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<APIWallet>>
abstract class ApiWallet implements RustOpaqueInterface {
  /// Store a compact Bitcoin message signature (QR Variant A — standard HW message signing).
  ///
  /// `sig_b64` must be a base64-encoded 65-byte compact signature as produced
  /// by most hardware wallets' native "sign message" feature.
  APIDescriptorSig addDescriptorSigFromMessage({
    required String mfp,
    required String xpubEntry,
    required String sigB64,
  });

  /// Import a mnemonic phrase as a signing key. Validates the words, computes
  /// the MFP, and stores the seed in the encrypted wallet database.
  APIHotKeyInfo addMnemonicKey({required String mnemonic, String? passphrase});

  /// Import a master xprv (depth=0 only) as a signing key.
  APIHotKeyInfo addXprvKey({required String xprv});

  /// Analyze partial signatures present in a PSBT.
  ///
  /// Returns signing status per MFP (must sign every input to count as signed)
  /// and whether all inputs are already finalized.
  Future<APIPsbtAnalysis> analyzePsbt({
    required String psbtBase64,
    required List<String> mfps,
  });

  /// Merge externally-signed PSBTs (HW device output / QR import /
  /// envelope) into the matching children of a plan. Each entry must
  /// reference a child of `plan_id`; entries whose `psbt_id` is not in
  /// the plan are reported under `failed`. Merge errors are also
  /// reported per-row and never abort the batch.
  ///
  /// The plan status is unchanged. Children whose ids do not appear in
  /// `signed` are left untouched and are absent from both
  /// `signed_ids` and `failed` (mirroring the batch contract — the
  /// report covers the batch the caller submitted, not the whole plan).
  APIBatchSignReport applySpacedPlanSignedPsbts({
    required PlatformInt64 planId,
    required List<APISignedChildPsbt> signed,
  });

  String get path;

  set path(String path);

  /// Snapshot of the auto-broadcast queue, for the background scheduler.
  ///
  /// Returns the number of pending PSBTs, the minimum absolute `nLockTime`
  /// among them (if any has one set), and the current tip height as known
  /// to the wallet. Cheap: one SQL + a base64+PSBT deserialize per row.
  ///
  /// PSBTs locked only by a BIP68 relative timelock contribute `None` to
  /// `min_locktime` — the scheduler treats those as "check again later"
  /// via its 24h heartbeat ceiling.
  APIAutoBroadcastSummary autoBroadcastSummary();

  /// Finalize the PSBT, broadcast via Electrum, and delete the local record.
  ///
  /// Returns the broadcast txid on success.
  Future<String> broadcastPsbt({
    required PlatformInt64 id,
    required String electrumUrl,
  });

  /// Cancel an active plan: discard every child PSBT (auto_broadcast
  /// vanishes with the row) and move the plan to `CANCELLED` for
  /// history. Errors when the plan is already terminal.
  void cancelSpacedPlan({required PlatformInt64 planId});

  /// Change the wallet's encryption protection scheme.
  ///
  /// Generates a fresh SQLCipher data key and re-encrypts the database
  /// in-place via `PRAGMA rekey` — the existing connection stays open and
  /// operational throughout. The `.meta` sidecar is then rewritten with the
  /// new scheme. No export/import required.
  ///
  /// After this call the Dart layer must update its credential cache:
  /// - `DeviceKey` → evict any cached password (automatic unlock).
  /// - `UserPassword` → cache `new_password`.
  /// - `XpubKey` → evict any cached password (user enters xpub on next open).
  Future<void> changeProtection({
    required String deviceKeyHex,
    required APIProtectionType newProtectionType,
    String? newPassword,
    required APISecurityLevel securityLevel,
  });

  /// Check whether an on-chain backup already exists for this wallet.
  ///
  /// Uses the already-open wallet connection — no key derivation or DB re-open.
  /// Queries each participant's anchor address on Electrum, then finds the commit TX
  /// whose outputs cover **all** anchor addresses (unique fingerprint of this multisig).
  Future<WalletBackupStatus> checkBackupHealth({required String electrumUrl});

  /// Delete all stored fiat prices (called when the user changes fiat currency).
  Future<void> clearFiatPrices();

  /// Wipe every spaced-plan auto-label tagged with this `plan_id` on
  /// this wallet's DB. The cubit calls this on the destination
  /// wallet handle on cancel, mirroring the source-side cleanup in
  /// [`Self::cancel_spaced_plan`]. Explicit user labels are not
  /// affected (the sweep keys on `source_entity`, which is NULL for
  /// user labels).
  void clearSpacedPlanLabels({required PlatformInt64 planId});

  /// Combine partial signatures from two PSBTs of the same transaction.
  ///
  /// Both PSBTs must refer to the same unsigned tx. Returns the merged PSBT
  /// in base64. Used by the on-chain backup flow, which signs an ephemeral
  /// PSBT across multiple keys without storing it in the wallet DB.
  String combinePsbts({required String aBase64, required String bBase64});

  /// Verify every child PSBT of a `DRAFT` plan is fully signed and arm it
  /// for auto-broadcast.
  ///
  /// A child counts as "signed" when either its PSBT is already finalised
  /// (BDK's `final_script_witness` / `final_script_sig` present) or at
  /// least `threshold` MFPs have a partial signature on every input
  /// (driven by `analyze_psbt` so the check matches what the UI shows).
  ///
  /// Reports the per-PSBT status instead of erroring on the partial case
  /// so the cubit can render the missing-signers UI without parsing the
  /// error string. The plan transition to `SIGNED` only happens when
  /// `committed == true`.
  ///
  /// Idempotent on a plan already in `SIGNED`: no state change, returns a
  /// report with `committed == true` and zero unsigned ids.
  APICommitSpacedPlanReport commitSpacedPlan({required PlatformInt64 planId});

  /// Complete a descriptor signature from a signed BIP322 PSBT (BB02 or QR Variant B).
  ///
  /// Extracts the ECDSA signature from the PSBT's `partial_sigs`, verifies it,
  /// and persists it as `"bip322"`.
  APIDescriptorSig completeDescriptorSigFromPsbt({
    required String mfp,
    required String xpubEntry,
    required String signedPsbtB64,
  });

  /// Compute on-chain backup parameters from the already-open wallet.
  ///
  /// Pure local computation — no network, no DB re-open.
  /// Returns fee-size estimates and anchor addresses for live fee breakdown in Flutter.
  Future<BackupParams> computeBackupParams();

  /// Build an unsigned PSBT with optional coin control and spend-path selection.
  ///
  /// * `recipients`           — one or more outputs; each has an address and amount.
  /// * `max_recipient_index`  — if `Some(i)`, recipient at index `i` gets the wallet
  ///   remainder (drain_to); its `amount_sat` field is ignored.
  ///   Pass `None` when every amount is explicit.
  /// * `selected_utxos` — if non-empty, only those coins are used.
  ///   Empty = BDK automatic coin selection.
  /// * `policy_path`    — spend-path branch selections from [APISpendPath.policyPath].
  /// * `spend_path_id`  — rust_id of the selected spend path (stored for reference).
  /// * `threshold`      — required signatures (from the spend path).
  /// * `mfps`           — master fingerprints of keys in the spend path.
  /// * `nlocktime_delta_blocks` — optional delay added on top of
  ///   `max(tip_height, abs_timelock)`. The resulting absolute height becomes
  ///   the transaction's nLockTime, so the tx cannot be broadcast until that
  ///   height is reached. Capped at `MAX_NLOCKTIME_DELTA_BLOCKS` (~1 year).
  APIPsbtInfo createPsbt({
    required List<APIRecipient> recipients,
    int? maxRecipientIndex,
    required BigInt feeAbsoluteSat,
    required List<APICoinControl> selectedUtxos,
    required List<APIPolicyPath> policyPath,
    required int spendPathId,
    required int threshold,
    required List<String> mfps,
    int? nlocktimeDeltaBlocks,
  });

  /// Delete a stored descriptor signature.
  void deleteDescriptorSig({required String mfp});

  /// Remove a hot signing key by MFP.
  void deleteHotKey({required String mfp});

  /// Delete a saved PSBT by id.
  void deletePsbt({required PlatformInt64 id});

  /// Derive the WIF-encoded private key for a specific address in this wallet.
  ///
  /// Looks up the address in the wallet's SPK index to find its keychain and
  /// derivation index, then combines that with the account path extracted from
  /// the wallet descriptor and the stored seed to produce the leaf private key,
  /// serialized in Wallet Import Format (WIF).
  ///
  /// Only valid for single-sig hot wallets. Call only after showing an
  /// appropriate security disclaimer — WIF exposes a spendable private key.
  String deriveAddressWif({required String address, required String mfp});

  /// Export all explicit (non-auto) labels to BIP-329 JSONL format.
  List<String> exportBip329();

  /// Broadcast a signed TX_COMMIT and emit TX_REVEAL to complete the backup.
  ///
  /// Anchor keys are derived from the wallet's xpubs — no seed material needed.
  Future<OnchainBackupResult> finalizeBackup({
    required String signedCommitPsbtBase64,
    required String vaultTapscriptHex,
    required BigInt revealFeeSat,
    required String electrumUrl,
  });

  /// Return full detail for an address: the address plus its unspent UTXOs.
  Future<APIAddressDetails> getAddressDetails({required String address});

  /// Return all currently revealed addresses for the given keychain, sorted by index ascending.
  /// Balance is the sum of all unspent outputs currently controlled by each address.
  Future<List<APIAddress>> getAddresses({required APIKeychain keychain});

  /// Return the cached balance (no network call).
  Future<APIBalance> getBalance();

  /// Return the aggregate fee info for the full unconfirmed ancestor package of the given
  /// parent txids. Performs a BFS through the tx graph to collect all unconfirmed ancestors
  /// transitively (parents, grandparents, …), summing their fees and vsizes to compute the
  /// effective package fee rate that miners use when evaluating CPFP.
  ///
  /// `parent_txids` should be the txids of the unconfirmed UTXOs being spent as child inputs.
  Future<APICpfpInfo> getCpfpInfo({required List<String> parentTxids});

  /// Return all stored BTC prices for `currency` as a list of (txid, price) pairs.
  Future<List<APIFiatPrice>> getFiatPrices({required String currency});

  /// Read wallet metadata from the open connection (no file re-open).
  Future<APIWalletInfo> getInfo();

  /// Return all key labels (mfp → label).
  Future<List<APIKeyLabel>> getKeyLabels();

  /// Return all spend-path labels (rust_id → label).
  Future<List<APIPathLabel>> getPathLabels();

  /// Return RBF replacement constraints for a mempool tx spending one of our UTXOs.
  /// Fetches parent txs from Electrum when fee cannot be determined from the wallet graph.
  Future<APIRbfInfo> getRbfInfo({required String spendingTxid});

  /// Fetch one plan plus the children still in `unsigned_txs`. Errors
  /// when the plan does not exist (use the plan_id returned by
  /// `plan_spaced_txs` / `list_spaced_plans`).
  APISpacedPlanDetail getSpacedPlan({required PlatformInt64 planId});

  /// Return the current best block height from the local chain (0 if not yet synced).
  Future<int> getTipHeight();

  /// Return a paginated page of transactions, sorted newest-first (no network call).
  Future<APITransactionPage> getTransactions({
    required int page,
    required int pageSize,
  });

  /// Return full detail for a transaction: the tx plus related UTXOs, input addresses,
  /// and output addresses. External input transactions not in BDK's graph are fetched
  /// from Electrum (using the URL stored from the last sync).
  Future<APITxDetails> getTxDetails({required String txid});

  /// Return transactions that have no stored fiat price for `currency`.
  Future<List<APITxMissingFiat>> getTxidsMissingFiat({
    required String currency,
  });

  /// Return full detail for a UTXO: the UTXO plus the explicit labels of its cluster peers.
  Future<APIUtxoDetails> getUtxoDetails({
    required String txid,
    required int vout,
  });

  /// Return all unspent outputs (UTXOs / coins), sorted by value descending.
  Future<List<APIUtxo>> getUtxos();

  /// True when this wallet has a plan in any active state
  /// (DRAFT / SIGNED / RUNNING). Used by the cubit to gate the
  /// "Plan spaced transactions…" menu entry.
  bool hasActiveSpacedPlan();

  /// Import labels from BIP-329 JSONL. Sets all as explicit, then re-propagates.
  /// Malformed lines and unknown types are silently skipped.
  void importBip329({required List<String> lines});

  /// Import a PSBT (base64) from an external source.
  ///
  /// If a record with the same unsigned txid already exists, the signatures are
  /// merged and the existing record is updated (`was_merged = true`).
  /// Otherwise a new record is created with metadata extracted from the PSBT.
  Future<APIImportPsbtResult> importPsbt({required String psbtBase64});

  /// Return all stored descriptor signatures, each with current validity status.
  List<APIDescriptorSig> listDescriptorSigs();

  /// List all hot signing keys stored in this wallet (never exposes the seed).
  APIHotKeyList listHotKeys();

  /// Return all saved unsigned PSBTs for this wallet, newest-first.
  Future<List<APIPsbtInfo>> listPsbts();

  /// List every plan ever created in this wallet, newest first.
  /// Terminal-state plans are kept for history (a CANCELLED row tells
  /// the user why their "Plan…" menu was greyed out earlier).
  List<APISpacedPlanDetail> listSpacedPlans();

  /// Merge partial signatures from a signed PSBT into the stored one.
  ///
  /// The signed PSBT must refer to the same transaction (same inputs/outputs).
  /// Returns the updated info.
  APIPsbtInfo mergePsbt({
    required PlatformInt64 id,
    required String signedPsbtBase64,
  });

  /// Build a spaced TX plan over every confirmed UTXO of this wallet.
  ///
  /// Persists a new `tx_plans` row (status `DRAFT`) and one
  /// `unsigned_txs` row per non-dropped intent. Returns a summary the
  /// UI can render directly — no extra reads needed.
  ///
  /// Errors out when:
  ///   - this wallet already has an active plan;
  ///   - the planner params are invalid;
  ///   - no confirmed UTXOs are eligible;
  ///   - `dst_addresses.len() < eligible_utxo_count`;
  ///   - every eligible UTXO yields a dust output at the chosen feerate
  ///     range (rolls the plan row back so the user can retry without
  ///     a separate cancel call).
  APISpacedPlanSummary planSpacedTxs({required APISpacedPlanParams params});

  /// Build the TX_COMMIT PSBT for an on-chain descriptor backup.
  ///
  /// Uses the live wallet (no extra connection). The PSBT is NOT stored in the
  /// wallet's `unsigned_txs` table — it is returned to Flutter to be signed and
  /// then passed directly to `finalize_backup`.
  ///
  /// `min_fee_rate` is the network's minimum relay fee rate. TX_COMMIT uses it
  /// as its fee rate (below relay standard so it cannot be mined alone).
  /// TX_REVEAL's fee is guaranteed to be at least `reveal_vbytes * min_fee_rate`.
  Future<OnchainBackupPsbt> prepareBackupPsbt({
    required List<String> utxoTxids,
    required List<int> utxoVouts,
    required double feeRateSatPerVb,
    required double minFeeRate,
    required List<APIPolicyPath> policyPath,
    required int spendPathId,
  });

  /// Build the BB02-BIP322 PSBT to send to the hardware wallet for signing.
  ///
  /// After calling this, pass the returned PSBT base64 to `hw_sign_psbt`
  /// with descriptor `wsh(pk({xpub_entry}/<0;1>/*))`  and then call
  /// `complete_descriptor_sig_from_psbt` with the signed result.
  ///
  /// Also returns the temporary descriptor string required for BB02 registration.
  APIPrepareDescriptorSigPsbt prepareDescriptorSigPsbt({required String mfp});

  /// Bundle every pending child PSBT of a plan together with plan-level
  /// signing context (descriptor, threshold, key-change map). The cubit
  /// uses this in a single call so the batch sign UI never has to
  /// re-open the wallet per PSBT.
  ///
  /// The plan must be in `DRAFT` or `SIGNED`. `SIGNED` is allowed so the
  /// UI can re-render the batch after a partial-sign attempt without
  /// reverting to DRAFT.
  ///
  /// Empty plans (no pending children) return an error so the caller
  /// surfaces "nothing to sign" explicitly instead of an empty list.
  APISpacedPlanSigningBundle prepareSpacedPlanPsbts({
    required PlatformInt64 planId,
  });

  /// Preview the result of building an unsigned tx — fee, change, send, weight — without
  /// constructing or persisting a PSBT. Mirrors `create_psbt` inputs so the UI can show
  /// what BDK would actually do, and so a subsequent `create_psbt` produces matching numbers.
  ///
  /// Exactly one of `fee_rate_sat_per_vb` / `fee_absolute_sat` must be `Some`.
  ///
  /// `rbf_infos` (optional) lets the preview compute `rbf_min_fee_sats` — the BIP-125
  /// Rule 4 / PaysForRBF threshold for the *new* tx vsize. Pass the same RBF infos the UI
  /// already fetched per conflicting mempool tx; pass empty when not replacing anything.
  ///
  /// Insufficient-funds is returned as a flag in the preview rather than as an error, so
  /// the screen can render gracefully while the user is still typing amounts.
  APITxPreview previewPsbt({
    required List<APIRecipient> recipients,
    int? maxRecipientIndex,
    double? feeRateSatPerVb,
    BigInt? feeAbsoluteSat,
    required List<APICoinControl> selectedUtxos,
    required List<APIPolicyPath> policyPath,
    required int spendPathId,
    required List<APIRbfInfo> rbfInfos,
  });

  /// Repropagate all existing explicit labels to their related entities.
  /// Useful after imports or migrations. Clears all auto labels first.
  void repropagateAllLabels();

  /// Force a full scan regardless of sync history (re-discovers all addresses).
  Future<void> rescan({required String electrumUrl});

  /// Reveal the stored seed phrase or xprv for a hot signing key.
  ///
  /// The SQLCipher layer already protects this data at rest; this function
  /// exposes it in plaintext for display purposes only. Call only when the
  /// user explicitly requests it and after showing an appropriate disclaimer.
  String revealHotKey({required String mfp});

  /// Reveal `count` new addresses for the given keychain beyond those already revealed,
  /// then persist the wallet. Returns the new total number of revealed addresses.
  int revealMoreAddresses({required APIKeychain keychain, required int count});

  /// Persist a label for an address. Pass an empty string to remove it.
  /// Automatically propagates to related entities (transactions and UTXOs).
  /// Clearing an inherited (auto) label is a no-op.
  void setAddressLabel({required String address, required String label});

  /// Persist a label for a coin (UTXO) by outpoint. Pass an empty string to remove it.
  /// Automatically propagates to related entities (transaction and address).
  /// Clearing an inherited (auto) label is a no-op.
  void setCoinLabel({
    required String txid,
    required int vout,
    required String label,
  });

  /// Store the Electrum URL so it can be used by detail queries (e.g. fetching
  /// unknown input transactions). Call this before sync if you want it available
  /// immediately without waiting for sync to complete.
  void setElectrumUrl({required String url});

  /// Persist a label for a key by master fingerprint. Pass an empty string to remove it.
  void setKeyLabel({required String mfp, required String label});

  /// Persist a label for a spend path by rust_id. Pass an empty string to remove it.
  void setPathLabel({required int rustId, required String label});

  /// Enable or disable auto-broadcast for a saved PSBT.
  ///
  /// When enabled, the wallet will broadcast this PSBT automatically as
  /// soon as its timelock matures (checked after each successful sync).
  /// Persists in the wallet database, so the flag survives app restarts.
  APIPsbtInfo setPsbtAutoBroadcast({
    required PlatformInt64 id,
    required bool enabled,
  });

  /// Set or clear the label for a saved PSBT. Pass an empty string to clear.
  APIPsbtInfo setPsbtLabel({required PlatformInt64 id, required String label});

  /// Seed this wallet's `address_labels` with the auto-labels of a
  /// spaced plan executed by *another* wallet. The cubit calls this
  /// on the destination wallet handle right after a `Migrate` plan
  /// is created — the source wallet can't reach the destination DB,
  /// so labels would otherwise be lost on receive.
  ///
  /// Each entry is tagged with the canonical
  /// `spaced_plan:{plan_id}:coin:{src_txid}:{src_vout}` source so the
  /// matching call to [`Self::clear_spaced_plan_labels`] can wipe
  /// them on cancel. Entries whose address already carries an
  /// explicit user label are skipped (the planner must never
  /// overwrite user input).
  ///
  /// Stored with `is_auto = false`: the user expects migrated coins
  /// on the destination wallet to look like *their own* labelled
  /// addresses, not as auto-inherited ones. The `source_entity` tag
  /// is still set so cancel cleanup can find and wipe them.
  void setSpacedPlanAddressLabels({
    required List<APISpacedPlanAddressLabel> entries,
  });

  /// Persist a label for a transaction. Pass an empty string to remove it.
  /// Automatically propagates to related entities (addresses and UTXOs).
  /// Clearing an inherited (auto) label is a no-op.
  void setTxLabel({required String txid, required String label});

  /// Sign the TX_COMMIT PSBT for an on-chain backup using a stored hot key.
  ///
  /// The PSBT is not stored in the wallet DB — it is ephemeral and returned
  /// directly to Flutter for passing to `finalize_backup`.
  String signBackupPsbt({required String psbtBase64, required String mfp});

  /// Sign the descriptor with a stored HotKey (mnemonic or xprv).
  ///
  /// Derives the root xprv from the seed entry for `mfp`, signs the
  /// canonical descriptor message via the BB02-BIP322 adapted protocol,
  /// and persists the signature.
  APIDescriptorSig signDescriptorWithHotkey({required String mfp});

  /// Sign a stored PSBT using the hot key identified by `mfp`.
  ///
  /// Only the signer for the given master fingerprint is loaded, so BDK can
  /// never accidentally sign with a key the user did not intend. The PSBT is
  /// **never auto-finalized** (`try_finalize: false`) — the user explicitly
  /// controls finalization, which prevents premature finalization in multisig
  /// or complex Taproot setups where BDK might otherwise finalize on the first
  /// satisfied threshold.
  ///
  /// Returns the updated [`APIPsbtInfo`] with the partial signatures added.
  APIPsbtInfo signPsbtWithKey({
    required PlatformInt64 psbtId,
    required String mfp,
  });

  /// Sign every pending child PSBT of a plan with the hot key
  /// identified by `mfp`. Each row is signed in its own critical
  /// section by reusing [`sign_psbt_with_key`]; partial failures
  /// **do not** roll back already-signed children — the failed list
  /// is returned so the UI can offer a retry.
  ///
  /// The plan must be in `DRAFT` or `SIGNED`. The plan status is
  /// **not** mutated — `commit_spaced_plan` remains the only state
  /// transition. An empty plan errors out so the caller surfaces
  /// "nothing to sign" instead of an empty `signed_ids`.
  APIBatchSignReport signSpacedPlanWithHotKey({
    required PlatformInt64 planId,
    required String mfp,
  });

  /// Open a reactive Electrum subscription for this wallet.
  ///
  /// Subscribes to block headers + all revealed SPKs of the wallet.
  /// Emits `true` through `sink` whenever a notification arrives
  /// (new block or scriptpubkey activity). The caller should trigger
  /// a sync on each event.
  ///
  /// Returns immediately; the listener runs on a blocking thread.
  /// The loop exits when the Dart sink is closed (StreamSubscription.cancel).
  Stream<bool> startSubscription({required String electrumUrl});

  /// Store (or replace) the BTC price in `currency` at the time of a transaction.
  Future<void> storeFiatPrice({
    required String txid,
    required String currency,
    required double btcPrice,
  });

  /// Sync with Electrum, persist, and update last_synced_at.
  ///
  /// Uses full_scan on first sync (last_synced_at is None) to discover all addresses
  /// up to the stop gap. Uses incremental sync on subsequent calls to only check
  /// already-revealed script pubkeys, which is much faster.
  Future<void> sync_({required String electrumUrl});

  /// Attempt to broadcast every PSBT flagged for auto-broadcast whose
  /// timelock has matured against the wallet's current chain tip.
  ///
  /// Skips silently (no entry in the returned `Vec`) for PSBTs still locked
  /// or awaiting a sync. Emits one entry per attempt that produced an
  /// outcome — either a successful broadcast (with txid) or a broadcast
  /// failure (with error message). On a successful broadcast the PSBT row
  /// is deleted and any label is propagated to the transaction.
  ///
  /// Designed to be invoked after each successful Electrum sync (one block
  /// = one natural retry tick). Safe to call when no PSBTs are pending.
  Future<List<APIAutoBroadcastResult>> tryAutoBroadcastDue({
    required String electrumUrl,
  });

  /// Re-verify all stored descriptor signatures and return updated statuses.
  ///
  /// Intentionally identical to [`list_descriptor_sigs`]: verification is
  /// always performed eagerly on every read (see [`verify_one_sig`]).  The
  /// distinction exists at the Flutter/cubit layer, where calling this method
  /// sets `hasVerified = true` in the UI state so that "verified" / "invalid"
  /// labels are shown instead of the neutral "signed" label.
  List<APIDescriptorSig> verifyDescriptorSigs();

  /// Return the network for this wallet.
  APINetwork walletNetwork();
}

/// A key label entry returned from [APIWallet::get_key_labels].
class APIKeyLabel {
  final String mfp;
  final String label;

  const APIKeyLabel({required this.mfp, required this.label});

  @override
  int get hashCode => mfp.hashCode ^ label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIKeyLabel &&
          runtimeType == other.runtimeType &&
          mfp == other.mfp &&
          label == other.label;
}

/// A spend-path label entry returned from [APIWallet::get_path_labels].
class APIPathLabel {
  final int rustId;
  final String label;

  const APIPathLabel({required this.rustId, required this.label});

  @override
  int get hashCode => rustId.hashCode ^ label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIPathLabel &&
          runtimeType == other.runtimeType &&
          rustId == other.rustId &&
          label == other.label;
}
