// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'model.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_psbt_label_to_tx`, `build_valid_outpoints`, `cascade_delete_label`, `clear_source_labels`, `create_electrum_client`, `create_raw_electrum_client`, `derive_and_format_keyspec`, `extract_xpub_derivation_map`, `extract_xpub_mfp_map`, `is_psbt_self_transfer`, `lock_wallet`, `propagate_label`, `protection_for_path`, `psbt_effective_label`, `psbt_from_base64`, `psbt_max_utxo_conf_height`, `psbt_to_base64`, `resolve_label`, `row_to_api_info`, `row_to_api_psbt_loaded`, `row_to_api_psbt`, `set_address_if_none`, `set_coin_if_none`, `set_tx_if_none`, `source_entity_id`, `xpub_slots_from_descriptor`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EntityType`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `eq`, `fmt`

/// Return all wallets found in wallets_dir, sorted newest-first.
Future<List<APIWalletInfo>> listWallets({
  required String walletsDir,
  required String encryptionKeyHex,
}) => RustLib.instance.api.crateApiWalletListWallets(
  walletsDir: walletsDir,
  encryptionKeyHex: encryptionKeyHex,
);

/// Create a new wallet .db file and return its info.
Future<APIWalletInfo> createWallet({
  required String walletsDir,
  required String name,
  required String descriptor,
  required APINetwork network,
  required String deviceKeyHex,
  required APIProtectionType protectionType,
  String? password,
  required APISecurityLevel securityLevel,
}) => RustLib.instance.api.crateApiWalletCreateWallet(
  walletsDir: walletsDir,
  name: name,
  descriptor: descriptor,
  network: network,
  deviceKeyHex: deviceKeyHex,
  protectionType: protectionType,
  password: password,
  securityLevel: securityLevel,
);

/// Read metadata from an existing wallet file.
/// Pass `password` for UserPassword wallets, `None` for DeviceKey wallets.
Future<APIWalletInfo> getWalletInfo({
  required String walletPath,
  required String deviceKeyHex,
  String? password,
}) => RustLib.instance.api.crateApiWalletGetWalletInfo(
  walletPath: walletPath,
  deviceKeyHex: deviceKeyHex,
  password: password,
);

/// Rename a wallet (updates wallet_info.name in the file).
/// Pass `password` for UserPassword wallets, `None` for DeviceKey wallets.
Future<void> renameWallet({
  required String walletPath,
  required String name,
  required String deviceKeyHex,
  String? password,
}) => RustLib.instance.api.crateApiWalletRenameWallet(
  walletPath: walletPath,
  name: name,
  deviceKeyHex: deviceKeyHex,
  password: password,
);

/// Delete a wallet's .db, .db-wal, .db-shm, and .db.meta files.
Future<void> deleteWallet({required String walletPath}) =>
    RustLib.instance.api.crateApiWalletDeleteWallet(walletPath: walletPath);

/// Open a wallet once and hold the live handle for repeated operations.
///
/// Reads descriptor and network from wallet_info inside the encrypted file,
/// then opens the BDK wallet in a single SQLite connection.
/// Pass `password` for UserPassword wallets, `None` for DeviceKey wallets.
Future<ApiWallet> openWallet({
  required String walletPath,
  required String deviceKeyHex,
  String? password,
}) => RustLib.instance.api.crateApiWalletOpenWallet(
  walletPath: walletPath,
  deviceKeyHex: deviceKeyHex,
  password: password,
);

/// Check whether a wallet requires a credential (password or xpub) to open.
Future<bool> walletRequiresPassword({required String walletPath}) => RustLib
    .instance
    .api
    .crateApiWalletWalletRequiresPassword(walletPath: walletPath);

/// Check whether a wallet is XpubKey protected.
Future<bool> walletRequiresXpub({required String walletPath}) => RustLib
    .instance
    .api
    .crateApiWalletWalletRequiresXpub(walletPath: walletPath);

/// Return the network stored in the wallet meta sidecar without opening the DB.
/// Returns None for DeviceKey wallets or when the meta cannot be read.
Future<String?> getWalletNetworkHint({required String walletPath}) => RustLib
    .instance
    .api
    .crateApiWalletGetWalletNetworkHint(walletPath: walletPath);

/// Add a new xpub slot to a XpubKey-protected wallet.
/// `current_xpub` is any already-registered xpub (used to derive the data key).
/// `new_mfp` and `new_xpub` identify the slot to add.
/// Derivation is looked up from the wallet descriptor automatically.
Future<void> addXpubSlot({
  required String walletPath,
  required String newMfp,
  required String newXpub,
  required String deviceKeyHex,
  required String currentXpub,
}) => RustLib.instance.api.crateApiWalletAddXpubSlot(
  walletPath: walletPath,
  newMfp: newMfp,
  newXpub: newXpub,
  deviceKeyHex: deviceKeyHex,
  currentXpub: currentXpub,
);

/// Remove an xpub slot by MFP from a XpubKey-protected wallet.
/// Fails if it would leave the wallet with zero slots.
Future<void> removeXpubSlot({
  required String walletPath,
  required String mfp,
}) => RustLib.instance.api.crateApiWalletRemoveXpubSlot(
  walletPath: walletPath,
  mfp: mfp,
);

/// List all registered xpub slots for a XpubKey-protected wallet, including derivation hints.
Future<List<APIXpubSlot>> listXpubSlots({required String walletPath}) =>
    RustLib.instance.api.crateApiWalletListXpubSlots(walletPath: walletPath);

/// Validate a mnemonic phrase and return its MFP without storing anything.
Future<APIHotKeyInfo> validateMnemonic({
  required String mnemonic,
  String? passphrase,
  required APINetwork network,
}) => RustLib.instance.api.crateApiWalletValidateMnemonic(
  mnemonic: mnemonic,
  passphrase: passphrase,
  network: network,
);

/// `derivation_path` may include or omit the leading `m/`.
/// Returns a string suitable for use in a Bitcoin descriptor.
Future<String> deriveKeyspec({
  required String mnemonic,
  String? passphrase,
  required String derivationPath,
  required APINetwork network,
}) => RustLib.instance.api.crateApiWalletDeriveKeyspec(
  mnemonic: mnemonic,
  passphrase: passphrase,
  derivationPath: derivationPath,
  network: network,
);

/// Derive a public keyspec `[mfp/path]xpub` from a master xprv and derivation path.
///
/// `xprv_str` must be a depth-0 master key.
/// `derivation_path` may include or omit the leading `m/`.
Future<String> deriveKeyspecFromXprv({
  required String xprvStr,
  required String derivationPath,
}) => RustLib.instance.api.crateApiWalletDeriveKeyspecFromXprv(
  xprvStr: xprvStr,
  derivationPath: derivationPath,
);

/// Store a mnemonic as a signing key for a project.
///
/// Validates the mnemonic, computes the MFP, and persists it in the
/// shared `project_seeds.db` (SQLCipher, device-key protected).
APIHotKeyInfo addProjectMnemonicKey({
  required String appSupportDir,
  required PlatformInt64 projectId,
  required String mnemonic,
  String? passphrase,
  required APINetwork network,
  required String deviceKeyHex,
}) => RustLib.instance.api.crateApiWalletAddProjectMnemonicKey(
  appSupportDir: appSupportDir,
  projectId: projectId,
  mnemonic: mnemonic,
  passphrase: passphrase,
  network: network,
  deviceKeyHex: deviceKeyHex,
);

/// Store a master xprv (depth-0 only) as a signing key for a project.
APIHotKeyInfo addProjectXprvKey({
  required String appSupportDir,
  required PlatformInt64 projectId,
  required String xprv,
  required String deviceKeyHex,
}) => RustLib.instance.api.crateApiWalletAddProjectXprvKey(
  appSupportDir: appSupportDir,
  projectId: projectId,
  xprv: xprv,
  deviceKeyHex: deviceKeyHex,
);

/// List all project signing keys (never exposes the seed itself).
List<APIHotKeyInfo> listProjectHotKeys({
  required String appSupportDir,
  required PlatformInt64 projectId,
  required String deviceKeyHex,
}) => RustLib.instance.api.crateApiWalletListProjectHotKeys(
  appSupportDir: appSupportDir,
  projectId: projectId,
  deviceKeyHex: deviceKeyHex,
);

/// Remove a project signing key by MFP.
void deleteProjectHotKey({
  required String appSupportDir,
  required PlatformInt64 projectId,
  required String mfp,
  required String deviceKeyHex,
}) => RustLib.instance.api.crateApiWalletDeleteProjectHotKey(
  appSupportDir: appSupportDir,
  projectId: projectId,
  mfp: mfp,
  deviceKeyHex: deviceKeyHex,
);

/// Reveal the stored seed phrase or xprv for a project signing key.
///
/// Call only after showing an appropriate warning to the user.
String revealProjectSeed({
  required String appSupportDir,
  required PlatformInt64 projectId,
  required String mfp,
  required String deviceKeyHex,
}) => RustLib.instance.api.crateApiWalletRevealProjectSeed(
  appSupportDir: appSupportDir,
  projectId: projectId,
  mfp: mfp,
  deviceKeyHex: deviceKeyHex,
);

/// Copy all signing keys from a project's encrypted seeds DB into a wallet.
///
/// Returns the number of keys copied.
int copyProjectKeysToWallet({
  required String appSupportDir,
  required PlatformInt64 projectId,
  required String walletPath,
  required String deviceKeyHex,
  String? walletPassword,
}) => RustLib.instance.api.crateApiWalletCopyProjectKeysToWallet(
  appSupportDir: appSupportDir,
  projectId: projectId,
  walletPath: walletPath,
  deviceKeyHex: deviceKeyHex,
  walletPassword: walletPassword,
);

/// Strip non-essential fields from a PSBT to reduce QR code size.
///
/// Returns the BIP39 English wordlist (2048 words, alphabetically sorted).
List<String> bip39Wordlist() =>
    RustLib.instance.api.crateApiWalletBip39Wordlist();

/// Returns all BIP39 words that, when appended to `partial_words`, produce a valid
/// mnemonic of a supported BIP39 length (12, 15, 18, 21, or 24 words) and start
/// with `prefix`.
///
/// `partial_words` must contain exactly (target_length - 1) words, e.g. 11 words
/// for a 12-word mnemonic. Returns an empty list if the count is wrong.
List<String> bip39ValidLastWords({
  required String partialWords,
  required String prefix,
}) => RustLib.instance.api.crateApiWalletBip39ValidLastWords(
  partialWords: partialWords,
  prefix: prefix,
);

/// Removes `non_witness_utxo` (full previous transaction, ~200-500 B per input)
/// when `witness_utxo` is present (segwit/taproot inputs), plus all `proprietary`
/// and `unknown` fields from global, inputs, and outputs.
///
/// The stored PSBT is never modified — this is only used for QR export.
Future<String> stripPsbtForHw({required String psbtBase64}) =>
    RustLib.instance.api.crateApiWalletStripPsbtForHw(psbtBase64: psbtBase64);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<APIWallet>>
abstract class ApiWallet implements RustOpaqueInterface {
  /// Import a mnemonic phrase as a signing key. Validates the words, computes
  /// the MFP, and stores the seed in the encrypted wallet database.
  APIHotKeyInfo addMnemonicKey({required String mnemonic, String? passphrase});

  /// Import a master xprv (depth=0 only) as a signing key.
  APIHotKeyInfo addXprvKey({required String xprv});

  /// Analyze partial signatures present in a PSBT.
  ///
  /// Returns signing status per MFP (must sign every input to count as signed)
  /// and whether all inputs are already finalized.
  Future<APIPsbtAnalysis> analyzePsbt({
    required String psbtBase64,
    required List<String> mfps,
  });

  String get path;

  set path(String path);

  /// Finalize the PSBT, broadcast via Electrum, and delete the local record.
  ///
  /// Returns the broadcast txid on success.
  Future<String> broadcastPsbt({
    required PlatformInt64 id,
    required String electrumUrl,
  });

  /// Change the wallet's encryption protection scheme.
  ///
  /// Generates a fresh SQLCipher data key and re-encrypts the database
  /// in-place via `PRAGMA rekey` — the existing connection stays open and
  /// operational throughout. The `.meta` sidecar is then rewritten with the
  /// new scheme. No export/import required.
  ///
  /// After this call the Dart layer must update its credential cache:
  /// - `DeviceKey` → evict any cached password (automatic unlock).
  /// - `UserPassword` → cache `new_password`.
  /// - `XpubKey` → evict any cached password (user enters xpub on next open).
  Future<void> changeProtection({
    required String deviceKeyHex,
    required APIProtectionType newProtectionType,
    String? newPassword,
    required APISecurityLevel securityLevel,
  });

  /// Delete all stored fiat prices (called when the user changes fiat currency).
  Future<void> clearFiatPrices();

  /// Build an unsigned PSBT with optional coin control and spend-path selection.
  ///
  /// * `recipients`           — one or more outputs; each has an address and amount.
  /// * `max_recipient_index`  — if `Some(i)`, recipient at index `i` gets the wallet
  ///   remainder (drain_to); its `amount_sat` field is ignored.
  ///   Pass `None` when every amount is explicit.
  /// * `selected_utxos` — if non-empty, only those coins are used.
  ///   Empty = BDK automatic coin selection.
  /// * `policy_path`    — spend-path branch selections from [APISpendPath.policyPath].
  /// * `spend_path_id`  — rust_id of the selected spend path (stored for reference).
  /// * `threshold`      — required signatures (from the spend path).
  /// * `mfps`           — master fingerprints of keys in the spend path.
  APIPsbtInfo createPsbt({
    required List<APIRecipient> recipients,
    int? maxRecipientIndex,
    required double feeRateSatPerVb,
    required List<APICoinControl> selectedUtxos,
    required List<APIPolicyPath> policyPath,
    required int spendPathId,
    required int threshold,
    required List<String> mfps,
  });

  /// Remove a hot signing key by MFP.
  void deleteHotKey({required String mfp});

  /// Delete a saved PSBT by id.
  void deletePsbt({required PlatformInt64 id});

  /// Derive the WIF-encoded private key for a specific address in this wallet.
  ///
  /// Looks up the address in the wallet's SPK index to find its keychain and
  /// derivation index, then combines that with the account path extracted from
  /// the wallet descriptor and the stored seed to produce the leaf private key,
  /// serialized in Wallet Import Format (WIF).
  ///
  /// Only valid for single-sig hot wallets. Call only after showing an
  /// appropriate security disclaimer — WIF exposes a spendable private key.
  String deriveAddressWif({required String address, required String mfp});

  /// Export all explicit (non-auto) labels to BIP-329 JSONL format.
  List<String> exportBip329();

  /// Return full detail for an address: the address plus its unspent UTXOs.
  Future<APIAddressDetails> getAddressDetails({required String address});

  /// Return all currently revealed addresses for the given keychain, sorted by index ascending.
  /// Balance is the sum of all unspent outputs currently controlled by each address.
  Future<List<APIAddress>> getAddresses({required APIKeychain keychain});

  /// Return the cached balance (no network call).
  Future<APIBalance> getBalance();

  /// Return the aggregate fee info for the full unconfirmed ancestor package of the given
  /// parent txids. Performs a BFS through the tx graph to collect all unconfirmed ancestors
  /// transitively (parents, grandparents, …), summing their fees and vsizes to compute the
  /// effective package fee rate that miners use when evaluating CPFP.
  ///
  /// `parent_txids` should be the txids of the unconfirmed UTXOs being spent as child inputs.
  Future<APICpfpInfo> getCpfpInfo({required List<String> parentTxids});

  /// Return all stored BTC prices for `currency` as a list of (txid, price) pairs.
  Future<List<APIFiatPrice>> getFiatPrices({required String currency});

  /// Read wallet metadata from the open connection (no file re-open).
  Future<APIWalletInfo> getInfo();

  /// Return all key labels (mfp → label).
  Future<List<APIKeyLabel>> getKeyLabels();

  /// Return all spend-path labels (rust_id → label).
  Future<List<APIPathLabel>> getPathLabels();

  /// Return RBF replacement constraints for a mempool tx spending one of our UTXOs.
  /// Fetches parent txs from Electrum when fee cannot be determined from the wallet graph.
  Future<APIRbfInfo> getRbfInfo({required String spendingTxid});

  /// Return the current best block height from the local chain (0 if not yet synced).
  Future<int> getTipHeight();

  /// Return a paginated page of transactions, sorted newest-first (no network call).
  Future<APITransactionPage> getTransactions({
    required int page,
    required int pageSize,
  });

  /// Return full detail for a transaction: the tx plus related UTXOs, input addresses,
  /// and output addresses. External input transactions not in BDK's graph are fetched
  /// from Electrum (using the URL stored from the last sync).
  Future<APITxDetails> getTxDetails({required String txid});

  /// Return transactions that have no stored fiat price for `currency`.
  Future<List<APITxMissingFiat>> getTxidsMissingFiat({
    required String currency,
  });

  /// Return full detail for a UTXO: the UTXO plus the explicit labels of its cluster peers.
  Future<APIUtxoDetails> getUtxoDetails({
    required String txid,
    required int vout,
  });

  /// Return all unspent outputs (UTXOs / coins), sorted by value descending.
  Future<List<APIUtxo>> getUtxos();

  /// Import labels from BIP-329 JSONL. Sets all as explicit, then re-propagates.
  /// Malformed lines and unknown types are silently skipped.
  void importBip329({required List<String> lines});

  /// Import a PSBT (base64) from an external source.
  ///
  /// If a record with the same unsigned txid already exists, the signatures are
  /// merged and the existing record is updated (`was_merged = true`).
  /// Otherwise a new record is created with metadata extracted from the PSBT.
  Future<APIImportPsbtResult> importPsbt({required String psbtBase64});

  /// List all hot signing keys stored in this wallet (never exposes the seed).
  List<APIHotKeyInfo> listHotKeys();

  /// Return all saved unsigned PSBTs for this wallet, newest-first.
  Future<List<APIPsbtInfo>> listPsbts();

  /// Merge partial signatures from a signed PSBT into the stored one.
  ///
  /// The signed PSBT must refer to the same transaction (same inputs/outputs).
  /// Returns the updated info.
  APIPsbtInfo mergePsbt({
    required PlatformInt64 id,
    required String signedPsbtBase64,
  });

  /// Repropagate all existing explicit labels to their related entities.
  /// Useful after imports or migrations. Clears all auto labels first.
  void repropagateAllLabels();

  /// Force a full scan regardless of sync history (re-discovers all addresses).
  Future<void> rescan({required String electrumUrl});

  /// Reveal the stored seed phrase or xprv for a hot signing key.
  ///
  /// The SQLCipher layer already protects this data at rest; this function
  /// exposes it in plaintext for display purposes only. Call only when the
  /// user explicitly requests it and after showing an appropriate disclaimer.
  String revealHotKey({required String mfp});

  /// Reveal `count` new addresses for the given keychain beyond those already revealed,
  /// then persist the wallet. Returns the new total number of revealed addresses.
  int revealMoreAddresses({required APIKeychain keychain, required int count});

  /// Persist a label for an address. Pass an empty string to remove it.
  /// Automatically propagates to related entities (transactions and UTXOs).
  /// Clearing an inherited (auto) label is a no-op.
  void setAddressLabel({required String address, required String label});

  /// Persist a label for a coin (UTXO) by outpoint. Pass an empty string to remove it.
  /// Automatically propagates to related entities (transaction and address).
  /// Clearing an inherited (auto) label is a no-op.
  void setCoinLabel({
    required String txid,
    required int vout,
    required String label,
  });

  /// Store the Electrum URL so it can be used by detail queries (e.g. fetching
  /// unknown input transactions). Call this before sync if you want it available
  /// immediately without waiting for sync to complete.
  void setElectrumUrl({required String url});

  /// Persist a label for a key by master fingerprint. Pass an empty string to remove it.
  void setKeyLabel({required String mfp, required String label});

  /// Persist a label for a spend path by rust_id. Pass an empty string to remove it.
  void setPathLabel({required int rustId, required String label});

  /// Set or clear the label for a saved PSBT. Pass an empty string to clear.
  APIPsbtInfo setPsbtLabel({required PlatformInt64 id, required String label});

  /// Persist a label for a transaction. Pass an empty string to remove it.
  /// Automatically propagates to related entities (addresses and UTXOs).
  /// Clearing an inherited (auto) label is a no-op.
  void setTxLabel({required String txid, required String label});

  /// Sign a stored PSBT using the hot key identified by `mfp`.
  ///
  /// Only the signer for the given master fingerprint is loaded, so BDK can
  /// never accidentally sign with a key the user did not intend. The PSBT is
  /// **never auto-finalized** (`try_finalize: false`) — the user explicitly
  /// controls finalization, which prevents premature finalization in multisig
  /// or complex Taproot setups where BDK might otherwise finalize on the first
  /// satisfied threshold.
  ///
  /// Returns the updated [`APIPsbtInfo`] with the partial signatures added.
  APIPsbtInfo signPsbtWithKey({
    required PlatformInt64 psbtId,
    required String mfp,
  });

  /// Open a reactive Electrum subscription for this wallet.
  ///
  /// Subscribes to block headers + all revealed SPKs of the wallet.
  /// Emits `true` through `sink` whenever a notification arrives
  /// (new block or scriptpubkey activity). The caller should trigger
  /// a sync on each event.
  ///
  /// Returns immediately; the listener runs on a blocking thread.
  /// The loop exits when the Dart sink is closed (StreamSubscription.cancel).
  Stream<bool> startSubscription({required String electrumUrl});

  /// Store (or replace) the BTC price in `currency` at the time of a transaction.
  Future<void> storeFiatPrice({
    required String txid,
    required String currency,
    required double btcPrice,
  });

  /// Sync with Electrum, persist, and update last_synced_at.
  ///
  /// Uses full_scan on first sync (last_synced_at is None) to discover all addresses
  /// up to the stop gap. Uses incremental sync on subsequent calls to only check
  /// already-revealed script pubkeys, which is much faster.
  Future<void> sync_({required String electrumUrl});

  /// Return the network for this wallet.
  APINetwork walletNetwork();
}

/// A key label entry returned from [APIWallet::get_key_labels].
class APIKeyLabel {
  final String mfp;
  final String label;

  const APIKeyLabel({required this.mfp, required this.label});

  @override
  int get hashCode => mfp.hashCode ^ label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIKeyLabel &&
          runtimeType == other.runtimeType &&
          mfp == other.mfp &&
          label == other.label;
}

/// A spend-path label entry returned from [APIWallet::get_path_labels].
class APIPathLabel {
  final int rustId;
  final String label;

  const APIPathLabel({required this.rustId, required this.label});

  @override
  int get hashCode => rustId.hashCode ^ label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIPathLabel &&
          runtimeType == other.runtimeType &&
          rustId == other.rustId &&
          label == other.label;
}
