// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'model.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_psbt_label_to_tx`, `build_addr_utxo_map`, `build_tx_utxo_map`, `cascade_delete_label`, `extract_xpub_mfp_map`, `propagate_label`, `psbt_from_base64`, `psbt_max_utxo_conf_height`, `psbt_to_base64`, `resolve_label`, `row_to_api_info`, `row_to_api_psbt`, `source_entity_id`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EntityType`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `eq`, `fmt`

/// Return all wallets found in wallets_dir, sorted newest-first.
Future<List<APIWalletInfo>> listWallets({
  required String walletsDir,
  required String encryptionKeyHex,
}) => RustLib.instance.api.crateApiWalletListWallets(
  walletsDir: walletsDir,
  encryptionKeyHex: encryptionKeyHex,
);

/// Create a new wallet .db file and return its info.
Future<APIWalletInfo> createWallet({
  required String walletsDir,
  required String name,
  required String descriptor,
  required APINetwork network,
  PlatformInt64? sourceProjectId,
  required String encryptionKeyHex,
}) => RustLib.instance.api.crateApiWalletCreateWallet(
  walletsDir: walletsDir,
  name: name,
  descriptor: descriptor,
  network: network,
  sourceProjectId: sourceProjectId,
  encryptionKeyHex: encryptionKeyHex,
);

/// Read metadata from an existing wallet file.
Future<APIWalletInfo> getWalletInfo({
  required String walletPath,
  required String encryptionKeyHex,
}) => RustLib.instance.api.crateApiWalletGetWalletInfo(
  walletPath: walletPath,
  encryptionKeyHex: encryptionKeyHex,
);

/// Rename a wallet (updates wallet_info.name in the file).
Future<void> renameWallet({
  required String walletPath,
  required String name,
  required String encryptionKeyHex,
}) => RustLib.instance.api.crateApiWalletRenameWallet(
  walletPath: walletPath,
  name: name,
  encryptionKeyHex: encryptionKeyHex,
);

/// Delete a wallet's .db, .db-wal, and .db-shm files. No encryption key needed.
Future<void> deleteWallet({required String walletPath}) =>
    RustLib.instance.api.crateApiWalletDeleteWallet(walletPath: walletPath);

/// Open a wallet once and hold the live handle for repeated operations.
///
/// Reads descriptor and network from wallet_info inside the encrypted file,
/// then opens the BDK wallet in a single SQLite connection.
Future<ApiWallet> openWallet({
  required String walletPath,
  required String encryptionKeyHex,
}) => RustLib.instance.api.crateApiWalletOpenWallet(
  walletPath: walletPath,
  encryptionKeyHex: encryptionKeyHex,
);

/// Strip non-essential fields from a PSBT to reduce QR code size.
///
/// Removes `non_witness_utxo` (full previous transaction, ~200-500 B per input)
/// when `witness_utxo` is present (segwit/taproot inputs), plus all `proprietary`
/// and `unknown` fields from global, inputs, and outputs.
///
/// The stored PSBT is never modified — this is only used for QR export.
Future<String> stripPsbtForHw({required String psbtBase64}) =>
    RustLib.instance.api.crateApiWalletStripPsbtForHw(psbtBase64: psbtBase64);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<APIWallet>>
abstract class ApiWallet implements RustOpaqueInterface {
  /// Analyze partial signatures present in a PSBT.
  ///
  /// Returns signing status per MFP (must sign every input to count as signed)
  /// and whether all inputs are already finalized.
  Future<APIPsbtAnalysis> analyzePsbt({
    required String psbtBase64,
    required List<String> mfps,
  });

  String get path;

  set path(String path);

  /// Finalize the PSBT, broadcast via Electrum, and delete the local record.
  ///
  /// Returns the broadcast txid on success.
  Future<String> broadcastPsbt({
    required PlatformInt64 id,
    required String electrumUrl,
  });

  /// Build an unsigned PSBT with optional coin control and spend-path selection.
  ///
  /// * `selected_utxos` — if non-empty, only those coins are used.
  ///   Empty = BDK automatic coin selection.
  /// * `policy_path`    — spend-path branch selections from [APISpendPath.policyPath].
  /// * `spend_path_id`  — rust_id of the selected spend path (stored for reference).
  /// * `threshold`      — required signatures (from the spend path).
  /// * `mfps`           — master fingerprints of keys in the spend path.
  APIPsbtInfo createPsbt({
    required String recipientAddress,
    required BigInt amountSat,
    required double feeRateSatPerVb,
    required List<APICoinControl> selectedUtxos,
    required List<APIPolicyPath> policyPath,
    required int spendPathId,
    required int threshold,
    required List<String> mfps,
    required bool sendMax,
  });

  /// Delete a saved PSBT by id.
  void deletePsbt({required PlatformInt64 id});

  /// Export all explicit (non-auto) labels to BIP-329 JSONL format.
  List<String> exportBip329();

  /// Return full detail for an address: the address plus its unspent UTXOs.
  Future<APIAddressDetails> getAddressDetails({required String address});

  /// Return all currently revealed addresses for the given keychain, sorted by index ascending.
  /// Balance is the sum of all unspent outputs currently controlled by each address.
  Future<List<APIAddress>> getAddresses({required APIKeychain keychain});

  /// Return the cached balance (no network call).
  Future<APIBalance> getBalance();

  /// Read wallet metadata from the open connection (no file re-open).
  Future<APIWalletInfo> getInfo();

  /// Return all key labels (mfp → label).
  Future<List<APIKeyLabel>> getKeyLabels();

  /// Return all spend-path labels (rust_id → label).
  Future<List<APIPathLabel>> getPathLabels();

  /// Return RBF replacement constraints for a mempool tx spending one of our UTXOs.
  /// Fetches parent txs from Electrum when fee cannot be determined from the wallet graph.
  Future<APIRbfInfo> getRbfInfo({required String spendingTxid});

  /// Return the current best block height from the local chain (0 if not yet synced).
  Future<int> getTipHeight();

  /// Return a paginated page of transactions, sorted newest-first (no network call).
  Future<APITransactionPage> getTransactions({
    required int page,
    required int pageSize,
  });

  /// Return full detail for a transaction: the tx plus related UTXOs, input addresses,
  /// and output addresses. External input transactions not in BDK's graph are fetched
  /// from Electrum (using the URL stored from the last sync).
  Future<APITxDetails> getTxDetails({required String txid});

  /// Return full detail for a UTXO: the UTXO plus the explicit labels of its cluster peers.
  Future<APIUtxoDetails> getUtxoDetails({
    required String txid,
    required int vout,
  });

  /// Return all unspent outputs (UTXOs / coins), sorted by value descending.
  Future<List<APIUtxo>> getUtxos();

  /// Import labels from BIP-329 JSONL. Sets all as explicit, then re-propagates.
  /// Malformed lines and unknown types are silently skipped.
  void importBip329({required List<String> lines});

  /// Import a PSBT (base64) from an external source.
  ///
  /// If a record with the same unsigned txid already exists, the signatures are
  /// merged and the existing record is updated (`was_merged = true`).
  /// Otherwise a new record is created with metadata extracted from the PSBT.
  Future<APIImportPsbtResult> importPsbt({required String psbtBase64});

  /// Return all saved unsigned PSBTs for this wallet, newest-first.
  Future<List<APIPsbtInfo>> listPsbts();

  /// Merge partial signatures from a signed PSBT into the stored one.
  ///
  /// The signed PSBT must refer to the same transaction (same inputs/outputs).
  /// Returns the updated info.
  APIPsbtInfo mergePsbt({
    required PlatformInt64 id,
    required String signedPsbtBase64,
  });

  /// Repropagate all existing explicit labels to their related entities.
  /// Useful after imports or migrations. Clears all auto labels first.
  void repropagateAllLabels();

  /// Force a full scan regardless of sync history (re-discovers all addresses).
  Future<void> rescan({required String electrumUrl});

  /// Reveal `count` new addresses for the given keychain beyond those already revealed,
  /// then persist the wallet. Returns the new total number of revealed addresses.
  int revealMoreAddresses({required APIKeychain keychain, required int count});

  /// Persist a label for an address. Pass an empty string to remove it.
  /// Automatically propagates to related entities (transactions and UTXOs).
  /// Clearing an inherited (auto) label is a no-op.
  void setAddressLabel({required String address, required String label});

  /// Persist a label for a coin (UTXO) by outpoint. Pass an empty string to remove it.
  /// Automatically propagates to related entities (transaction and address).
  /// Clearing an inherited (auto) label is a no-op.
  void setCoinLabel({
    required String txid,
    required int vout,
    required String label,
  });

  /// Store the Electrum URL so it can be used by detail queries (e.g. fetching
  /// unknown input transactions). Call this before sync if you want it available
  /// immediately without waiting for sync to complete.
  void setElectrumUrl({required String url});

  /// Persist a label for a key by master fingerprint. Pass an empty string to remove it.
  void setKeyLabel({required String mfp, required String label});

  /// Persist a label for a spend path by rust_id. Pass an empty string to remove it.
  void setPathLabel({required int rustId, required String label});

  /// Set or clear the label for a saved PSBT. Pass an empty string to clear.
  APIPsbtInfo setPsbtLabel({required PlatformInt64 id, required String label});

  /// Persist a label for a transaction. Pass an empty string to remove it.
  /// Automatically propagates to related entities (addresses and UTXOs).
  /// Clearing an inherited (auto) label is a no-op.
  void setTxLabel({required String txid, required String label});

  /// Sync with Electrum, persist, and update last_synced_at.
  ///
  /// Uses full_scan on first sync (last_synced_at is None) to discover all addresses
  /// up to the stop gap. Uses incremental sync on subsequent calls to only check
  /// already-revealed script pubkeys, which is much faster.
  Future<void> sync_({required String electrumUrl});
}

/// A key label entry returned from [APIWallet::get_key_labels].
class APIKeyLabel {
  final String mfp;
  final String label;

  const APIKeyLabel({required this.mfp, required this.label});

  @override
  int get hashCode => mfp.hashCode ^ label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIKeyLabel &&
          runtimeType == other.runtimeType &&
          mfp == other.mfp &&
          label == other.label;
}

/// A spend-path label entry returned from [APIWallet::get_path_labels].
class APIPathLabel {
  final int rustId;
  final String label;

  const APIPathLabel({required this.rustId, required this.label});

  @override
  int get hashCode => rustId.hashCode ^ label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIPathLabel &&
          runtimeType == other.runtimeType &&
          rustId == other.rustId &&
          label == other.label;
}
