// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'model.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `estimate_sweep_fee`, `make_ecdsa_sig`, `sign_p2pkh_input`, `sign_p2sh_wpkh_input`, `sign_p2wpkh_input`

/// Derive the P2WPKH, P2PKH, and P2SH-P2WPKH addresses controlled by `wif`.
///
/// Returns them in that order so callers can display them for the user to
/// identify which address type holds funds.
Future<List<APIWifAddress>> resolveWif({
  required String wif,
  required APINetwork network,
}) =>
    RustLib.instance.api.crateApiWifSweepResolveWif(wif: wif, network: network);

/// Query Electrum for all UTXOs controlled by `wif` across all supported
/// address types (P2WPKH, P2PKH, P2SH-P2WPKH).
Future<List<APIWifUtxo>> queryWifUtxos({
  required String wif,
  required APINetwork network,
  required String electrumUrl,
}) => RustLib.instance.api.crateApiWifSweepQueryWifUtxos(
  wif: wif,
  network: network,
  electrumUrl: electrumUrl,
);

/// Sweep all funds controlled by `wif` to `destination_address`.
///
/// Queries Electrum for UTXOs, builds a transaction spending all of them to
/// `destination_address` (minus fee), signs each input, and broadcasts.
///
/// Returns the transaction ID of the broadcast transaction.
Future<String> sweepWif({
  required String wif,
  required String destinationAddress,
  required double feeRateSatPerVb,
  required String electrumUrl,
  required APINetwork network,
}) => RustLib.instance.api.crateApiWifSweepSweepWif(
  wif: wif,
  destinationAddress: destinationAddress,
  feeRateSatPerVb: feeRateSatPerVb,
  electrumUrl: electrumUrl,
  network: network,
);

/// A single address derived from a WIF key.
class APIWifAddress {
  /// One of: `"p2wpkh"`, `"p2pkh"`, `"p2sh_wpkh"`.
  final String addressType;
  final String address;

  const APIWifAddress({required this.addressType, required this.address});

  @override
  int get hashCode => addressType.hashCode ^ address.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIWifAddress &&
          runtimeType == other.runtimeType &&
          addressType == other.addressType &&
          address == other.address;
}

/// A UTXO controlled by a WIF key.
class APIWifUtxo {
  final String txid;
  final int vout;
  final BigInt valueSat;
  final String address;

  /// Same type string as in [`APIWifAddress::address_type`].
  final String addressType;

  const APIWifUtxo({
    required this.txid,
    required this.vout,
    required this.valueSat,
    required this.address,
    required this.addressType,
  });

  @override
  int get hashCode =>
      txid.hashCode ^
      vout.hashCode ^
      valueSat.hashCode ^
      address.hashCode ^
      addressType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIWifUtxo &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          vout == other.vout &&
          valueSat == other.valueSat &&
          address == other.address &&
          addressType == other.addressType;
}
